BEGIN
PERFORM EXISTS (SELECT marketing.auto_generate_visiting_schedule());
PERFORM EXISTS (SELECT marketing.cancel_purchase_advance_receipt_to_edit_test(null, null));
PERFORM EXISTS (SELECT marketing.cek_is_allowed_edit(null));
PERFORM EXISTS (SELECT marketing.check_batch_and_update_exp_date(null));
PERFORM EXISTS (SELECT marketing.check_item_selling_price_level(null, 0.0));
PERFORM EXISTS (SELECT marketing.copy_incentive_matrix_from_selected_period(null, null, null));
PERFORM EXISTS (SELECT marketing.copy_purchase_advance_receipt_to_edit_test(null));
PERFORM EXISTS (SELECT marketing.cust_outl_by_instance(null));
PERFORM EXISTS (SELECT marketing.customer_deposit_report_detail(null, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT marketing.customer_deposit_report_detail_beginning(null, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT marketing.customer_deposit_report_parent(CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT marketing.customer_deposit_report_print_detail(null, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT marketing.customer_deposit_report_print_parent(CURRENT_DATE, CURRENT_DATE, null, null));
PERFORM EXISTS (SELECT marketing.customer_summary_deposit_report_parent(CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT marketing.customer_summary_deposit_report_print_parent(CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT marketing.delete_not_used_gtnd_data(null, FALSE, null));
PERFORM EXISTS (SELECT marketing.delivery_allocation_detail_for_edit(null));
PERFORM EXISTS (SELECT marketing.delivery_allocation_detail_for_list(null));
PERFORM EXISTS (SELECT marketing.delivery_order_allocation_for_edit(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null, FALSE, null));
PERFORM EXISTS (SELECT marketing.delivery_order_allocation_for_list(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null, FALSE, null));
PERFORM EXISTS (SELECT marketing.delivery_order_detail_update_ordered(null, null));
PERFORM EXISTS (SELECT marketing.delivery_order_detail_update_ordered_remove(null, null));
PERFORM EXISTS (SELECT marketing.delivery_order_ordered_canceled(null));
PERFORM EXISTS (SELECT marketing.delivery_order_ordered_remove_new(null, null));
PERFORM EXISTS (SELECT marketing.delivery_order_update_ordered(null, null, null));
PERFORM EXISTS (SELECT marketing.delivery_order_update_ordered_edit(null, null, null, null));
PERFORM EXISTS (SELECT marketing.do_update_so(null, null));
PERFORM EXISTS (SELECT marketing.do_update_so_edit(null, null));
PERFORM EXISTS (SELECT marketing.do_update_stock(null, null, null));
PERFORM EXISTS (SELECT marketing.generate_fp_number(null, null, null));
PERFORM EXISTS (SELECT marketing.generate_target_certain_product(null, null, null));
PERFORM EXISTS (SELECT marketing.generate_turnover_target(null, null, null, null));
PERFORM EXISTS (SELECT marketing.generate_turnover_target(null, null, null));
PERFORM EXISTS (SELECT marketing.get_advance_receipt_edit(null, FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT marketing.get_all_customers(null));
PERFORM EXISTS (SELECT marketing.get_brands());
PERFORM EXISTS (SELECT marketing.get_brands_json(null));
PERFORM EXISTS (SELECT marketing.get_business_partner_address_json(null));
PERFORM EXISTS (SELECT marketing.get_business_partner_bank_json(null));
PERFORM EXISTS (SELECT marketing.get_business_partner_contact_json(null));
PERFORM EXISTS (SELECT marketing.get_current_certain_product(null, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT marketing.get_current_incentive_matrix(null, null, null));
PERFORM EXISTS (SELECT marketing.get_current_price_list(null, FALSE));
PERFORM EXISTS (SELECT marketing.get_current_sales_expense_calculation(null, null, null));
PERFORM EXISTS (SELECT marketing.get_current_target_calculation(null, null, null));
PERFORM EXISTS (SELECT marketing.get_customer(null));
PERFORM EXISTS (SELECT marketing.get_customer_and_outlet_by_category(null, null));
PERFORM EXISTS (SELECT marketing.get_customer_and_outlet_by_instance(null));
PERFORM EXISTS (SELECT marketing.get_customer_and_outlet_by_warehouse_config(null));
PERFORM EXISTS (SELECT marketing.get_customer_and_outlet_by_warehouse_config_concat(null));
PERFORM EXISTS (SELECT marketing.get_customer_and_outlet_shipto_concat(null));
PERFORM EXISTS (SELECT marketing.get_customer_category(null));
PERFORM EXISTS (SELECT marketing.get_customer_category_json(null));
PERFORM EXISTS (SELECT marketing.get_customer_code(null));
PERFORM EXISTS (SELECT marketing.get_customer_delivery_concat(null));
PERFORM EXISTS (SELECT marketing.get_customer_delivery_json(null));
PERFORM EXISTS (SELECT marketing.get_customer_json(null));
PERFORM EXISTS (SELECT marketing.get_customers(null));
PERFORM EXISTS (SELECT marketing.get_customers_for_cr(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT marketing.get_data_master_tax_number(null));
PERFORM EXISTS (SELECT marketing.get_data_new_sales_advance_detail(null, null));
PERFORM EXISTS (SELECT marketing.get_data_sales_request_edit(null));
PERFORM EXISTS (SELECT marketing.get_default_settings_minimum_visiting_count_json(null));
PERFORM EXISTS (SELECT marketing.get_default_settings_selling_price_sales_json(null));
PERFORM EXISTS (SELECT marketing.get_delivery_order_allocation_detail_json(null));
PERFORM EXISTS (SELECT marketing.get_delivery_order_allocation_json(null));
PERFORM EXISTS (SELECT marketing.get_delivery_order_term_json(null));
PERFORM EXISTS (SELECT marketing.get_delivery_term_by_instance());
PERFORM EXISTS (SELECT marketing.get_detail_pareto_transaction_per_period(null, CURRENT_DATE, CURRENT_DATE, null, null, null));
PERFORM EXISTS (SELECT marketing.get_discount_by_level(null));
PERFORM EXISTS (SELECT marketing.get_distribution_plan_json(null));
PERFORM EXISTS (SELECT marketing.get_distribution_plan_product(null));
PERFORM EXISTS (SELECT marketing.get_distribution_plan_product_json(null));
PERFORM EXISTS (SELECT marketing.get_distribution_plan_sales(null));
PERFORM EXISTS (SELECT marketing.get_distribution_plan_sales_json(null));
PERFORM EXISTS (SELECT marketing.get_do_qty_summary(null));
PERFORM EXISTS (SELECT marketing.get_expedition_json(null));
PERFORM EXISTS (SELECT marketing.get_fixed_forecast_json(null));
PERFORM EXISTS (SELECT marketing.get_generate_tax_number(null, null, null));
PERFORM EXISTS (SELECT marketing.get_generate_tax_number_cancel(null, null, null));
PERFORM EXISTS (SELECT marketing.get_generate_tax_number_detail_json(null));
PERFORM EXISTS (SELECT marketing.get_generate_tax_number_for_ar());
PERFORM EXISTS (SELECT marketing.get_generate_tax_number_json(null));
PERFORM EXISTS (SELECT marketing.get_gross_profit(null, null));
PERFORM EXISTS (SELECT marketing.get_incentive_detail(null, 0));
PERFORM EXISTS (SELECT marketing.get_incentive_turnover_percent(null, null, null));
PERFORM EXISTS (SELECT marketing.get_journal_for_expense_and_stock(null, 0));
PERFORM EXISTS (SELECT marketing.get_level(null));
PERFORM EXISTS (SELECT marketing.get_master_level_json(null));
PERFORM EXISTS (SELECT marketing.get_master_plaftorm(null));
PERFORM EXISTS (SELECT marketing.get_master_platform_json(null));
PERFORM EXISTS (SELECT marketing.get_master_route_json(null));
PERFORM EXISTS (SELECT marketing.get_matrix_target(null, 0));
PERFORM EXISTS (SELECT marketing.get_member_category());
PERFORM EXISTS (SELECT marketing.get_member_category_json(null));
PERFORM EXISTS (SELECT marketing.get_member_discount_json(null));
PERFORM EXISTS (SELECT marketing.get_member_discount_parameter(null, null));
PERFORM EXISTS (SELECT marketing.get_minimum_visiting_a_day(null));
PERFORM EXISTS (SELECT marketing.get_new_data_delivery_order(null));
PERFORM EXISTS (SELECT marketing.get_new_data_sales_order(null));
PERFORM EXISTS (SELECT marketing.get_new_update_business_partner_category(null));
PERFORM EXISTS (SELECT marketing.get_new_update_business_partner_suplier(null));
PERFORM EXISTS (SELECT marketing.get_new_update_customer(null));
PERFORM EXISTS (SELECT marketing.get_new_update_customer_category(null));
PERFORM EXISTS (SELECT marketing.get_new_update_customer_online(null));
PERFORM EXISTS (SELECT marketing.get_new_update_master_level(null));
PERFORM EXISTS (SELECT marketing.get_new_update_master_platform(null));
PERFORM EXISTS (SELECT marketing.get_new_update_master_route(null));
PERFORM EXISTS (SELECT marketing.get_outlet_category(null));
PERFORM EXISTS (SELECT marketing.get_outlet_category_json(null));
PERFORM EXISTS (SELECT marketing.get_outlet_images_json(null));
PERFORM EXISTS (SELECT marketing.get_outlet_qrcode_batch_draft_json(null));
PERFORM EXISTS (SELECT marketing.get_outlet_qrcode_batch_items_draft_json(null));
PERFORM EXISTS (SELECT marketing.get_outlet_qrcode_batch_items_json(null));
PERFORM EXISTS (SELECT marketing.get_outlet_qrcode_batch_json(null));
PERFORM EXISTS (SELECT marketing.get_outlet_qrcodes_json(null));
PERFORM EXISTS (SELECT marketing.get_outlet_regional_exclusive_json(null));
PERFORM EXISTS (SELECT marketing.get_outlets(null));
PERFORM EXISTS (SELECT marketing.get_outlets_by_sales_person(null, null, null));
PERFORM EXISTS (SELECT marketing.get_outlets_feedback_json(null));
PERFORM EXISTS (SELECT marketing.get_outlets_json(null));
PERFORM EXISTS (SELECT marketing.get_pareto_outlet_achievement(null, null, null));
PERFORM EXISTS (SELECT marketing.get_pareto_outlet_periods_by_sales_person(null));
PERFORM EXISTS (SELECT marketing.get_plaftorm_by_instance(null));
PERFORM EXISTS (SELECT marketing.get_price_category_by_parent_instance(null));
PERFORM EXISTS (SELECT marketing.get_price_list_json(null));
PERFORM EXISTS (SELECT marketing.get_price_list_products_json(null));
PERFORM EXISTS (SELECT marketing.get_price_list_regions_json(null));
PERFORM EXISTS (SELECT marketing.get_pricelist_and_shipto_by_concat(null));
PERFORM EXISTS (SELECT marketing.get_pricelist_by_parent_instance(null));
PERFORM EXISTS (SELECT marketing.get_product_taxes_json(null));
PERFORM EXISTS (SELECT marketing.get_promo_free_item_benefit_json(null));
PERFORM EXISTS (SELECT marketing.get_promo_json(null));
PERFORM EXISTS (SELECT marketing.get_promo_member_json(null));
PERFORM EXISTS (SELECT marketing.get_promo_requirement_json(null));
PERFORM EXISTS (SELECT marketing.get_regionals_json(null));
PERFORM EXISTS (SELECT marketing.get_route());
PERFORM EXISTS (SELECT marketing.get_route_by_instance(null));
PERFORM EXISTS (SELECT marketing.get_sa_for_sales_lite(null, null));
PERFORM EXISTS (SELECT marketing.get_sa_nominal(null, null));
PERFORM EXISTS (SELECT marketing.get_sales_advance_deposit_edit(FALSE, CURRENT_DATE, CURRENT_DATE, null, null));
PERFORM EXISTS (SELECT marketing.get_sales_advance_detail_edit(null, FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT marketing.get_sales_advance_detail_json(null));
PERFORM EXISTS (SELECT marketing.get_sales_advance_json(null));
PERFORM EXISTS (SELECT marketing.get_sales_advance_parent_edit(FALSE, CURRENT_DATE, CURRENT_DATE, null, null));
PERFORM EXISTS (SELECT marketing.get_sales_forecast_detail_json(null));
PERFORM EXISTS (SELECT marketing.get_sales_forecast_json(null));
PERFORM EXISTS (SELECT marketing.get_sales_product(null, null));
PERFORM EXISTS (SELECT marketing.get_sales_products_json(null));
PERFORM EXISTS (SELECT marketing.get_sales_products_target(null));
PERFORM EXISTS (SELECT marketing.get_sales_return_receive_detail_json(null));
PERFORM EXISTS (SELECT marketing.get_sales_return_receive_json(null));
PERFORM EXISTS (SELECT marketing.get_sales_return_request_detail_json(null));
PERFORM EXISTS (SELECT marketing.get_sales_return_request_json(null));
PERFORM EXISTS (SELECT marketing.get_sales_salary_default(null));
PERFORM EXISTS (SELECT marketing.get_sales_salary_default_json(null));
PERFORM EXISTS (SELECT marketing.get_selling_price_categori_json(null));
PERFORM EXISTS (SELECT marketing.get_selling_price_category());
PERFORM EXISTS (SELECT marketing.get_selling_price_category_details_json(null));
PERFORM EXISTS (SELECT marketing.get_selling_price_category_json(null));
PERFORM EXISTS (SELECT marketing.get_selling_price_category_profit_json(null));
PERFORM EXISTS (SELECT marketing.get_selling_price_detail_json(null));
PERFORM EXISTS (SELECT marketing.get_selling_price_discount_items_draft_json(null));
PERFORM EXISTS (SELECT marketing.get_selling_price_discount_items_json(null));
PERFORM EXISTS (SELECT marketing.get_selling_price_draft_json(null));
PERFORM EXISTS (SELECT marketing.get_selling_price_items_draft_json(null));
PERFORM EXISTS (SELECT marketing.get_selling_price_items_json(null));
PERFORM EXISTS (SELECT marketing.get_selling_price_json(null));
PERFORM EXISTS (SELECT marketing.get_selling_price_product_items_draft_json(null));
PERFORM EXISTS (SELECT marketing.get_selling_price_product_items_json(null));
PERFORM EXISTS (SELECT marketing.get_selling_price_tax_items_draft_json(null));
PERFORM EXISTS (SELECT marketing.get_selling_price_tax_items_json(null));
PERFORM EXISTS (SELECT marketing.get_selling_price_tax_json(null));
PERFORM EXISTS (SELECT marketing.get_shipping_order_detail_json(null));
PERFORM EXISTS (SELECT marketing.get_shipping_order_json(null));
PERFORM EXISTS (SELECT marketing.get_so_id(null));
PERFORM EXISTS (SELECT marketing.get_sub_outlets(null, 0, FALSE));
PERFORM EXISTS (SELECT marketing.get_supplier_address_json(null));
PERFORM EXISTS (SELECT marketing.get_supplier_all());
PERFORM EXISTS (SELECT marketing.get_supplier_bank_json(null));
PERFORM EXISTS (SELECT marketing.get_supplier_category_json(null));
PERFORM EXISTS (SELECT marketing.get_supplier_contact_json(null));
PERFORM EXISTS (SELECT marketing.get_supplier_json(null));
PERFORM EXISTS (SELECT marketing.get_supplier_pic_json(null));
PERFORM EXISTS (SELECT marketing.get_table_json(null));
PERFORM EXISTS (SELECT marketing.get_transportation_json(null));
PERFORM EXISTS (SELECT marketing.get_transportation_type_instance(null));
PERFORM EXISTS (SELECT marketing.get_transportation_type_json(null));
PERFORM EXISTS (SELECT marketing.get_turnover_target_nominal(null, null));
PERFORM EXISTS (SELECT marketing.get_valid_sales_expense(null, null));
PERFORM EXISTS (SELECT marketing.get_vendor_category(null));
PERFORM EXISTS (SELECT marketing.get_view_brands_json(null));
PERFORM EXISTS (SELECT marketing.get_view_business_partner_address_json(null));
PERFORM EXISTS (SELECT marketing.get_view_business_partner_bank_json(null));
PERFORM EXISTS (SELECT marketing.get_view_business_partner_contact_json(null));
PERFORM EXISTS (SELECT marketing.get_view_customer_category_json(null));
PERFORM EXISTS (SELECT marketing.get_view_customer_delivery_json(null));
PERFORM EXISTS (SELECT marketing.get_view_customer_json(null));
PERFORM EXISTS (SELECT marketing.get_view_default_settings_minimum_visiting_count_json(null));
PERFORM EXISTS (SELECT marketing.get_view_default_settings_selling_price_sales_json(null));
PERFORM EXISTS (SELECT marketing.get_view_delivery_order_allocation_detail_json(null));
PERFORM EXISTS (SELECT marketing.get_view_delivery_order_allocation_json(null));
PERFORM EXISTS (SELECT marketing.get_view_delivery_order_term_json(null));
PERFORM EXISTS (SELECT marketing.get_view_distribution_plan_json(null));
PERFORM EXISTS (SELECT marketing.get_view_distribution_plan_product_json(null));
PERFORM EXISTS (SELECT marketing.get_view_distribution_plan_sales_json(null));
PERFORM EXISTS (SELECT marketing.get_view_expedition_json(null));
PERFORM EXISTS (SELECT marketing.get_view_fixed_forecast_json(null));
PERFORM EXISTS (SELECT marketing.get_view_generate_tax_number_json(null));
PERFORM EXISTS (SELECT marketing.get_view_master_level_json(null));
PERFORM EXISTS (SELECT marketing.get_view_master_platform_json(null));
PERFORM EXISTS (SELECT marketing.get_view_master_route_json(null));
PERFORM EXISTS (SELECT marketing.get_view_member_category_json(null));
PERFORM EXISTS (SELECT marketing.get_view_member_discount_json(null));
PERFORM EXISTS (SELECT marketing.get_view_outlet_category_json(null));
PERFORM EXISTS (SELECT marketing.get_view_outlet_images_json(null));
PERFORM EXISTS (SELECT marketing.get_view_outlet_qrcode_batch_items_json(null));
PERFORM EXISTS (SELECT marketing.get_view_outlet_qrcode_batch_json(null));
PERFORM EXISTS (SELECT marketing.get_view_outlet_qrcodes_json(null));
PERFORM EXISTS (SELECT marketing.get_view_outlet_regional_exclusive_json(null));
PERFORM EXISTS (SELECT marketing.get_view_outlets_feedback_json(null));
PERFORM EXISTS (SELECT marketing.get_view_outlets_json(null));
PERFORM EXISTS (SELECT marketing.get_view_price_list_json(null));
PERFORM EXISTS (SELECT marketing.get_view_price_list_products_json(null));
PERFORM EXISTS (SELECT marketing.get_view_price_list_regions_json(null));
PERFORM EXISTS (SELECT marketing.get_view_product_taxes_json(null));
PERFORM EXISTS (SELECT marketing.get_view_promo_free_item_benefit_json(null));
PERFORM EXISTS (SELECT marketing.get_view_promo_json(null));
PERFORM EXISTS (SELECT marketing.get_view_promo_member_json(null));
PERFORM EXISTS (SELECT marketing.get_view_promo_requirement_json(null));
PERFORM EXISTS (SELECT marketing.get_view_regionals_json(null));
PERFORM EXISTS (SELECT marketing.get_view_sales_forecast_detail_json(null));
PERFORM EXISTS (SELECT marketing.get_view_sales_forecast_json(null));
PERFORM EXISTS (SELECT marketing.get_view_sales_products_json(null));
PERFORM EXISTS (SELECT marketing.get_view_sales_salary_default_json(null));
PERFORM EXISTS (SELECT marketing.get_view_selling_price_categori_json(null));
PERFORM EXISTS (SELECT marketing.get_view_selling_price_category_details_json(null));
PERFORM EXISTS (SELECT marketing.get_view_selling_price_category_json(null));
PERFORM EXISTS (SELECT marketing.get_view_selling_price_category_profit_json(null));
PERFORM EXISTS (SELECT marketing.get_view_selling_price_detail_json(null));
PERFORM EXISTS (SELECT marketing.get_view_selling_price_discount_items_json(null));
PERFORM EXISTS (SELECT marketing.get_view_selling_price_items_json(null));
PERFORM EXISTS (SELECT marketing.get_view_selling_price_json(null));
PERFORM EXISTS (SELECT marketing.get_view_selling_price_product_items_json(null));
PERFORM EXISTS (SELECT marketing.get_view_selling_price_tax_items_json(null));
PERFORM EXISTS (SELECT marketing.get_view_selling_price_tax_json(null));
PERFORM EXISTS (SELECT marketing.get_view_shipping_order_detail_json(null));
PERFORM EXISTS (SELECT marketing.get_view_shipping_order_json(null));
PERFORM EXISTS (SELECT marketing.get_view_supplier_address_json(null));
PERFORM EXISTS (SELECT marketing.get_view_supplier_bank_json(null));
PERFORM EXISTS (SELECT marketing.get_view_supplier_category_json(null));
PERFORM EXISTS (SELECT marketing.get_view_supplier_contact_json(null));
PERFORM EXISTS (SELECT marketing.get_view_supplier_json(null));
PERFORM EXISTS (SELECT marketing.get_view_supplier_pic_json(null));
PERFORM EXISTS (SELECT marketing.get_view_table_json(null));
PERFORM EXISTS (SELECT marketing.get_view_transportation_json(null));
PERFORM EXISTS (SELECT marketing.get_view_transportation_type_json(null));
PERFORM EXISTS (SELECT marketing.get_view_visiting_schedule_details_json(null));
PERFORM EXISTS (SELECT marketing.get_view_visiting_schedule_json(null));
PERFORM EXISTS (SELECT marketing.get_visiting_schedule_details_json(null));
PERFORM EXISTS (SELECT marketing.get_visiting_schedule_json(null));
PERFORM EXISTS (SELECT marketing.insert_delivery_order(null, null, null));
PERFORM EXISTS (SELECT marketing.insert_detail_do_for_edit(null, null));
PERFORM EXISTS (SELECT marketing.insert_distribution_plan(null, CURRENT_DATE, null, FALSE));
PERFORM EXISTS (SELECT marketing.insert_distribution_plan_product(null, null));
PERFORM EXISTS (SELECT marketing.insert_distribution_plan_sales(null, null));
PERFORM EXISTS (SELECT marketing.insert_edit_delivery_order(null));
PERFORM EXISTS (SELECT marketing.insert_edit_good_replacement_receive(null));
PERFORM EXISTS (SELECT marketing.insert_edit_sales_return_receive(null));
PERFORM EXISTS (SELECT marketing.insert_edit_sales_return_request(null));
PERFORM EXISTS (SELECT marketing.insert_edit_shipping_order(null));
PERFORM EXISTS (SELECT marketing.insert_expedition(null, null, null, null, null));
PERFORM EXISTS (SELECT marketing.insert_from_sa_to_sales_refund(null, null));
PERFORM EXISTS (SELECT marketing.insert_incentive_indicator(null, 0.0, 0));
PERFORM EXISTS (SELECT marketing.insert_incentive_matrix_detail(null, 0.0, null, null, null));
PERFORM EXISTS (SELECT marketing.insert_incentive_matrix_detail(null, 0.0, null, null));
PERFORM EXISTS (SELECT marketing.insert_new_id_delivery_order(null));
PERFORM EXISTS (SELECT marketing.insert_new_id_delivery_order_new(null));
PERFORM EXISTS (SELECT marketing.insert_new_id_sales_order(null));
PERFORM EXISTS (SELECT marketing.insert_new_id_sales_order_new(null));
PERFORM EXISTS (SELECT marketing.insert_new_id_sales_order_new1(null, null));
PERFORM EXISTS (SELECT marketing.insert_new_id_sales_order_new2(null, null));
PERFORM EXISTS (SELECT marketing.insert_product_sales_return_request(null, null, null));
PERFORM EXISTS (SELECT marketing.insert_promo_member(null, FALSE, null));
PERFORM EXISTS (SELECT marketing.insert_promo_products(null, null, FALSE, FALSE));
PERFORM EXISTS (SELECT marketing.insert_sales_advance_edit_detail(null, null));
PERFORM EXISTS (SELECT marketing.insert_sales_forecast_detail(null, null));
PERFORM EXISTS (SELECT marketing.insert_selling_price_items_draft(null, null, 0.0, 0, 0));
PERFORM EXISTS (SELECT marketing.insert_shipping_order_from_do(null, null));
PERFORM EXISTS (SELECT marketing.insert_so_detail_to_sa_detail(null, null));
PERFORM EXISTS (SELECT marketing.insert_so_to_do(null, null));
PERFORM EXISTS (SELECT marketing.insert_transportation(null, null, null, null, null, null));
PERFORM EXISTS (SELECT marketing.list_ar_invoice(null, null));
PERFORM EXISTS (SELECT marketing.list_archive_supplier_category(null));
PERFORM EXISTS (SELECT marketing.list_brands(null));
PERFORM EXISTS (SELECT marketing.list_business_partner_archive(null, null));
PERFORM EXISTS (SELECT marketing.list_business_partner_category(null, 0, FALSE));
PERFORM EXISTS (SELECT marketing.list_calculate_sales_expense(null, null, FALSE, null));
PERFORM EXISTS (SELECT marketing.list_calculate_sales_expense_detail(null, null, FALSE, null));
PERFORM EXISTS (SELECT marketing.list_certain_product_detail(null));
PERFORM EXISTS (SELECT marketing.list_certain_product_detail_new());
PERFORM EXISTS (SELECT marketing.list_certain_product_parent(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT marketing.list_customer(null, null));
PERFORM EXISTS (SELECT marketing.list_customer_archive(null));
PERFORM EXISTS (SELECT marketing.list_customer_category(null, FALSE));
PERFORM EXISTS (SELECT marketing.list_customer_category_archive(null));
PERFORM EXISTS (SELECT marketing.list_customer_for_shipping_order());
PERFORM EXISTS (SELECT marketing.list_customer_for_slu_do());
PERFORM EXISTS (SELECT marketing.list_customer_internal(null, FALSE));
PERFORM EXISTS (SELECT marketing.list_customer_online(null, FALSE, null));
PERFORM EXISTS (SELECT marketing.list_customer_online_archive(null));
PERFORM EXISTS (SELECT marketing.list_customer_sales(null, FALSE, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT marketing.list_delivery_allocation_detail(null));
PERFORM EXISTS (SELECT marketing.list_delivery_order_allocation(CURRENT_DATE, CURRENT_DATE, FALSE, FALSE, null, null, FALSE, null, null));
PERFORM EXISTS (SELECT marketing.list_delivery_order_allocation(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT marketing.list_delivery_order_allocation_new(CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT marketing.list_delivery_order_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT marketing.list_delivery_order_report_test(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, null, FALSE, 0, null));
PERFORM EXISTS (SELECT marketing.list_distribution_plan(null));
PERFORM EXISTS (SELECT marketing.list_do(null, null));
PERFORM EXISTS (SELECT marketing.list_do_detail(null, null, FALSE, null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, 0));
PERFORM EXISTS (SELECT marketing.list_do_parent(null, FALSE, null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, 0));
PERFORM EXISTS (SELECT marketing.list_expedition_instance(null, null));
PERFORM EXISTS (SELECT marketing.list_generate_tax_number(CURRENT_DATE, CURRENT_DATE, null, FALSE));
PERFORM EXISTS (SELECT marketing.list_incentive_matrix(null, null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT marketing.list_incentive_matrix_detail(null));
PERFORM EXISTS (SELECT marketing.list_incentive_matrix_detail(null, null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT marketing.list_incentive_matrix_level(null));
PERFORM EXISTS (SELECT marketing.list_incentive_matrix_level(null, null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT marketing.list_level_shown(null));
PERFORM EXISTS (SELECT marketing.list_master_level(null, FALSE));
PERFORM EXISTS (SELECT marketing.list_master_level_archive(null));
PERFORM EXISTS (SELECT marketing.list_master_platform(null, FALSE));
PERFORM EXISTS (SELECT marketing.list_master_platform_archive(null));
PERFORM EXISTS (SELECT marketing.list_master_route(null, FALSE));
PERFORM EXISTS (SELECT marketing.list_master_route_archive(null));
PERFORM EXISTS (SELECT marketing.list_of_customer_online_list(null));
PERFORM EXISTS (SELECT marketing.list_of_customer_online_list());
PERFORM EXISTS (SELECT marketing.list_of_master_platform(null));
PERFORM EXISTS (SELECT marketing.list_of_sales_return_request_list(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT marketing.list_of_supplier_category(null));
PERFORM EXISTS (SELECT marketing.list_outlets(null));
PERFORM EXISTS (SELECT marketing.list_pareto_outlet(null, FALSE, CURRENT_DATE, CURRENT_DATE, null, FALSE));
PERFORM EXISTS (SELECT marketing.list_period());
PERFORM EXISTS (SELECT marketing.list_promo_free_item_benefit(null));
PERFORM EXISTS (SELECT marketing.list_promo_requirement(null));
PERFORM EXISTS (SELECT marketing.list_sa_for_refund(FALSE, CURRENT_DATE, CURRENT_DATE, null, null));
PERFORM EXISTS (SELECT marketing.list_sales_advance_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT marketing.list_sales_advance_detail_for_edit(null));
PERFORM EXISTS (SELECT marketing.list_sales_advance_detail_new(null));
PERFORM EXISTS (SELECT marketing.list_sales_forecast(CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT marketing.list_sales_forecast_detail(null));
PERFORM EXISTS (SELECT marketing.list_sales_forecast_detail_report(null, null, FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT marketing.list_sales_forecast_detail_report(null));
PERFORM EXISTS (SELECT marketing.list_sales_forecast_list(null, CURRENT_DATE, CURRENT_DATE, FALSE, FALSE, null, null));
PERFORM EXISTS (SELECT marketing.list_sales_forecast_list_detail(null));
PERFORM EXISTS (SELECT marketing.list_sales_forecast_report(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT marketing.list_sales_return_receive(null, null));
PERFORM EXISTS (SELECT marketing.list_sales_return_receive_detail(null));
PERFORM EXISTS (SELECT marketing.list_sales_return_receive_detail1(null));
PERFORM EXISTS (SELECT marketing.list_sales_return_receive_edit(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT marketing.list_sales_return_receive_list(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT marketing.list_sales_return_received(null));
PERFORM EXISTS (SELECT marketing.list_sales_return_received_report_detail(null, null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT marketing.list_sales_return_received_report_parent(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT marketing.list_sales_return_request(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT marketing.list_sales_return_request_detail(null, null));
PERFORM EXISTS (SELECT marketing.list_sales_return_request_detail_edit(null, null));
PERFORM EXISTS (SELECT marketing.list_sales_return_request_detail_report(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT marketing.list_sales_return_request_list_detail(null, null));
PERFORM EXISTS (SELECT marketing.list_sales_return_request_list_edit(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT marketing.list_sales_return_request_report(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT marketing.list_selling_price_all_products(null));
PERFORM EXISTS (SELECT marketing.list_selling_price_child(null, null));
PERFORM EXISTS (SELECT marketing.list_selling_price_parent(null, null));
PERFORM EXISTS (SELECT marketing.list_selling_price_products(null, null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT marketing.list_shipping_order(CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT marketing.list_shipping_order_detail(null));
PERFORM EXISTS (SELECT marketing.list_shipping_order_detail_edit(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null, null));
PERFORM EXISTS (SELECT marketing.list_shipping_order_edit_parent(FALSE, CURRENT_DATE, CURRENT_DATE, null, FALSE, null, null));
PERFORM EXISTS (SELECT marketing.list_shipping_order_list_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null, null));
PERFORM EXISTS (SELECT marketing.list_shipping_order_list_parent(FALSE, CURRENT_DATE, CURRENT_DATE, null, FALSE, null, null));
PERFORM EXISTS (SELECT marketing.list_shipping_order_parent_edit(FALSE, CURRENT_DATE, CURRENT_DATE, null, FALSE, null, null));
PERFORM EXISTS (SELECT marketing.list_shipping_order_report(CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT marketing.list_shipping_order_report_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE, null, null));
PERFORM EXISTS (SELECT marketing.list_shipping_order_report_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT marketing.list_shipping_order_report_parent(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT marketing.list_so_sales_advance(FALSE, CURRENT_DATE, CURRENT_DATE, null, null));
PERFORM EXISTS (SELECT marketing.list_target_calculation(null, null, FALSE, null));
PERFORM EXISTS (SELECT marketing.list_transportation_instance(null, null));
PERFORM EXISTS (SELECT marketing.list_turnover_target_level_by_parent(null));
PERFORM EXISTS (SELECT marketing.list_turnover_target_product_by_level(null));
PERFORM EXISTS (SELECT marketing.list_warehouse_do_slu_list());
PERFORM EXISTS (SELECT marketing.list_warehouse_for_shipping_order());
PERFORM EXISTS (SELECT marketing.lookup_customer(null, null));
PERFORM EXISTS (SELECT marketing.lookup_customer());
PERFORM EXISTS (SELECT marketing.lookup_outlet(null, null));
PERFORM EXISTS (SELECT marketing.lookup_warehouse());
PERFORM EXISTS (SELECT marketing.online_sales_report_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT marketing.online_sales_report_summary(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT marketing.open_list_so_sales_advance(FALSE, CURRENT_DATE, CURRENT_DATE, null, null));
PERFORM EXISTS (SELECT marketing.price_list_report(null));
PERFORM EXISTS (SELECT marketing.price_list_report_approved(null));
PERFORM EXISTS (SELECT marketing.price_list_report_detail(null, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT marketing.price_list_report_detail_approved(null));
PERFORM EXISTS (SELECT marketing.price_list_report_detail_level(null, null, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT marketing.price_list_report_detail_level_approved(null));
PERFORM EXISTS (SELECT marketing.print_online_sales_report_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT marketing.print_online_sales_report_summary(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT marketing.print_out_list_turnover_target());
PERFORM EXISTS (SELECT marketing.print_out_sa_refund(null));
PERFORM EXISTS (SELECT marketing.printout_incentive_matrix(null, null));
PERFORM EXISTS (SELECT marketing.printout_incentive_matrix_detail(null));
PERFORM EXISTS (SELECT marketing.qc_update_stock(null, null));
PERFORM EXISTS (SELECT marketing.refresh_delivery_order_detail(null, null));
PERFORM EXISTS (SELECT marketing.refresh_delivery_order_edit_detail(null, null));
PERFORM EXISTS (SELECT marketing.remove_distribution_plan(null));
PERFORM EXISTS (SELECT marketing.remove_new_promo(null));
PERFORM EXISTS (SELECT marketing.report_calculate_sales_expense(null));
PERFORM EXISTS (SELECT marketing.report_calculate_sales_expense_detail());
PERFORM EXISTS (SELECT marketing.report_certain_product_detail());
PERFORM EXISTS (SELECT marketing.report_certain_product_parent(null, FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT marketing.report_delivery_allocation_detail(null));
PERFORM EXISTS (SELECT marketing.report_delivery_allocation_detail_for_list());
PERFORM EXISTS (SELECT marketing.report_delivery_allocation_detail_reporting(null));
PERFORM EXISTS (SELECT marketing.report_delivery_order_allocation(null));
PERFORM EXISTS (SELECT marketing.report_delivery_order_allocation_for_list(null));
PERFORM EXISTS (SELECT marketing.report_delivery_order_allocation_new(null));
PERFORM EXISTS (SELECT marketing.report_delivery_order_list(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, null, FALSE, 0, null));
PERFORM EXISTS (SELECT marketing.report_incentive_matrix(null, null, null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT marketing.report_incentive_matrix_detail(null));
PERFORM EXISTS (SELECT marketing.report_incentive_matrix_level(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT marketing.report_list_certain_product_detail());
PERFORM EXISTS (SELECT marketing.report_list_certain_product_parent(null, FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT marketing.report_list_target_calculation_level(null));
PERFORM EXISTS (SELECT marketing.report_list_turnover_target());
PERFORM EXISTS (SELECT marketing.report_pareto_outlet(null));
PERFORM EXISTS (SELECT marketing.report_sales_forecast(null));
PERFORM EXISTS (SELECT marketing.report_sales_forecast_detail(null, null));
PERFORM EXISTS (SELECT marketing.report_sales_forecast_detail(null));
PERFORM EXISTS (SELECT marketing.report_sales_forecast_list_detail(null));
PERFORM EXISTS (SELECT marketing.report_sales_forecast_list_parent(null));
PERFORM EXISTS (SELECT marketing.report_sales_return_receive_list_parent(null));
PERFORM EXISTS (SELECT marketing.report_sales_return_received_detail());
PERFORM EXISTS (SELECT marketing.report_sales_return_received_list_parent(null));
PERFORM EXISTS (SELECT marketing.report_sales_return_received_parent(null));
PERFORM EXISTS (SELECT marketing.report_sales_return_request(null));
PERFORM EXISTS (SELECT marketing.report_sales_return_request_detail(null));
PERFORM EXISTS (SELECT marketing.report_sales_return_request_list(null));
PERFORM EXISTS (SELECT marketing.report_sales_return_request_list_detail());
PERFORM EXISTS (SELECT marketing.report_shipping_order(null));
PERFORM EXISTS (SELECT marketing.report_shipping_order_detail(null));
PERFORM EXISTS (SELECT marketing.report_shipping_order_list_detail_generate());
PERFORM EXISTS (SELECT marketing.report_shipping_order_list_generate(null));
PERFORM EXISTS (SELECT marketing.report_shipping_order_parent(null, null));
PERFORM EXISTS (SELECT marketing.report_shipping_order_report_detail(null));
PERFORM EXISTS (SELECT marketing.report_shipping_order_report_detail(null, null, null));
PERFORM EXISTS (SELECT marketing.report_target_calculation(null, null, FALSE, null));
PERFORM EXISTS (SELECT marketing.sales_advance_edit_update_parent_data(null, null));
PERFORM EXISTS (SELECT marketing.sales_advance_edit_update_parent_old_data(null, null));
PERFORM EXISTS (SELECT marketing.sales_advance_history_detail(null, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT marketing.sales_advance_history_parent(CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT marketing.sales_advance_refund_list(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null, null));
PERFORM EXISTS (SELECT marketing.sales_advance_refund_list_print_out(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT marketing.sales_order_validate_qty_do(null));
PERFORM EXISTS (SELECT marketing.sales_order_validate_qty_do_edit(null));
PERFORM EXISTS (SELECT marketing.sales_order_validate_qty_do_edit(null, null));
PERFORM EXISTS (SELECT marketing.sales_return_request_report_detail(null));
PERFORM EXISTS (SELECT marketing.sales_return_request_report_parent(null));
PERFORM EXISTS (SELECT marketing.sales_return_update_stock(null, null, null));
PERFORM EXISTS (SELECT marketing.save_incentive_detail(null, 0, 0.0, 0.0, 0.0, 0.0, null));
PERFORM EXISTS (SELECT marketing.set_copy_calculate_sales_expense(null, null));
PERFORM EXISTS (SELECT marketing.set_copy_target_calculation(null, null));
PERFORM EXISTS (SELECT marketing.set_incentive_detail_level_nominal(null, 0.0));
PERFORM EXISTS (SELECT marketing.set_new_business_partner_address_suplier(null, null, null, null, null, null));
PERFORM EXISTS (SELECT marketing.set_new_business_partner_bank_suplier(null, null, null, null, null, null));
PERFORM EXISTS (SELECT marketing.set_new_business_partner_category(null, 0, null, FALSE, null));
PERFORM EXISTS (SELECT marketing.set_new_business_partner_contact_person(null, null, null, null, null, null));
PERFORM EXISTS (SELECT marketing.set_new_business_partner_suplier(FALSE, null, null, null, null, null, null, FALSE, null, null, null, null, FALSE));
PERFORM EXISTS (SELECT marketing.set_new_certain_product(null, CURRENT_DATE, null, CURRENT_DATE, null, null));
--PERFORM EXISTS (SELECT marketing.set_new_customer(''::varchar, 'PRINCIPAL'::varchar, ''::varchar, TRUE, ''::varchar, ''::varchar, ''::varchar, ''::varchar, null));
--PERFORM EXISTS (SELECT marketing.set_new_customer(''::varchar, 'PRINCIPAL'::varchar, ''::varchar, TRUE, ''::varchar, ''::varchar, ''::varchar, ''::varchar, ''::varchar, ''::varchar, ''::varchar));
--PERFORM EXISTS (SELECT marketing.set_new_customer(''::varchar, 'PRINCIPAL'::varchar, ''::varchar, TRUE, ''::varchar, ''::varchar, ''::varchar, ''::varchar, ''::varchar, ''::varchar, ''::varchar, ''::varchar));
PERFORM EXISTS (SELECT marketing.set_new_customer_categories(null, null, null, FALSE, FALSE, 0.0, 0.0, 0.0, 0.0, null));
PERFORM EXISTS (SELECT marketing.set_new_customer_category(null, null, null, FALSE, null, FALSE));
PERFORM EXISTS (SELECT marketing.set_new_customer_internal(null, null, null, null, null, null, null, 0, null, null, null, null, null, null, null, FALSE, null, null, null, null, null));
PERFORM EXISTS (SELECT marketing.set_new_customer_online(null, null, null, null, null, null, null, null, null, null, FALSE, null, null, null, null, null));
PERFORM EXISTS (SELECT marketing.set_new_item_certain_product(null, null));
PERFORM EXISTS (SELECT marketing.set_new_master_level(null, null, null, FALSE, null));
PERFORM EXISTS (SELECT marketing.set_new_master_platform(null, null, null, FALSE, null));
PERFORM EXISTS (SELECT marketing.set_new_master_route(null, null, FALSE, null));
--PERFORM EXISTS (SELECT marketing.set_new_promo(null, null, null, now(), now(), null, CURRENT_TIME, FALSE, null, FALSE, 0, 0.0, 0.0, 0.0, FALSE));
--PERFORM EXISTS (SELECT marketing.set_new_promo(null, null, null, now(), now(), CURRENT_TIME, CURRENT_TIME, FALSE, null, FALSE, 0, 0.0, 0.0));
PERFORM EXISTS (SELECT marketing.set_new_sales_advance(null, CURRENT_DATE, null, null, CURRENT_DATE, null, null, null, null, 0.0, null, null, null, null, null, 0.0, 0.0, null, null, null));
PERFORM EXISTS (SELECT marketing.set_new_sales_advance_edit(null, CURRENT_DATE, null, null, CURRENT_DATE, null, null, null, null, 0.0, null, null, null, null, null, 0.0, 0.0, null, null));
PERFORM EXISTS (SELECT marketing.set_new_sales_advance_non_so(null, CURRENT_DATE, CURRENT_DATE, null, null, 0.0, null, null, null, null, null, null, null, null));
PERFORM EXISTS (SELECT marketing.set_new_sales_advance_refund_data(CURRENT_DATE, null, null, null, CURRENT_DATE, null, null, CURRENT_DATE, null, null, null, null, 0.0, 0.0, null, null, null, null, null));
PERFORM EXISTS (SELECT marketing.set_new_sales_return_receive(null, CURRENT_DATE, null, null, null, null, 0.0, null, null, null));
PERFORM EXISTS (SELECT marketing.set_new_update_customer_delivery(null, null));
PERFORM EXISTS (SELECT marketing.set_new_update_customer_delivery_new(null, null));
PERFORM EXISTS (SELECT marketing.set_new_update_delivery_order_allocation(null, CURRENT_DATE, null, null, null, null, null, null, null, null, CURRENT_DATE, null, null));
PERFORM EXISTS (SELECT marketing.set_new_update_delivery_order_allocation_edit(null, CURRENT_DATE, null, null, null, null, null, null, null, null, CURRENT_DATE, null, null));
PERFORM EXISTS (SELECT marketing.set_new_update_delivery_order_allocation_new(null, CURRENT_DATE, null, null, null, null, null, null, null, null, null, null));
PERFORM EXISTS (SELECT marketing.set_new_update_generate_tax_number(null, CURRENT_DATE, null, null, null, null, null, null));
PERFORM EXISTS (SELECT marketing.set_new_update_parent_delivery_order_allocation(null, CURRENT_DATE, null, null, null, null, null, null, null, null, CURRENT_DATE, null, null));
PERFORM EXISTS (SELECT marketing.set_new_update_promo(null));
PERFORM EXISTS (SELECT marketing.set_new_update_sales_forecast(null, CURRENT_DATE, null, null, null, null, null, null));
PERFORM EXISTS (SELECT marketing.set_new_update_sales_return_request(null, CURRENT_DATE, null, null, null, null));
PERFORM EXISTS (SELECT marketing.set_new_update_selling_price(null, CURRENT_DATE, null, null, null, FALSE, null));
PERFORM EXISTS (SELECT marketing.set_new_update_shipping_order(null, CURRENT_DATE, null, null, null, null, null, null, null, null, null, 0.0, null, null, null, null, CURRENT_DATE, null, null, null, null, null));
PERFORM EXISTS (SELECT marketing.set_sales_forecast_detail(null, null, null));
PERFORM EXISTS (SELECT marketing.set_sales_products(null, null));
PERFORM EXISTS (SELECT marketing.set_sales_ret_receive_detail(null, null));
PERFORM EXISTS (SELECT marketing.set_shipping_order_detail(null, null));
PERFORM EXISTS (SELECT marketing.set_turnover_target_on_target_calculation(null, null, null, null, 0.0, null));
PERFORM EXISTS (SELECT marketing.set_update_calculate_sales_expense(null, CURRENT_DATE, null, 0.0, null, null, null));
PERFORM EXISTS (SELECT marketing.set_update_calculate_sales_expense(null, CURRENT_DATE, null, 0.0, null, null));
PERFORM EXISTS (SELECT marketing.set_update_incentive_matrix_detail(CURRENT_DATE, null, 0.0, null, null, null, null, null));
PERFORM EXISTS (SELECT marketing.set_update_incentive_matrix_detail(CURRENT_DATE, null, 0.0, null, null, null));
PERFORM EXISTS (SELECT marketing.set_update_pareto_outlet(null, CURRENT_DATE, null, null, null, CURRENT_DATE, CURRENT_DATE, 0.0, 0.0, null, null, null));
PERFORM EXISTS (SELECT marketing.set_update_target_calculation(null, CURRENT_DATE, null, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, null, null, 0.0, 0.0, null));
PERFORM EXISTS (SELECT marketing.set_update_target_calculation(null, CURRENT_DATE, null, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, null, null));
PERFORM EXISTS (SELECT marketing.shipping_order_report_detail(null));
PERFORM EXISTS (SELECT marketing.target_calculation_turnover_new(null, null));
PERFORM EXISTS (SELECT marketing.target_turnover_product_new(null));
PERFORM EXISTS (SELECT marketing.test_stock_updater_replacement(null, null, null));
PERFORM EXISTS (SELECT marketing.unset_turnover_target_on_target_calculation(null));
PERFORM EXISTS (SELECT marketing.update_old_all_promo(null));
PERFORM EXISTS (SELECT marketing.update_old_business_partner_category(null));
PERFORM EXISTS (SELECT marketing.update_old_business_partner_suplier(null));
PERFORM EXISTS (SELECT marketing.update_old_customer(null));
PERFORM EXISTS (SELECT marketing.update_old_customer_category(null));
PERFORM EXISTS (SELECT marketing.update_old_customer_delivery(null, null));
PERFORM EXISTS (SELECT marketing.update_old_customer_online(null));
PERFORM EXISTS (SELECT marketing.update_old_master_platform(null));
PERFORM EXISTS (SELECT marketing.update_old_master_route(null));
PERFORM EXISTS (SELECT marketing.update_outlet_terminated(null));
PERFORM EXISTS (SELECT marketing.update_qty_stock_for_validate(null));
PERFORM EXISTS (SELECT marketing.update_qty_stock_for_validate_edit(null));
PERFORM EXISTS (SELECT marketing.update_sa_amount_remain_for_refund(null, null));
PERFORM EXISTS (SELECT marketing.update_selling_price_items_hpp(null));
PERFORM EXISTS (SELECT marketing.update_so_qty_ordered_for_edit_do(null));
PERFORM EXISTS (SELECT marketing.update_tax_number_from_ar(null, null));
PERFORM EXISTS (SELECT marketing.update_tax_number_from_ar_cancelled(null, null));
PERFORM EXISTS (SELECT marketing.validasi_customer_online_name_archive(null));
PERFORM EXISTS (SELECT marketing.validate_business_partner_category_name(null));
PERFORM EXISTS (SELECT marketing.validate_business_partner_category_name_archived(null));
PERFORM EXISTS (SELECT marketing.validate_business_partner_code(null));
PERFORM EXISTS (SELECT marketing.validate_business_partner_code_archive(null));
PERFORM EXISTS (SELECT marketing.validate_business_partner_code_archive_new(null));
PERFORM EXISTS (SELECT marketing.validate_business_partner_code_edit(null, null));
PERFORM EXISTS (SELECT marketing.validate_business_partner_code_edit_archive(null, null));
PERFORM EXISTS (SELECT marketing.validate_business_partner_code_new(null));
PERFORM EXISTS (SELECT marketing.validate_business_partner_name(null));
PERFORM EXISTS (SELECT marketing.validate_business_partner_name_archive(null));
PERFORM EXISTS (SELECT marketing.validate_business_partner_npwp(null));
PERFORM EXISTS (SELECT marketing.validate_business_partner_npwp_archive(null));
PERFORM EXISTS (SELECT marketing.validate_currency_code_iso(null, null));
PERFORM EXISTS (SELECT marketing.validate_cust_internal_name_edit(null, null));
PERFORM EXISTS (SELECT marketing.validate_customer_category_archive_edit(null, null));
PERFORM EXISTS (SELECT marketing.validate_customer_category_code(null));
PERFORM EXISTS (SELECT marketing.validate_customer_category_code_archive(null));
PERFORM EXISTS (SELECT marketing.validate_customer_category_code_edit(null, null));
PERFORM EXISTS (SELECT marketing.validate_customer_category_name(null));
PERFORM EXISTS (SELECT marketing.validate_customer_category_name_archive(null));
PERFORM EXISTS (SELECT marketing.validate_customer_category_name_edit(null, null));
PERFORM EXISTS (SELECT marketing.validate_customer_code(null));
PERFORM EXISTS (SELECT marketing.validate_customer_code_archive(null));
PERFORM EXISTS (SELECT marketing.validate_customer_code_edit(null));
PERFORM EXISTS (SELECT marketing.validate_customer_name(null));
PERFORM EXISTS (SELECT marketing.validate_customer_name_archive(null));
PERFORM EXISTS (SELECT marketing.validate_customer_name_edit(null));
PERFORM EXISTS (SELECT marketing.validate_customer_online_edit(null, null));
PERFORM EXISTS (SELECT marketing.validate_master_platform_name(null));
PERFORM EXISTS (SELECT marketing.validate_master_platform_name_edit(null, null));
PERFORM EXISTS (SELECT marketing.validate_master_route_archived(null));
PERFORM EXISTS (SELECT marketing.validate_master_route_name(null));
PERFORM EXISTS (SELECT marketing.validate_master_route_name_edit(null, null));
PERFORM EXISTS (SELECT marketing.validate_member_category(null));
PERFORM EXISTS (SELECT marketing.validate_member_discount(null));
PERFORM EXISTS (SELECT marketing.validate_platform(null));
PERFORM EXISTS (SELECT marketing.validate_platform_archived(null));
PERFORM EXISTS (SELECT marketing.validate_platform_name_edit(null, null));
PERFORM EXISTS (SELECT marketing.validate_promo_in_use(null, null));
PERFORM EXISTS (SELECT marketing.validate_supplier(null, null));
PERFORM EXISTS (SELECT marketing.validate_supplier_archive(null, null));
PERFORM EXISTS (SELECT marketing.validate_supplier_archived(null, null));
PERFORM EXISTS (SELECT marketing.validate_supplier_cat_name(null));
PERFORM EXISTS (SELECT marketing.validate_supplier_cat_name_archive(null));
PERFORM EXISTS (SELECT marketing.validate_supplier_edit_code(null, null));
PERFORM EXISTS (SELECT marketing.validate_supplier_edit_name(null, null));
PERFORM EXISTS (SELECT marketing.validate_supplier_edit_npwp(null, null));
PERFORM EXISTS (SELECT marketing.validating_distribution_plan_products(null));
END;