BEGIN
PERFORM EXISTS (SELECT reports.get_barcode_and_label_detail_json(null));
PERFORM EXISTS (SELECT reports.get_barcode_and_label_json(null));
PERFORM EXISTS (SELECT reports.get_beginning_by_item(null, null, null, CURRENT_DATE));
PERFORM EXISTS (SELECT reports.get_beginning_convertion_material(null, null, CURRENT_DATE));
PERFORM EXISTS (SELECT reports.get_beginning_delivery_order(null, null, CURRENT_DATE));
PERFORM EXISTS (SELECT reports.get_beginning_inv_adj(null, null, CURRENT_DATE));
PERFORM EXISTS (SELECT reports.get_beginning_material_used(null, null, CURRENT_DATE));
PERFORM EXISTS (SELECT reports.get_beginning_material_used_return(null, null, CURRENT_DATE));
PERFORM EXISTS (SELECT reports.get_beginning_purchase(null, null, CURRENT_DATE));
PERFORM EXISTS (SELECT reports.get_beginning_purchase_return(null, null, CURRENT_DATE));
PERFORM EXISTS (SELECT reports.get_beginning_sales_return(null, null, CURRENT_DATE));
PERFORM EXISTS (SELECT reports.get_beginning_stock_taking(null, null, CURRENT_DATE));
PERFORM EXISTS (SELECT reports.get_current_convertion_material(null, null, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT reports.get_current_delivery_order(null, null, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT reports.get_current_inv_adj(null, null, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT reports.get_current_inv_transfer_in(null, null, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT reports.get_current_inv_transfer_out(null, null, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT reports.get_current_mat_return(null, null, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT reports.get_current_mat_used(null, null, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT reports.get_current_purchase_return(null, null, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT reports.get_current_purchasing(null, null, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT reports.get_current_sales_return(null, null, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT reports.get_current_stock_taking(null, null, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT reports.get_ending_by_item(null, null, null, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT reports.get_mutasi_in_by_item(null, null, null, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT reports.get_mutasi_out_by_item(null, null, null, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT reports.get_print_out_stock_movement_report(null, null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT reports.get_print_out_stock_movement_summary_report(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT reports.get_stock_movement_report(null, null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT reports.get_stock_movement_summary_report(null, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT reports.get_view_barcode_and_label_detail_json(null));
PERFORM EXISTS (SELECT reports.get_view_barcode_and_label_json(null));
PERFORM EXISTS (SELECT reports.insert_barcode_and_label_detail(null, null, null, null));
PERFORM EXISTS (SELECT reports.list_barcode_and_label_products(null, null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT reports.print_stock_movement_report_detail(null, null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT reports.print_stock_movement_summary_report(null, null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT reports.report_barcode_and_label(null));
END;