BEGIN
PERFORM EXISTS (SELECT accounting.cancel_credit_notes_to_edit(null, null));
PERFORM EXISTS (SELECT accounting.cancel_debit_notes_to_edit(null, null));
PERFORM EXISTS (SELECT accounting.check_account_and_cost_center_for_fixed_asset(null, 0.0, 0.0, null));
PERFORM EXISTS (SELECT accounting.check_account_and_cost_center_for_fixed_asset_disposal(null));
PERFORM EXISTS (SELECT accounting.check_account_and_cost_center_for_fixed_assets(null, 0.0, 0.0));
PERFORM EXISTS (SELECT accounting.check_account_and_cost_center_for_prepaid(null, 0.0, 0.0));
PERFORM EXISTS (SELECT accounting.check_unbalance_journal_schedule());
PERFORM EXISTS (SELECT accounting.completing_credit_notes_transaction(null, 0));
PERFORM EXISTS (SELECT accounting.completing_prepaid_transaction(null, 0));
PERFORM EXISTS (SELECT accounting.copy_credit_notes_to_edit(null));
PERFORM EXISTS (SELECT accounting.copy_debit_notes_to_edit(null));
PERFORM EXISTS (SELECT accounting.delete_journal(null, null));
PERFORM EXISTS (SELECT accounting.delete_preparation_account_detail(null));
PERFORM EXISTS (SELECT accounting.delete_transaction_edit('accounting.chart_of_account', '', '', 0, 0));
PERFORM EXISTS (SELECT accounting.fixed_asset_allocation_print_out(null));
PERFORM EXISTS (SELECT accounting.fixed_asset_detail_depreciation_print_out());
PERFORM EXISTS (SELECT accounting.fixed_asset_disposal_allocation_print_out(null));
PERFORM EXISTS (SELECT accounting.fixed_asset_disposal_detail_depreciation_print_out(null));
PERFORM EXISTS (SELECT accounting.fixed_asset_disposal_print_out(null));
PERFORM EXISTS (SELECT accounting.fixed_asset_print_out(null));
PERFORM EXISTS (SELECT accounting.general_journal_detail_report(null));
PERFORM EXISTS (SELECT accounting.general_journal_report(null));
PERFORM EXISTS (SELECT accounting.general_ledger_detail_report(CURRENT_DATE, 0, null, 0, CURRENT_DATE, null));
PERFORM EXISTS (SELECT accounting.general_ledger_parent_report(CURRENT_DATE, 0, 0, null, CURRENT_DATE, null, null));
PERFORM EXISTS (SELECT accounting.generate_fixed_asset_depreciation(null, CURRENT_DATE, 0, null, 0.0, 0, null));
PERFORM EXISTS (SELECT accounting.generate_fixed_asset_disposal_depreciation(null, CURRENT_DATE, 0, null, 0.0));
PERFORM EXISTS (SELECT accounting.generate_fixed_asset_journal());
PERFORM EXISTS (SELECT accounting.generate_prepaid_amotization(null, CURRENT_DATE, 0, null, 0.0));
PERFORM EXISTS (SELECT accounting.generate_prepaid_journal());
PERFORM EXISTS (SELECT accounting.generate_unbalance_do_journal(null));
PERFORM EXISTS (SELECT accounting.get_account(null));
PERFORM EXISTS (SELECT accounting.get_account_beginning(null));
PERFORM EXISTS (SELECT accounting.get_account_cash_flow(CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.get_account_code_position(null));
PERFORM EXISTS (SELECT accounting.get_account_for_conf(null));
PERFORM EXISTS (SELECT accounting.get_account_in_journal(null, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.get_account_income_statement(0, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.get_account_payable());
PERFORM EXISTS (SELECT accounting.get_account_transaction_amount(null, CURRENT_DATE, CURRENT_DATE, 0));
PERFORM EXISTS (SELECT accounting.get_account_transaction_amount_by_group(null, CURRENT_DATE, CURRENT_DATE, 0));
PERFORM EXISTS (SELECT accounting.get_account_transaction_amount_by_group_monthly(null, CURRENT_DATE, 0));
PERFORM EXISTS (SELECT accounting.get_account_type());
PERFORM EXISTS (SELECT accounting.get_account_type_json(null));
PERFORM EXISTS (SELECT accounting.get_account_types(null));
PERFORM EXISTS (SELECT accounting.get_accounts_(CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT accounting.get_accounts_balance(CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT accounting.get_ap_purchase_journal(null, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.get_ap_purchase_journal_beginning(null, CURRENT_DATE, null, null));
PERFORM EXISTS (SELECT accounting.get_ar_sales_journal(null, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.get_ar_sales_journal_beginning(null, CURRENT_DATE, null, null));
PERFORM EXISTS (SELECT accounting.get_ar_sales_journal_beginning_x(null, CURRENT_DATE, null, null, FALSE));
PERFORM EXISTS (SELECT accounting.get_asset_accounts(CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT accounting.get_asset_accounts_formatx(CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT accounting.get_assets(null, null));
PERFORM EXISTS (SELECT accounting.get_balance_sheet_comparison_detail(CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.get_balance_sheet_comparison_group(CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.get_balance_sheet_comparison_header(CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.get_balance_sheet_detail_per_month(0, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.get_balance_sheet_group_per_month(0, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.get_bank_cash());
PERFORM EXISTS (SELECT accounting.get_bank_cash_account(null));
PERFORM EXISTS (SELECT accounting.get_bank_cash_account_(null));
PERFORM EXISTS (SELECT accounting.get_bank_cash_account_json(null));
PERFORM EXISTS (SELECT accounting.get_bank_cash_code());
PERFORM EXISTS (SELECT accounting.get_bank_cash_code_json(null));
PERFORM EXISTS (SELECT accounting.get_bank_code());
PERFORM EXISTS (SELECT accounting.get_bank_code(null));
PERFORM EXISTS (SELECT accounting.get_bank_json(null));
PERFORM EXISTS (SELECT accounting.get_beginning_balance(null, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.get_category_bank_cash_account());
PERFORM EXISTS (SELECT accounting.get_chart_of_account_instance(null));
PERFORM EXISTS (SELECT accounting.get_chart_of_account_json(null));
PERFORM EXISTS (SELECT accounting.get_chart_of_account_x_json(null));
PERFORM EXISTS (SELECT accounting.get_child_of_cash_bank(null));
PERFORM EXISTS (SELECT accounting.get_child_of_coa(null));
PERFORM EXISTS (SELECT accounting.get_child_of_non_cash_bank(null));
PERFORM EXISTS (SELECT accounting.get_coa_bank(null));
PERFORM EXISTS (SELECT accounting.get_coa_bank());
PERFORM EXISTS (SELECT accounting.get_coa_level_1(null, null));
PERFORM EXISTS (SELECT accounting.get_coa_level_2(null, null));
PERFORM EXISTS (SELECT accounting.get_coa_parent_code(null));
PERFORM EXISTS (SELECT accounting.get_credit_notes_detail_json(null));
PERFORM EXISTS (SELECT accounting.get_credit_notes_journal_detail_json(null));
PERFORM EXISTS (SELECT accounting.get_credit_notes_json(null));
PERFORM EXISTS (SELECT accounting.get_credit_notes_report(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.get_credit_notes_report_summary(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT accounting.get_current_balance(null, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.get_current_level_coa(null));
PERFORM EXISTS (SELECT accounting.get_customer_deposit(CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT accounting.get_customer_deposit_beginning(null, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT accounting.get_customer_deposit_detail(null, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.get_customer_deposit_detail_beginning(null, CURRENT_DATE, null));
PERFORM EXISTS (SELECT accounting.get_data_new_journal(null, null));
PERFORM EXISTS (SELECT accounting.get_data_new_journal_detail(null, null));
PERFORM EXISTS (SELECT accounting.get_data_old_journal(null, null));
PERFORM EXISTS (SELECT accounting.get_debit_notes_detail_json(null));
PERFORM EXISTS (SELECT accounting.get_debit_notes_journal_detail_json(null));
PERFORM EXISTS (SELECT accounting.get_debit_notes_json(null));
PERFORM EXISTS (SELECT accounting.get_debit_notes_report(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.get_debit_notes_report_summary(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT accounting.get_depreciation_type());
PERFORM EXISTS (SELECT accounting.get_e_faktur_ar_list(CURRENT_DATE, CURRENT_DATE, FALSE));
PERFORM EXISTS (SELECT accounting.get_e_faktur_out(CURRENT_DATE, CURRENT_DATE, FALSE));
PERFORM EXISTS (SELECT accounting.get_e_faktur_tax_unpicked_list(CURRENT_DATE, CURRENT_DATE, FALSE));
PERFORM EXISTS (SELECT accounting.get_fixed_asset_allocation_json(null));
PERFORM EXISTS (SELECT accounting.get_fixed_asset_depreciation_json(null));
PERFORM EXISTS (SELECT accounting.get_fixed_asset_disposal_allocation_json(null));
PERFORM EXISTS (SELECT accounting.get_fixed_asset_disposal_depreciation_json(null));
PERFORM EXISTS (SELECT accounting.get_fixed_asset_disposal_json(null));
PERFORM EXISTS (SELECT accounting.get_fixed_asset_disposal_report(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.get_fixed_asset_json(null));
PERFORM EXISTS (SELECT accounting.get_fixed_asset_report(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.get_fixed_assets_depreciation_report(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.get_fixed_assets_disposal_report(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.get_general_journal_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, FALSE));
PERFORM EXISTS (SELECT accounting.get_gross_income_accounts(CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT accounting.get_gross_income_formatx(CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT accounting.get_group_account_by_report(null));
PERFORM EXISTS (SELECT accounting.get_group_account_cash_flow(CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.get_group_account_income_statement(null, CURRENT_DATE, CURRENT_DATE, 0));
PERFORM EXISTS (SELECT accounting.get_group_first_level_by_status(null, CURRENT_DATE, 0));
PERFORM EXISTS (SELECT accounting.get_group_first_level_by_status_monthly(null, CURRENT_DATE, 0));
PERFORM EXISTS (SELECT accounting.get_income_statement_amount_by_period(0, CURRENT_DATE, CURRENT_DATE, 0));
PERFORM EXISTS (SELECT accounting.get_journal_detail_json(null));
PERFORM EXISTS (SELECT accounting.get_journal_json(null));
PERFORM EXISTS (SELECT accounting.get_liability_accounts(CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT accounting.get_liability_accounts_formatx(CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT accounting.get_net_income_accounts(CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT accounting.get_net_income_formatx(CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT accounting.get_net_sales_accounts(CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT accounting.get_net_sales_accounts_formatx(CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT accounting.get_new_update_bank(null));
PERFORM EXISTS (SELECT accounting.get_new_update_bank_cash_account(null));
PERFORM EXISTS (SELECT accounting.get_new_update_coa(null));
PERFORM EXISTS (SELECT accounting.get_new_update_coa_top(null));
PERFORM EXISTS (SELECT accounting.get_parent_bank_cash(null));
PERFORM EXISTS (SELECT accounting.get_parent_chart_of_account(null));
PERFORM EXISTS (SELECT accounting.get_prepaid_amortization_json(null));
PERFORM EXISTS (SELECT accounting.get_prepaid_detail_json(null));
PERFORM EXISTS (SELECT accounting.get_prepaid_expenses_amortization_report(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.get_prepaid_json(null));
PERFORM EXISTS (SELECT accounting.get_prepaid_parent_data_for_list(null));
PERFORM EXISTS (SELECT accounting.get_preparation_property());
PERFORM EXISTS (SELECT accounting.get_preparation_property_detail_new(0));
PERFORM EXISTS (SELECT accounting.get_print_out_fixed_asset_disposal_report(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.get_print_out_fixed_asset_report(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.get_products_chart_of_account_json(null));
PERFORM EXISTS (SELECT accounting.get_report_balance_sheet_summary(CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.get_saldo(CURRENT_DATE, CURRENT_DATE, null, 0));
PERFORM EXISTS (SELECT accounting.get_summary_cash_flow(CURRENT_DATE, null));
PERFORM EXISTS (SELECT accounting.get_supplier_deposit(CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT accounting.get_supplier_deposit_beginning(null, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT accounting.get_supplier_deposit_current(null, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT accounting.get_supplier_deposit_detail(CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT accounting.get_supplier_deposit_detail_beginning(null, CURRENT_DATE, null));
PERFORM EXISTS (SELECT accounting.get_supplier_deposit_detail_current(null, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT accounting.get_top_level());
PERFORM EXISTS (SELECT accounting.get_total_all_income_statement(CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.get_transaction_status_journal());
PERFORM EXISTS (SELECT accounting.get_variant_hpp(CURRENT_DATE, 0));
PERFORM EXISTS (SELECT accounting.get_view_account_type_json(null));
PERFORM EXISTS (SELECT accounting.get_view_bank_cash_account_json(null));
PERFORM EXISTS (SELECT accounting.get_view_bank_cash_code_json(null));
PERFORM EXISTS (SELECT accounting.get_view_bank_json(null));
PERFORM EXISTS (SELECT accounting.get_view_chart_of_account_json(null));
PERFORM EXISTS (SELECT accounting.get_view_chart_of_account_x_json(null));
PERFORM EXISTS (SELECT accounting.get_view_products_chart_of_account_json(null));
PERFORM EXISTS (SELECT accounting.insert_ap_to_debit_notes(null, null));
PERFORM EXISTS (SELECT accounting.insert_ar_to_credit_notes(null, null, null));
PERFORM EXISTS (SELECT accounting.insert_crons('', '', 0, FALSE));
PERFORM EXISTS (SELECT accounting.insert_detail_old_journal_to_new(null, null));
PERFORM EXISTS (SELECT accounting.insert_edit_fixed_asset(null));
PERFORM EXISTS (SELECT accounting.insert_edit_fixed_asset_disposal(null));
PERFORM EXISTS (SELECT accounting.insert_edit_prepaid(null));
PERFORM EXISTS (SELECT accounting.insert_fixed_asset_to_disposal(null, null));
PERFORM EXISTS (SELECT accounting.insert_preparation_detail(null, null, null, null));
PERFORM EXISTS (SELECT accounting.insert_purchase_return_to_debit_notes(null, null));
PERFORM EXISTS (SELECT accounting.insert_sales_return_to_credit_notes(null, null, null));
PERFORM EXISTS (SELECT accounting.insert_to_journal_detail(null));
PERFORM EXISTS (SELECT accounting.insert_to_journal_detail1(null, null, 0, 0));
PERFORM EXISTS (SELECT accounting.insert_to_journal_parent(null));
PERFORM EXISTS (SELECT accounting.list_accounts(null));
PERFORM EXISTS (SELECT accounting.list_ap_ar_ledger(FALSE, null, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.list_ap_ar_ledger_sum(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT accounting.list_asset_for_list());
PERFORM EXISTS (SELECT accounting.list_bank(null, FALSE, null));
PERFORM EXISTS (SELECT accounting.list_bank_archive(null, null));
PERFORM EXISTS (SELECT accounting.list_bank_cash_account(null, FALSE));
PERFORM EXISTS (SELECT accounting.list_bank_cash_account_archive(null));
PERFORM EXISTS (SELECT accounting.list_bank_cash_account_code());
PERFORM EXISTS (SELECT accounting.list_chart_of_account(''));
PERFORM EXISTS (SELECT accounting.list_chart_of_account(null, FALSE, null));
PERFORM EXISTS (SELECT accounting.list_chart_of_account_archive(null, null));
PERFORM EXISTS (SELECT accounting.list_chart_of_account_code());
PERFORM EXISTS (SELECT accounting.list_credit_notes(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.list_credit_notes_list_detail(null));
--PERFORM EXISTS (SELECT accounting.list_credit_notes_list_detail_new(null));
PERFORM EXISTS (SELECT accounting.list_credit_notes_list_journal_detail(null));
PERFORM EXISTS (SELECT accounting.list_credit_notes_list_parent(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT accounting.list_debit_notes(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.list_debit_notes_detail_edit(null));
PERFORM EXISTS (SELECT accounting.list_debit_notes_edit(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.list_debit_notes_journal_detail_edit(null));
PERFORM EXISTS (SELECT accounting.list_debit_notes_list_detail(null));
PERFORM EXISTS (SELECT accounting.list_debit_notes_list_journal_detail(null));
PERFORM EXISTS (SELECT accounting.list_debit_notes_list_journal_detail_new(null));
PERFORM EXISTS (SELECT accounting.list_debit_notes_list_parent(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT accounting.list_detail_credit_notes_edit(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.list_fixed_asset(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.list_fixed_asset_allocation(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.list_fixed_asset_depreciation_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.list_fixed_asset_disposal_allocation(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.list_fixed_asset_disposal_depreciation(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.list_fixed_asset_disposal_edit(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.list_fixed_asset_disposal_list(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.list_fixed_asset_disposal_list_allocation(null));
PERFORM EXISTS (SELECT accounting.list_fixed_asset_disposal_list_depreciation(null));
PERFORM EXISTS (SELECT accounting.list_fixed_asset_disposal_list_detail(null));
PERFORM EXISTS (SELECT accounting.list_fixed_asset_edit(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.list_fixed_asset_list_allocation(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.list_fixed_asset_list_depreciation_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.list_fixed_asset_list_parent(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.list_fixed_asset_print_out(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.list_general_journal_list(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, FALSE));
PERFORM EXISTS (SELECT accounting.list_general_journal_list_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.list_journal(FALSE, CURRENT_DATE, CURRENT_DATE, 0, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT accounting.list_journal_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.list_journal_detail_credit_notes_edit(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.list_journal_general(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.list_journal_general_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.list_journal_general_edit(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.list_of_credit_notes_edit(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.list_of_general_ledger(CURRENT_DATE, 0, 0, null, CURRENT_DATE, null, null, FALSE));
PERFORM EXISTS (SELECT accounting.list_of_general_ledger_detail(CURRENT_DATE, 0, null, 0, CURRENT_DATE, null, null, null));
PERFORM EXISTS (SELECT accounting.list_prepaid(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.list_prepaid_account_for_list());
PERFORM EXISTS (SELECT accounting.list_prepaid_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.list_prepaid_detail_for_printout(null));
PERFORM EXISTS (SELECT accounting.list_prepaid_edit(FALSE, CURRENT_DATE, CURRENT_DATE, null, FALSE, null));
PERFORM EXISTS (SELECT accounting.list_prepaid_for_amortization_printout(null));
PERFORM EXISTS (SELECT accounting.list_prepaid_for_print_out(null));
PERFORM EXISTS (SELECT accounting.list_prepaid_list_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.list_prepaid_list_detail_for_printout(null));
PERFORM EXISTS (SELECT accounting.list_prepaid_list_for_amortization_printout(null));
PERFORM EXISTS (SELECT accounting.list_prepaid_list_for_print_out(null));
PERFORM EXISTS (SELECT accounting.list_prepaid_list_parent(FALSE, CURRENT_DATE, CURRENT_DATE, null, FALSE, null));
PERFORM EXISTS (SELECT accounting.list_preparation_account(null, null));
PERFORM EXISTS (SELECT accounting.list_preparation_account_detail(null, null));
PERFORM EXISTS (SELECT accounting.list_purchase_advance_ledger(CURRENT_DATE, CURRENT_DATE, null, FALSE, null));
PERFORM EXISTS (SELECT accounting.list_purchase_advance_ledger_sum(CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT accounting.list_sa_pa_ledger(FALSE, null, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.list_sa_pa_ledger_sum(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT accounting.list_sales_advance_ledger(CURRENT_DATE, CURRENT_DATE, null, FALSE, null));
PERFORM EXISTS (SELECT accounting.list_sales_advance_ledger_sum(CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT accounting.list_unbalance_journal(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.list_unbalance_journal_detail(null));
PERFORM EXISTS (SELECT accounting.list_unbalance_journal_detail_report());
PERFORM EXISTS (SELECT accounting.list_unbalance_journal_report(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.open_close_credit_notes(null, FALSE));
PERFORM EXISTS (SELECT accounting.open_close_debit_notes(null, FALSE));
PERFORM EXISTS (SELECT accounting.open_close_fixed_assets(null, FALSE));
PERFORM EXISTS (SELECT accounting.open_close_fixed_assets_disposal(null, FALSE));
PERFORM EXISTS (SELECT accounting.open_close_general_journal(null, FALSE));
PERFORM EXISTS (SELECT accounting.open_close_prepaid(null, FALSE));
PERFORM EXISTS (SELECT accounting.open_credit_notes(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.open_credit_notes_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.open_credit_notes_journal_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.open_debit_notes(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.open_debit_notes_detail(null));
PERFORM EXISTS (SELECT accounting.open_debit_notes_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.open_debit_notes_journal_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.open_debit_notes_journal_detail(null));
PERFORM EXISTS (SELECT accounting.open_fixed_asset(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.open_fixed_asset_allocation(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.open_fixed_asset_depreciation_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.open_fixed_asset_disposal(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.open_fixed_asset_disposal_allocation(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.open_fixed_asset_disposal_depreciation(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.open_journal_general(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.open_journal_general_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.open_prepaid(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.open_prepaid_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.open_prepaid_detail_amortization(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.prepaid_detail_amortization(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.prepaid_list_detail_amortization(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.print_credit_notes_report(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.print_debit_notes_report(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.print_fixed_asset_disposal_list(null));
PERFORM EXISTS (SELECT accounting.print_fixed_asset_disposal_list_allocation());
PERFORM EXISTS (SELECT accounting.print_fixed_asset_disposal_list_depreciation());
PERFORM EXISTS (SELECT accounting.print_fixed_assets_depreciation_report(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.print_fixed_assets_disposal_report(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.print_general_journal_list(null));
PERFORM EXISTS (SELECT accounting.print_general_journal_list_detail());
PERFORM EXISTS (SELECT accounting.print_general_journal_report(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.print_journal_detail(null));
PERFORM EXISTS (SELECT accounting.print_journal_detail());
PERFORM EXISTS (SELECT accounting.print_journal_list(0));
PERFORM EXISTS (SELECT accounting.print_journal_list(null));
PERFORM EXISTS (SELECT accounting.print_prepaid_expenses_amortization_report(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT accounting.report_income_statements_non_operational(CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT accounting.report_income_statements_other(CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT accounting.report_list_credit_notes_list_detail(null));
PERFORM EXISTS (SELECT accounting.report_list_credit_notes_list_journal_detail(null));
PERFORM EXISTS (SELECT accounting.report_list_credit_notes_list_parent(null));
PERFORM EXISTS (SELECT accounting.report_list_debit_notes_list_detail(null));
PERFORM EXISTS (SELECT accounting.report_list_debit_notes_list_journal_detail(null));
PERFORM EXISTS (SELECT accounting.report_list_debit_notes_list_parent(null));
PERFORM EXISTS (SELECT accounting.save_credit_notes_new_to_old(null, null, 0));
PERFORM EXISTS (SELECT accounting.save_debit_notes_new_to_old(null, null, 0));
PERFORM EXISTS (SELECT accounting.save_fixed_assets(null, null, 0));
PERFORM EXISTS (SELECT accounting.set_credit_notes_to_journal(null));
PERFORM EXISTS (SELECT accounting.set_debit_notes_to_journal(null));
PERFORM EXISTS (SELECT accounting.set_fixed_asset_disposal(null));
PERFORM EXISTS (SELECT accounting.set_fixed_assets_disposal_to_journal(null));
PERFORM EXISTS (SELECT accounting.set_fixed_assets_to_journal(null));
PERFORM EXISTS (SELECT accounting.set_fixed_assets_to_journal_before_created_date(null));
PERFORM EXISTS (SELECT accounting.set_fixed_asstes_journal_crons());
PERFORM EXISTS (SELECT accounting.set_new_bank(null, null, null, FALSE, null));
PERFORM EXISTS (SELECT accounting.set_new_bank_cash_account(null, null, null, null, null, null, null, null, 0.0, 0.0, null, null, FALSE, null));
PERFORM EXISTS (SELECT accounting.set_new_chart_of_account(null, null, null, null, null, null, null, null, null, null, null, 0, null, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT accounting.set_new_chart_of_account(null, null, null, null, 0.0, null, null));
PERFORM EXISTS (SELECT accounting.set_new_chart_of_account_top(null, null, null, null, FALSE, null));
PERFORM EXISTS (SELECT accounting.set_new_coa(null, null, null, null, null, null, null, null, null, null, null, null, null, 0.0, 0.0, CURRENT_DATE, null));
PERFORM EXISTS (SELECT accounting.set_new_coa(null, null, null, null, null, null, null, null, null, null, null, 0, null, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT accounting.set_new_coa_from_cashbank(null, null, null, null, 0, null, FALSE, null));
PERFORM EXISTS (SELECT accounting.set_new_coa_top(null, null, null, null, FALSE, null));
PERFORM EXISTS (SELECT accounting.set_new_credit_notes(null, CURRENT_DATE, null, null, null, null, null, 0.0, 0.0, null));
PERFORM EXISTS (SELECT accounting.set_new_debit_notes(null, CURRENT_DATE, null, null, null, null, null, null, 0.0, 0.0));
PERFORM EXISTS (SELECT accounting.set_new_fixed_asset(null, CURRENT_DATE, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0.0, 0.0, 0.0, 0.0, CURRENT_DATE, null, null, null));
PERFORM EXISTS (SELECT accounting.set_new_fixed_asset_edit(null, CURRENT_DATE, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0.0, 0.0, 0.0, 0.0, CURRENT_DATE, null, null, null));
PERFORM EXISTS (SELECT accounting.set_new_general_journal(null, CURRENT_DATE, null, null, null, 0.0, null, 0.0, 0.0, null));
PERFORM EXISTS (SELECT accounting.set_new_general_journal_edit(null, CURRENT_DATE, null, null, null, 0.0, null, 0.0, 0.0, null));
PERFORM EXISTS (SELECT accounting.set_new_prepaid(null, CURRENT_DATE, null, null, null, null, CURRENT_DATE, null, 0.0, 0.0, null, null, null));
PERFORM EXISTS (SELECT accounting.set_prepaid_journal_crons());
PERFORM EXISTS (SELECT accounting.set_prepaid_to_journal(null));
PERFORM EXISTS (SELECT accounting.set_prepaid_to_journal_before_created_date(null));
PERFORM EXISTS (SELECT accounting.update_old_bank(null));
PERFORM EXISTS (SELECT accounting.update_old_bank_cash_account(null));
PERFORM EXISTS (SELECT accounting.update_old_coa(null));
PERFORM EXISTS (SELECT accounting.validate_account_code(null));
PERFORM EXISTS (SELECT accounting.validate_account_code_archive(null));
PERFORM EXISTS (SELECT accounting.validate_account_code_edit(null, null));
PERFORM EXISTS (SELECT accounting.validate_account_name(null));
PERFORM EXISTS (SELECT accounting.validate_account_name(null, 0));
PERFORM EXISTS (SELECT accounting.validate_account_name_archive(null, 0));
PERFORM EXISTS (SELECT accounting.validate_account_name_top(null));
PERFORM EXISTS (SELECT accounting.validate_asset_code(null));
PERFORM EXISTS (SELECT accounting.validate_bank_cash_account_code(null));
PERFORM EXISTS (SELECT accounting.validate_bank_cash_account_code_archive(null));
PERFORM EXISTS (SELECT accounting.validate_bank_cash_account_code_edit(null, null));
PERFORM EXISTS (SELECT accounting.validate_bank_cash_account_name(null));
PERFORM EXISTS (SELECT accounting.validate_bank_cash_account_name_archive(null));
PERFORM EXISTS (SELECT accounting.validate_bank_cash_account_name_archive_new(null));
PERFORM EXISTS (SELECT accounting.validate_bank_cash_account_name_new(null));
PERFORM EXISTS (SELECT accounting.validate_bank_code(null, null));
PERFORM EXISTS (SELECT accounting.validate_bank_edit(null, null));
PERFORM EXISTS (SELECT accounting.validate_bank_edit_code(null, null));
PERFORM EXISTS (SELECT accounting.validate_bank_name(null, null));
PERFORM EXISTS (SELECT accounting.validate_close_limit_date('accounting.journal', null));
PERFORM EXISTS (SELECT accounting.validate_code_bank_cash_account_edit(null, null, null));
PERFORM EXISTS (SELECT accounting.validate_edit_account_code(null, null));
PERFORM EXISTS (SELECT accounting.validate_edit_account_name(null, null, 0));
PERFORM EXISTS (SELECT accounting.validate_name_bank_cash_account_edit(null, null));
END;