BEGIN
PERFORM EXISTS (SELECT inventory.check_is_error_convermaterial_edit(null, null));
PERFORM EXISTS (SELECT inventory.conv_mat_det_update_stock(null, null, null));
PERFORM EXISTS (SELECT inventory.conv_mat_update_stock(null, null, null));
PERFORM EXISTS (SELECT inventory.delete_stock_ledger(null, 0));
PERFORM EXISTS (SELECT inventory.generate_mat_used_non_sales(null, null, null));
PERFORM EXISTS (SELECT inventory.generate_mat_used_non_sales_detail(null, null));
PERFORM EXISTS (SELECT inventory.generate_material_used_non_sales(null, null, null));
PERFORM EXISTS (SELECT inventory.generate_stock_taking(null, null, null));
PERFORM EXISTS (SELECT inventory.get_account());
PERFORM EXISTS (SELECT inventory.get_buffer_stock(null));
PERFORM EXISTS (SELECT inventory.get_code_transaction(null));
PERFORM EXISTS (SELECT inventory.get_code_transaction_json(null));
PERFORM EXISTS (SELECT inventory.get_convertion_material_detail_json(null));
PERFORM EXISTS (SELECT inventory.get_convertion_material_json(null));
PERFORM EXISTS (SELECT inventory.get_convertion_material_stock_json(null));
PERFORM EXISTS (SELECT inventory.get_current_stock(null));
PERFORM EXISTS (SELECT inventory.get_data_ctsb_concat());
PERFORM EXISTS (SELECT inventory.get_inventory_adjustment_by_value_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT inventory.get_inventory_adjustment_detail_json(null));
PERFORM EXISTS (SELECT inventory.get_inventory_adjustment_json(null));
PERFORM EXISTS (SELECT inventory.get_inventory_adjustment_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT inventory.get_inventory_category());
PERFORM EXISTS (SELECT inventory.get_inventory_group());
PERFORM EXISTS (SELECT inventory.get_inventory_transfer_detail_json(null));
PERFORM EXISTS (SELECT inventory.get_inventory_transfer_json(null));
PERFORM EXISTS (SELECT inventory.get_inventory_transfer_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null, null));
PERFORM EXISTS (SELECT inventory.get_inventory_transfer_report(null));
PERFORM EXISTS (SELECT inventory.get_inventory_type());
PERFORM EXISTS (SELECT inventory.get_item_category());
PERFORM EXISTS (SELECT inventory.get_item_type_all());
PERFORM EXISTS (SELECT inventory.get_item_unit());
PERFORM EXISTS (SELECT inventory.get_mat_used_type());
PERFORM EXISTS (SELECT inventory.get_material_req_non_production_detail_json(null));
PERFORM EXISTS (SELECT inventory.get_material_req_non_production_json(null));
PERFORM EXISTS (SELECT inventory.get_material_return_non_production_detail_json(null));
PERFORM EXISTS (SELECT inventory.get_material_return_non_production_json(null));
PERFORM EXISTS (SELECT inventory.get_material_used_non_production_detail_json(null));
PERFORM EXISTS (SELECT inventory.get_material_used_non_production_json(null));
PERFORM EXISTS (SELECT inventory.get_material_used_non_production_stock_json(null));
PERFORM EXISTS (SELECT inventory.get_material_used_non_sales_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT inventory.get_material_used_type_code(null));
PERFORM EXISTS (SELECT inventory.get_material_used_type_json(null));
PERFORM EXISTS (SELECT inventory.get_new_update_material_used_type(null));
PERFORM EXISTS (SELECT inventory.get_outstanding_so(null, null));
PERFORM EXISTS (SELECT inventory.get_products_for_mat_request(null, FALSE, null, null));
PERFORM EXISTS (SELECT inventory.get_products_for_mat_used(null, FALSE, null, null, null));
PERFORM EXISTS (SELECT inventory.get_products_for_se_by_qty_report(null));
PERFORM EXISTS (SELECT inventory.get_room_stocks());
PERFORM EXISTS (SELECT inventory.get_sales_forecast_item_sales_plan(null, null));
PERFORM EXISTS (SELECT inventory.get_selected_material_return_non_sales(null));
PERFORM EXISTS (SELECT inventory.get_shipping_method());
PERFORM EXISTS (SELECT inventory.get_shipping_method_json(null));
PERFORM EXISTS (SELECT inventory.get_stock_ledger_sticker(0.0, 0.0));
PERFORM EXISTS (SELECT inventory.get_stock_list_involved(null, 0));
PERFORM EXISTS (SELECT inventory.get_stock_taking_by_value_report(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT inventory.get_stock_taking_detail_json(null));
PERFORM EXISTS (SELECT inventory.get_stock_taking_json(null));
PERFORM EXISTS (SELECT inventory.get_stock_taking_report(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT inventory.get_stock_taking_work_sheet_report_test(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT inventory.get_stock_taking_work_sheet_report_test(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT inventory.get_unit());
PERFORM EXISTS (SELECT inventory.get_unit_for_convertion_material(null));
PERFORM EXISTS (SELECT inventory.get_view_code_transaction_json(null));
PERFORM EXISTS (SELECT inventory.get_view_convertion_material_detail_json(null));
PERFORM EXISTS (SELECT inventory.get_view_convertion_material_json(null));
PERFORM EXISTS (SELECT inventory.get_view_convertion_material_stock_json(null));
PERFORM EXISTS (SELECT inventory.get_view_inventory_adjustment_detail_json(null));
PERFORM EXISTS (SELECT inventory.get_view_inventory_adjustment_json(null));
PERFORM EXISTS (SELECT inventory.get_view_inventory_transfer_detail_json(null));
PERFORM EXISTS (SELECT inventory.get_view_inventory_transfer_json(null));
PERFORM EXISTS (SELECT inventory.get_view_material_req_non_production_detail_json(null));
PERFORM EXISTS (SELECT inventory.get_view_material_req_non_production_json(null));
PERFORM EXISTS (SELECT inventory.get_view_material_return_non_production_detail_json(null));
PERFORM EXISTS (SELECT inventory.get_view_material_return_non_production_json(null));
PERFORM EXISTS (SELECT inventory.get_view_material_used_non_production_detail_json(null));
PERFORM EXISTS (SELECT inventory.get_view_material_used_non_production_json(null));
PERFORM EXISTS (SELECT inventory.get_view_material_used_non_production_stock_json(null));
PERFORM EXISTS (SELECT inventory.get_view_material_used_type_json(null));
PERFORM EXISTS (SELECT inventory.get_view_shipping_method_json(null));
PERFORM EXISTS (SELECT inventory.get_view_stock_taking_detail_json(null));
PERFORM EXISTS (SELECT inventory.get_view_stock_taking_json(null));
PERFORM EXISTS (SELECT inventory.get_warehouse_for_convertion_material(null, null, null, null));
PERFORM EXISTS (SELECT inventory.insert_edit_convertion_material(null));
PERFORM EXISTS (SELECT inventory.insert_edit_inventory_adjustment(null));
PERFORM EXISTS (SELECT inventory.insert_edit_inventory_transfer(null));
PERFORM EXISTS (SELECT inventory.insert_edit_material_request_non_sales(null));
PERFORM EXISTS (SELECT inventory.insert_edit_material_return_non_production(null));
PERFORM EXISTS (SELECT inventory.insert_edit_material_used_non_production(null));
PERFORM EXISTS (SELECT inventory.insert_edit_stock_taking(null));
PERFORM EXISTS (SELECT inventory.insert_inv_adj_last_buying(null));
PERFORM EXISTS (SELECT inventory.inv_adj_update_stock(null, null, null, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.inv_trf_check_stock(null, null, null));
PERFORM EXISTS (SELECT inventory.inv_trf_update_stock(null, null, null, 0));
PERFORM EXISTS (SELECT inventory.inv_trf_update_stock_test(null, null, null, 0));
PERFORM EXISTS (SELECT inventory.inventory_adjustment_detail_print_out());
PERFORM EXISTS (SELECT inventory.inventory_adjustment_print_out(null));
PERFORM EXISTS (SELECT inventory.inventory_transfer_detail_printout());
PERFORM EXISTS (SELECT inventory.inventory_transfer_report(null, null));
PERFORM EXISTS (SELECT inventory.inventory_transfer_report_detail());
PERFORM EXISTS (SELECT inventory.inventory_transfer_report_print(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT inventory.list_convertion_material(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.list_convertion_material_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.list_convertion_material_edit(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT inventory.list_convertion_material_list_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.list_convertion_material_list_parent(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT inventory.list_convertion_material_stock(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.list_cost_center_for_inventory_adjustment_lookup());
PERFORM EXISTS (SELECT inventory.list_cost_center_for_material_return_nonsales_lookup());
PERFORM EXISTS (SELECT inventory.list_cost_center_for_material_used_nonsales_lookup());
PERFORM EXISTS (SELECT inventory.list_covertion_material_detail_edit(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.list_failed_stock_for_mat_used(null));
PERFORM EXISTS (SELECT inventory.list_inv_adj(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null, null, null, null));
PERFORM EXISTS (SELECT inventory.list_inventory(null, FALSE, null));
PERFORM EXISTS (SELECT inventory.list_inventory(null, FALSE, null, null));
PERFORM EXISTS (SELECT inventory.list_inventory_adjustment(CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT inventory.list_inventory_adjustment_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.list_inventory_adjustment_detail_edits(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.list_inventory_adjustment_detail_report(null, FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT inventory.list_inventory_adjustment_for_edit(CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT inventory.list_inventory_adjustment_list_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.list_inventory_adjustment_list_parent(null, FALSE, CURRENT_DATE, CURRENT_DATE, null, null, null, FALSE));
PERFORM EXISTS (SELECT inventory.list_inventory_adjustment_report(CURRENT_DATE, CURRENT_DATE, FALSE, null, null, FALSE));
PERFORM EXISTS (SELECT inventory.list_inventory_transfer(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT inventory.list_inventory_transfer_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.list_inventory_transfer_detail_edit(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.list_inventory_transfer_edit(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null, null));
PERFORM EXISTS (SELECT inventory.list_inventory_transfer_edit_new(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null, null, null));
PERFORM EXISTS (SELECT inventory.list_inventory_transfer_list_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.list_inventory_transfer_list_new(null));
PERFORM EXISTS (SELECT inventory.list_inventory_transfer_list_parent(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null, null, null));
PERFORM EXISTS (SELECT inventory.list_inventory_transfer_product(null));
PERFORM EXISTS (SELECT inventory.list_inventory_transfer_report(FALSE, CURRENT_DATE, CURRENT_DATE, null));
--PERFORM EXISTS (SELECT inventory.list_items_choose(null, FALSE, null, FALSE, null, FALSE));
PERFORM EXISTS (SELECT inventory.list_mat_req_non_prd(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.list_mat_req_non_prd(FALSE, CURRENT_DATE, CURRENT_DATE, null, null, null, null));
PERFORM EXISTS (SELECT inventory.list_mat_return_non_sales_edit(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null, null, null, null));
PERFORM EXISTS (SELECT inventory.list_mat_used_for_inventory_adjustment_lookup());
PERFORM EXISTS (SELECT inventory.list_mat_used_for_material_return_nonsales_lookup());
PERFORM EXISTS (SELECT inventory.list_mat_used_for_material_used_nonsales_lookup());
PERFORM EXISTS (SELECT inventory.list_material_req_non_production(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT inventory.list_material_req_non_production(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.list_material_req_non_production_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.list_material_req_non_production_detail_edit(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.list_material_req_non_production_detail_for_mat_used(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT inventory.list_material_req_non_production_detail_report(null));
PERFORM EXISTS (SELECT inventory.list_material_req_non_production_detail_report_new(null, null, null));
PERFORM EXISTS (SELECT inventory.list_material_req_non_production_for_mat_used(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT inventory.list_material_req_non_production_list_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.list_material_req_non_production_list_parent(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null, null, null, null));
PERFORM EXISTS (SELECT inventory.list_material_req_non_sales_edit(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null, null, null));
PERFORM EXISTS (SELECT inventory.list_material_req_non_sales_report(FALSE, CURRENT_DATE, CURRENT_DATE, null, null));
PERFORM EXISTS (SELECT inventory.list_material_return_non_production(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT inventory.list_material_return_non_production_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.list_material_return_non_production_detail_report(null, FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT inventory.list_material_return_non_production_detail_report(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.list_material_return_non_production_list_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.list_material_return_non_production_list_parent(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null, null, null));
PERFORM EXISTS (SELECT inventory.list_material_return_non_production_list_parent(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.list_material_return_non_production_report(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.list_material_used_non_production(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT inventory.list_material_used_non_production_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.list_material_used_non_production_detail_edit(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null, null));
PERFORM EXISTS (SELECT inventory.list_material_used_non_production_list_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.list_material_used_non_production_list_parent(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null, null));
PERFORM EXISTS (SELECT inventory.list_material_used_non_production_list_parent(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.list_material_used_non_production_list_report(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT inventory.list_material_used_non_production_stock(null));
PERFORM EXISTS (SELECT inventory.list_material_used_non_sales_detail_report(null));
PERFORM EXISTS (SELECT inventory.list_material_used_non_sales_edit(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT inventory.list_material_used_non_sales_edit_detail(null, FALSE, null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT inventory.list_material_used_non_sales_report(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT inventory.list_material_used_type(null, FALSE));
PERFORM EXISTS (SELECT inventory.list_material_used_type_archive(null));
PERFORM EXISTS (SELECT inventory.list_of_material_used_type(null));
PERFORM EXISTS (SELECT inventory.list_product_for_inv_transfer_report_lookup());
PERFORM EXISTS (SELECT inventory.list_product_for_stock_taking_byvalue_lookup(null));
PERFORM EXISTS (SELECT inventory.list_product_inv_adjust_report(null));
PERFORM EXISTS (SELECT inventory.list_product_inv_adjust_report_value(null));
PERFORM EXISTS (SELECT inventory.list_product_material_non_sales_report(null));
PERFORM EXISTS (SELECT inventory.list_product_stock_taking_report(null));
PERFORM EXISTS (SELECT inventory.list_product_stock_taking_ws_report());
PERFORM EXISTS (SELECT inventory.list_quality_control_check_report(null, FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT inventory.list_return_mat_use_non_prd(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.list_return_mat_use_non_prd_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.list_stock_available(null));
PERFORM EXISTS (SELECT inventory.list_stock_taking(FALSE, CURRENT_DATE, CURRENT_DATE, null, null));
PERFORM EXISTS (SELECT inventory.list_stock_taking_detail(null));
PERFORM EXISTS (SELECT inventory.list_stock_taking_detail_edit(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.list_stock_taking_edit(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null, null));
PERFORM EXISTS (SELECT inventory.list_stock_taking_list_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.list_stock_taking_list_new(null));
PERFORM EXISTS (SELECT inventory.list_stock_taking_list_parent(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null, null));
PERFORM EXISTS (SELECT inventory.list_warehouse_for_inventory_adjustment_lookup());
PERFORM EXISTS (SELECT inventory.list_warehouse_for_material_return_nonsales_lookup());
PERFORM EXISTS (SELECT inventory.list_warehouse_for_material_used_non_sales_lookup(null));
PERFORM EXISTS (SELECT inventory.list_warehouse_for_stock_taking_byvalue_lookup(null));
PERFORM EXISTS (SELECT inventory.list_warehouse_from_inv_trans_edit());
PERFORM EXISTS (SELECT inventory.list_warehouse_inven_adjust_report(null));
PERFORM EXISTS (SELECT inventory.list_warehouse_inven_adjust_report_value(null));
PERFORM EXISTS (SELECT inventory.list_warehouse_stock_taking_report(null));
PERFORM EXISTS (SELECT inventory.list_warehouse_stock_taking_ws_report());
PERFORM EXISTS (SELECT inventory.list_warehouse_to_inven_trans_edit());
PERFORM EXISTS (SELECT inventory.mat_ret_non_prod_update_stock(null, null, null));
PERFORM EXISTS (SELECT inventory.mat_used_canceled(null, null));
PERFORM EXISTS (SELECT inventory.mat_used_non_prod_update_stock(null, null, null));
PERFORM EXISTS (SELECT inventory.mat_used_remove(null, null, null));
PERFORM EXISTS (SELECT inventory.open_close_convertion_material(null, FALSE));
PERFORM EXISTS (SELECT inventory.open_close_inventory_adjusment(null, FALSE));
PERFORM EXISTS (SELECT inventory.open_close_inventory_transfer(null, FALSE));
PERFORM EXISTS (SELECT inventory.open_close_material_request(null, FALSE));
PERFORM EXISTS (SELECT inventory.open_close_material_return(null, FALSE));
PERFORM EXISTS (SELECT inventory.open_close_material_used(null, FALSE));
PERFORM EXISTS (SELECT inventory.open_close_stock_taking(null, FALSE));
PERFORM EXISTS (SELECT inventory.open_list_convertion_material(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.open_list_convertion_material_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.open_list_convertion_material_stock(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.open_list_inventory_adjustment(CURRENT_DATE, CURRENT_DATE, FALSE));
PERFORM EXISTS (SELECT inventory.open_list_inventory_adjustment_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.open_list_inventory_transfer(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.open_list_inventory_transfer_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.open_list_material_req_non_production(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.open_list_material_req_non_production_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.open_list_material_return_non_production(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.open_list_material_return_non_production_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.open_list_material_used_non_production(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.open_list_material_used_non_production_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.open_list_material_used_non_production_stock(null));
PERFORM EXISTS (SELECT inventory.open_list_stock_taking(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT inventory.open_list_stock_taking_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT inventory.print_inventory_adjustment_by_value_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT inventory.print_inventory_adjustment_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT inventory.print_inventory_transfer_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT inventory.print_material_used_non_sales_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT inventory.print_stock_taking_by_value_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT inventory.print_stock_taking_report(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT inventory.print_stock_taking_work_sheet_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT inventory.print_stock_taking_work_sheet_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT inventory.report_convertion_material_list_detail(null));
PERFORM EXISTS (SELECT inventory.report_convertion_material_list_parent(null));
PERFORM EXISTS (SELECT inventory.report_inventory_adj(null));
PERFORM EXISTS (SELECT inventory.report_inventory_adj_detail_generate(null));
PERFORM EXISTS (SELECT inventory.report_inventory_adjustment(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT inventory.report_inventory_adjustment_by_value(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT inventory.report_inventory_adjustment_list_detail(null));
PERFORM EXISTS (SELECT inventory.report_inventory_adjustment_list_parent(null));
PERFORM EXISTS (SELECT inventory.report_inventory_transfer(null));
PERFORM EXISTS (SELECT inventory.report_inventory_transfer_detail(null));
PERFORM EXISTS (SELECT inventory.report_list_inventory_transfer_detail_generate(null));
PERFORM EXISTS (SELECT inventory.report_list_inventory_transfer_generate(null));
PERFORM EXISTS (SELECT inventory.report_mat_req_non_production_list_detail(null));
PERFORM EXISTS (SELECT inventory.report_mat_req_non_production_list_parent(null));
PERFORM EXISTS (SELECT inventory.report_mat_req_non_sales(null));
PERFORM EXISTS (SELECT inventory.report_mat_req_non_sales_detail(null));
PERFORM EXISTS (SELECT inventory.report_mat_ret_non_production_list_detail(null));
PERFORM EXISTS (SELECT inventory.report_mat_ret_non_production_list_parent(null));
PERFORM EXISTS (SELECT inventory.report_mat_used_non_prd_list_detail(null));
PERFORM EXISTS (SELECT inventory.report_mat_used_non_prd_list_parent(null));
PERFORM EXISTS (SELECT inventory.report_material_request_non_sales(null, null));
PERFORM EXISTS (SELECT inventory.report_material_request_non_sales_detail(null, null));
PERFORM EXISTS (SELECT inventory.report_material_request_non_sales_detail_new());
PERFORM EXISTS (SELECT inventory.report_material_return_non_sales(null, null));
PERFORM EXISTS (SELECT inventory.report_material_return_non_sales_detail(null));
PERFORM EXISTS (SELECT inventory.report_material_return_non_sales_detail(null, null));
PERFORM EXISTS (SELECT inventory.report_material_used_non_sales(null));
PERFORM EXISTS (SELECT inventory.report_material_used_non_sales_detail(null));
PERFORM EXISTS (SELECT inventory.report_material_used_non_sales_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT inventory.report_stock_taking_by_value(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT inventory.report_stock_taking_list_detail(null));
PERFORM EXISTS (SELECT inventory.report_stock_taking_list_parent(null));
PERFORM EXISTS (SELECT inventory.reset_material_used_non_production(null, null, null, null, null));
PERFORM EXISTS (SELECT inventory.save_mat_used_non_sales_edit(null, null, null, null, null));
PERFORM EXISTS (SELECT inventory.set_new_convertion_material(null, CURRENT_DATE, null, null, null, null, null, null, null, null, 0.0, null, now(), null, null));
PERFORM EXISTS (SELECT inventory.set_new_convertion_material_edit(null, CURRENT_DATE, null, null, null, null, null, null, null, null, 0.0, null, now(), null, null));
PERFORM EXISTS (SELECT inventory.set_new_inventory_transfer(null, CURRENT_DATE, null, null, null, null, null, null, null, null, 0));
PERFORM EXISTS (SELECT inventory.set_new_material_req_non_production(null, CURRENT_DATE, null, null, null, 0, null, null));
PERFORM EXISTS (SELECT inventory.set_new_material_return_non_production(null, CURRENT_DATE, null, null, null, null, null, null, null, null));
PERFORM EXISTS (SELECT inventory.set_new_material_return_non_production_approved(null, CURRENT_DATE, null, null, null, null, null, null, null, null));
PERFORM EXISTS (SELECT inventory.set_new_material_used_non_production(null, CURRENT_DATE, null, null, null, null, null, null));
PERFORM EXISTS (SELECT inventory.set_new_material_used_non_production_approval(null, CURRENT_DATE, null, null, null, null, null, null));
PERFORM EXISTS (SELECT inventory.set_new_material_used_type(null, null, null, null, FALSE, null));
PERFORM EXISTS (SELECT inventory.set_new_stock_taking(null, CURRENT_DATE, null, null, null, null, null));
PERFORM EXISTS (SELECT inventory.set_new_stock_taking_revisi(null, CURRENT_DATE, null, null, null, null, 0, null));
PERFORM EXISTS (SELECT inventory.set_new_update_inventory_adjustment(null, null, null, null, now(), null, null, null));
PERFORM EXISTS (SELECT inventory.set_new_update_inventory_adjustment_beginning(null, null, null, null, now(), null, null, null));
PERFORM EXISTS (SELECT inventory.set_new_update_inventory_adjustment_journal(null, null));
PERFORM EXISTS (SELECT inventory.stock_taking_detail_update_ordered(null, null));
PERFORM EXISTS (SELECT inventory.stock_taking_update_ordered(null, null));
PERFORM EXISTS (SELECT inventory.stock_taking_update_stock(null, null, null));
PERFORM EXISTS (SELECT inventory.update_old_material_used_type(null));
PERFORM EXISTS (SELECT inventory.update_trans_stat_convertion_material(null, 0));
PERFORM EXISTS (SELECT inventory.validasi_stock_mat_used_non_sales(null));
PERFORM EXISTS (SELECT inventory.validate_material_used_type_code(null));
PERFORM EXISTS (SELECT inventory.validate_material_used_type_code_archive(null));
PERFORM EXISTS (SELECT inventory.validate_material_used_type_edit_code(null, null));
PERFORM EXISTS (SELECT inventory.validate_material_used_type_edit_name(null, null));
PERFORM EXISTS (SELECT inventory.validate_material_used_type_name(null));
PERFORM EXISTS (SELECT inventory.validate_material_used_type_name_archive(null));
END;