BEGIN
PERFORM EXISTS (SELECT purchasing.aa(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE));
PERFORM EXISTS (SELECT purchasing.ap_invoice_detail_report());
PERFORM EXISTS (SELECT purchasing.ap_invoice_report(null));
PERFORM EXISTS (SELECT purchasing.completing_ap_invoice_transaction(null, null, null, 0.0));
PERFORM EXISTS (SELECT purchasing.completing_purchase_order_transaction(null, null));
PERFORM EXISTS (SELECT purchasing.count_discount(0.0, null, FALSE));
PERFORM EXISTS (SELECT purchasing.count_taxes(0.0, null));
PERFORM EXISTS (SELECT purchasing.delete_grn_detail(null));
PERFORM EXISTS (SELECT purchasing.delete_item_poir(null));
PERFORM EXISTS (SELECT purchasing.fc_qc_analis(null, null));
PERFORM EXISTS (SELECT purchasing.generate_purchase_return_detail(null, null));
PERFORM EXISTS (SELECT purchasing.get_account());
PERFORM EXISTS (SELECT purchasing.get_all_forecast_by_instance(null));
PERFORM EXISTS (SELECT purchasing.get_all_supplier());
PERFORM EXISTS (SELECT purchasing.get_all_warehouse(null));
PERFORM EXISTS (SELECT purchasing.get_ap_aging_report_detail(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.get_ap_aging_report_summary(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.get_ap_invoice_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.get_ap_invoice_report_detail(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.get_ap_invoice_report_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT purchasing.get_ap_invoice_report_detail_old(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT purchasing.get_ap_invoice_report_details(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, 0));
PERFORM EXISTS (SELECT purchasing.get_ap_invoice_report_details_by_instance(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, 0, null));
PERFORM EXISTS (SELECT purchasing.get_ap_invoice_report_summary(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, 0));
PERFORM EXISTS (SELECT purchasing.get_ap_invoice_report_summary_by_instance(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, 0, null));
PERFORM EXISTS (SELECT purchasing.get_ap_ledger(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT purchasing.get_ap_ledger(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.get_ap_purchase_journal(CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT purchasing.get_ap_purchase_journal_beginning_x(CURRENT_DATE, null, null, FALSE));
PERFORM EXISTS (SELECT purchasing.get_ap_unbilled_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.get_currency());
PERFORM EXISTS (SELECT purchasing.get_data_purchase_return_edit(null));
PERFORM EXISTS (SELECT purchasing.get_forecast_delivery_plan_json(null));
PERFORM EXISTS (SELECT purchasing.get_forecast_delivery_product_json(null));
PERFORM EXISTS (SELECT purchasing.get_forecast_json(null));
PERFORM EXISTS (SELECT purchasing.get_forecast_plan_by_id_forecast(null));
PERFORM EXISTS (SELECT purchasing.get_forecast_product_json(null));
PERFORM EXISTS (SELECT purchasing.get_goods_received_notes_details_json(null));
PERFORM EXISTS (SELECT purchasing.get_goods_received_notes_json(null));
PERFORM EXISTS (SELECT purchasing.get_grn_list(FALSE, null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT purchasing.get_grn_list_edit(FALSE, null, FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT purchasing.get_grn_list_new(FALSE, null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT purchasing.get_grn_monitoring_report(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT purchasing.get_grn_monitoring_report_by_instance(null, FALSE, CURRENT_DATE, CURRENT_DATE, null, FALSE, null));
PERFORM EXISTS (SELECT purchasing.get_grn_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.get_grn_report_by_instances(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT purchasing.get_inventory_ratio());
PERFORM EXISTS (SELECT purchasing.get_inventory_ratio_pr());
PERFORM EXISTS (SELECT purchasing.get_lookup_product_for_grn_monitoring_report());
PERFORM EXISTS (SELECT purchasing.get_master_fob_json(null));
PERFORM EXISTS (SELECT purchasing.get_master_priority_json(null));
PERFORM EXISTS (SELECT purchasing.get_master_status_json(null));
PERFORM EXISTS (SELECT purchasing.get_master_transaction_type_json(null));
PERFORM EXISTS (SELECT purchasing.get_new_update_purchase_order(null));
PERFORM EXISTS (SELECT purchasing.get_new_update_purchase_request(null));
PERFORM EXISTS (SELECT purchasing.get_new_update_qc_parameter(null));
PERFORM EXISTS (SELECT purchasing.get_new_update_transaction_type(null));
PERFORM EXISTS (SELECT purchasing.get_parameter_qc());
PERFORM EXISTS (SELECT purchasing.get_payment_term());
PERFORM EXISTS (SELECT purchasing.get_payment_type_po());
PERFORM EXISTS (SELECT purchasing.get_pool());
PERFORM EXISTS (SELECT purchasing.get_price_contract_detail_discount_json(null));
PERFORM EXISTS (SELECT purchasing.get_price_contract_detail_json(null));
PERFORM EXISTS (SELECT purchasing.get_price_contract_detail_taxes_json(null));
PERFORM EXISTS (SELECT purchasing.get_price_contract_json(null));
PERFORM EXISTS (SELECT purchasing.get_price_last_buying(null));
PERFORM EXISTS (SELECT purchasing.get_project());
PERFORM EXISTS (SELECT purchasing.get_purchae_lite_detail(null));
PERFORM EXISTS (SELECT purchasing.get_purchase_invoice_advance_settle_json(null));
PERFORM EXISTS (SELECT purchasing.get_purchase_invoice_advance_unsettle_json(null));
PERFORM EXISTS (SELECT purchasing.get_purchase_invoice_detail_json(null));
PERFORM EXISTS (SELECT purchasing.get_purchase_invoice_json(null));
PERFORM EXISTS (SELECT purchasing.get_purchase_invoice_po_detail_json(null));
PERFORM EXISTS (SELECT purchasing.get_purchase_invoice_receive_item_detail_json(null));
PERFORM EXISTS (SELECT purchasing.get_purchase_lite_adv(null));
PERFORM EXISTS (SELECT purchasing.get_purchase_order_close(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.get_purchase_order_close_by_instance(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT purchasing.get_purchase_order_detail_json(null));
PERFORM EXISTS (SELECT purchasing.get_purchase_order_detail_old_json(null));
PERFORM EXISTS (SELECT purchasing.get_purchase_order_detail_requisition_json(null));
PERFORM EXISTS (SELECT purchasing.get_purchase_order_items_draft_json(null));
PERFORM EXISTS (SELECT purchasing.get_purchase_order_items_json(null));
PERFORM EXISTS (SELECT purchasing.get_purchase_order_items_requisition_json(null));
PERFORM EXISTS (SELECT purchasing.get_purchase_order_json(null));
PERFORM EXISTS (SELECT purchasing.get_purchase_order_manual_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT purchasing.get_purchase_order_manual_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.get_purchase_order_manual_report_by_instance(null, null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT purchasing.get_purchase_order_old_json(null));
PERFORM EXISTS (SELECT purchasing.get_purchase_order_outsanding_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT purchasing.get_purchase_order_outsanding_report_by_instance(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT purchasing.get_purchase_order_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.get_purchase_order_report_by_instance(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT purchasing.get_purchase_order_termin_json(null));
PERFORM EXISTS (SELECT purchasing.get_purchase_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.get_purchase_request_manual_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT purchasing.get_purchase_request_manual_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.get_purchase_request_manual_report_by_instance(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.get_purchase_request_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null, null));
PERFORM EXISTS (SELECT purchasing.get_purchase_request_report_by_instance(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null, null, null));
PERFORM EXISTS (SELECT purchasing.get_purchase_requisition_detail_json(null));
PERFORM EXISTS (SELECT purchasing.get_purchase_requisition_json(null));
PERFORM EXISTS (SELECT purchasing.get_purchase_return_by_product(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.get_purchase_return_detail_json(null));
PERFORM EXISTS (SELECT purchasing.get_purchase_return_json(null));
PERFORM EXISTS (SELECT purchasing.get_purchase_return_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.get_purchase_return_report_by_instance(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT purchasing.get_qc_category());
PERFORM EXISTS (SELECT purchasing.get_qc_reject_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.get_qc_reject_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT purchasing.get_qc_reject_report_by_instance(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null, null));
PERFORM EXISTS (SELECT purchasing.get_quality_control_analysis_json(null));
PERFORM EXISTS (SELECT purchasing.get_quality_control_category_json(null));
PERFORM EXISTS (SELECT purchasing.get_quality_control_check_report(FALSE, CURRENT_DATE, CURRENT_DATE, null, null, FALSE, null));
PERFORM EXISTS (SELECT purchasing.get_quality_control_detail_json(null));
PERFORM EXISTS (SELECT purchasing.get_quality_control_json(null));
PERFORM EXISTS (SELECT purchasing.get_quality_control_parameter_json(null));
PERFORM EXISTS (SELECT purchasing.get_request_outstanding_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT purchasing.get_request_outstanding_report_by_instance(null, null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT purchasing.get_request_report_by_product(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.get_request_report_by_product_by_instance(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT purchasing.get_requisition_detail_json(null));
PERFORM EXISTS (SELECT purchasing.get_requisition_json(null));
PERFORM EXISTS (SELECT purchasing.get_selected_items(null));
PERFORM EXISTS (SELECT purchasing.get_supllier());
PERFORM EXISTS (SELECT purchasing.get_supllier_ap_invoice());
PERFORM EXISTS (SELECT purchasing.get_supplier(null));
PERFORM EXISTS (SELECT purchasing.get_supplier_ap_invoice(null));
PERFORM EXISTS (SELECT purchasing.get_supplier_bank(null, null));
PERFORM EXISTS (SELECT purchasing.get_supplier_bank_id(null));
PERFORM EXISTS (SELECT purchasing.get_supplier_bank_new(null));
PERFORM EXISTS (SELECT purchasing.get_supplier_bank_old(null));
PERFORM EXISTS (SELECT purchasing.get_transaction_status(0));
PERFORM EXISTS (SELECT purchasing.get_transaction_type());
PERFORM EXISTS (SELECT purchasing.get_vat_type_po());
PERFORM EXISTS (SELECT purchasing.get_vendor_category());
PERFORM EXISTS (SELECT purchasing.get_view_forecast_delivery_plan_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_forecast_delivery_product_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_forecast_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_forecast_product_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_goods_received_notes_details_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_goods_received_notes_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_master_fob_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_master_priority_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_master_status_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_master_transaction_type_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_price_contract_detail_discount_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_price_contract_detail_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_price_contract_detail_taxes_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_price_contract_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_purchase_invoice_advance_settle_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_purchase_invoice_detail_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_purchase_invoice_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_purchase_invoice_po_detail_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_purchase_invoice_receive_item_detail_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_purchase_order_detail_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_purchase_order_detail_old_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_purchase_order_detail_requisition_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_purchase_order_items_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_purchase_order_items_requisition_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_purchase_order_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_purchase_order_old_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_purchase_order_termin_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_purchase_requisition_detail_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_purchase_requisition_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_purchase_return_detail_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_purchase_return_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_quality_control_analysis_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_quality_control_category_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_quality_control_detail_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_quality_control_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_quality_control_parameter_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_requisition_detail_json(null));
PERFORM EXISTS (SELECT purchasing.get_view_requisition_json(null));
PERFORM EXISTS (SELECT purchasing.get_warehouse());
PERFORM EXISTS (SELECT purchasing.get_warehouse(null));
PERFORM EXISTS (SELECT purchasing.get_warehouse_for_report(null));
PERFORM EXISTS (SELECT purchasing.get_warehouse_from(null, null));
PERFORM EXISTS (SELECT purchasing.get_warehouse_instance(null));
PERFORM EXISTS (SELECT purchasing.get_warehouse_sales_instance(null));
PERFORM EXISTS (SELECT purchasing.get_warehouse_to(null));
PERFORM EXISTS (SELECT purchasing.get_warehouse_to(null, null));
PERFORM EXISTS (SELECT purchasing.grn_detail_add_batch(null));
PERFORM EXISTS (SELECT purchasing.insert_edit_ap_invoice(null));
PERFORM EXISTS (SELECT purchasing.insert_edit_goods_received_notes(null));
PERFORM EXISTS (SELECT purchasing.insert_edit_purchase_lite(null));
PERFORM EXISTS (SELECT purchasing.insert_edit_purchase_order(null));
PERFORM EXISTS (SELECT purchasing.insert_edit_purchase_order_manual_edit(null));
PERFORM EXISTS (SELECT purchasing.insert_edit_purchase_request(null));
PERFORM EXISTS (SELECT purchasing.insert_edit_purchase_return(null));
PERFORM EXISTS (SELECT purchasing.insert_from_pr_to_po(null, null));
PERFORM EXISTS (SELECT purchasing.insert_good_receivied_notes_generate(null, null));
PERFORM EXISTS (SELECT purchasing.insert_journal_purchase_lite(null, 0.0));
PERFORM EXISTS (SELECT purchasing.insert_po_last_buying(null, null, null, null));
PERFORM EXISTS (SELECT purchasing.insert_price_contract_detail(null, null));
PERFORM EXISTS (SELECT purchasing.insert_price_contract_detail_all_products(null, null));
PERFORM EXISTS (SELECT purchasing.insert_purchase_invoice_advance_settle(null, null));
PERFORM EXISTS (SELECT purchasing.insert_purchase_invoice_generate(null, null, null));
PERFORM EXISTS (SELECT purchasing.insert_purchase_lite_generate(null, null));
PERFORM EXISTS (SELECT purchasing.insert_purchase_lite_generate_by_batch(null, null));
PERFORM EXISTS (SELECT purchasing.insert_purchase_lite_generate_by_product(null, null));
PERFORM EXISTS (SELECT purchasing.insert_purchase_lite_last_buying(null, null, null, null));
PERFORM EXISTS (SELECT purchasing.insert_purchase_order_details(null));
PERFORM EXISTS (SELECT purchasing.insert_purchase_order_generate(null, null));
PERFORM EXISTS (SELECT purchasing.insert_purchase_order_items_requisition(null));
PERFORM EXISTS (SELECT purchasing.insert_purchase_requisition_detail(null, null));
PERFORM EXISTS (SELECT purchasing.insert_quality_control_edit(null));
PERFORM EXISTS (SELECT purchasing.insert_quality_control_generate(null, null));
PERFORM EXISTS (SELECT purchasing.insert_settle_ap(null, null, null));
PERFORM EXISTS (SELECT purchasing.insert_settle_ap_invoice(null, null, null));
PERFORM EXISTS (SELECT purchasing.insert_settle_purchase_lite(null, null));
PERFORM EXISTS (SELECT purchasing.is_forecast_valid(null));
PERFORM EXISTS (SELECT purchasing.list_account_for_ap_invoice_beginning());
PERFORM EXISTS (SELECT purchasing.list_ap_invoice_beginning(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT purchasing.list_ap_invoice_beginning_edit(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.list_ap_invoice_beginning_list_parent(FALSE, CURRENT_DATE, CURRENT_DATE, null, FALSE, null, null, null, null));
PERFORM EXISTS (SELECT purchasing.list_ap_invoice_edit(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.list_ap_invoice_for_debit_notes(null, null));
PERFORM EXISTS (SELECT purchasing.list_apinvoice(null, FALSE, CURRENT_DATE, CURRENT_DATE, null, FALSE));
PERFORM EXISTS (SELECT purchasing.list_apinvoice_advance_settle(null));
PERFORM EXISTS (SELECT purchasing.list_apinvoice_advance_settle_detail_report(null));
PERFORM EXISTS (SELECT purchasing.list_apinvoice_detail(null));
PERFORM EXISTS (SELECT purchasing.list_apinvoice_detail_info(null));
PERFORM EXISTS (SELECT purchasing.list_apinvoice_detail_old(null));
PERFORM EXISTS (SELECT purchasing.list_apinvoice_detail_report(null, null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT purchasing.list_apinvoice_item_detail(null));
PERFORM EXISTS (SELECT purchasing.list_apinvoice_item_detail_new(null));
PERFORM EXISTS (SELECT purchasing.list_apinvoice_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT purchasing.list_category_for_po_lookup());
PERFORM EXISTS (SELECT purchasing.list_contract_price_detail(null));
PERFORM EXISTS (SELECT purchasing.list_goods_received_notes(null, null));
PERFORM EXISTS (SELECT purchasing.list_goods_received_notes_filtr(null, FALSE, CURRENT_DATE, CURRENT_DATE, null, FALSE, null, FALSE));
PERFORM EXISTS (SELECT purchasing.list_goods_received_notes_filtr_detail(null));
PERFORM EXISTS (SELECT purchasing.list_goods_received_notes_filtr_detail_report(null));
PERFORM EXISTS (SELECT purchasing.list_goods_received_notes_filtr_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null, FALSE, null));
PERFORM EXISTS (SELECT purchasing.list_goods_reeceived_notes_detail(null, null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT purchasing.list_grn(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, FALSE, null));
PERFORM EXISTS (SELECT purchasing.list_grn(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE));
PERFORM EXISTS (SELECT purchasing.list_grn_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT purchasing.list_grn_detail_new(null));
PERFORM EXISTS (SELECT purchasing.list_grn_detail_qc_edit(null));
PERFORM EXISTS (SELECT purchasing.list_grn_new(null));
PERFORM EXISTS (SELECT purchasing.list_grn_parent_qc_edit(FALSE, CURRENT_DATE, CURRENT_DATE, null, null, null));
PERFORM EXISTS (SELECT purchasing.list_group_for_pr_report());
PERFORM EXISTS (SELECT purchasing.list_item_preturn(null, null, FALSE, null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT purchasing.list_item_preturn_detail_report(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT purchasing.list_item_preturn_report(FALSE, CURRENT_DATE, CURRENT_DATE, null, FALSE));
PERFORM EXISTS (SELECT purchasing.list_item_purchase_report(null, FALSE));
PERFORM EXISTS (SELECT purchasing.list_item_purchase_requisition(null, null, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.list_item_purchase_requisition_edit(null, FALSE));
--PERFORM EXISTS (SELECT purchasing.list_item_purchase_requisition_manual(null, null, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.list_items_purchase_price_contract_discount(null));
PERFORM EXISTS (SELECT purchasing.list_items_purchase_price_contract_taxes(null));
PERFORM EXISTS (SELECT purchasing.list_lookup_product_qcc_report());
PERFORM EXISTS (SELECT purchasing.list_po(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE));
PERFORM EXISTS (SELECT purchasing.list_po_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE, null, FALSE, null));
PERFORM EXISTS (SELECT purchasing.list_po_detail_edit(null, FALSE, CURRENT_DATE, CURRENT_DATE, null, FALSE, null));
PERFORM EXISTS (SELECT purchasing.list_po_edit(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT purchasing.list_po_for_purchase_advance(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT purchasing.list_po_manual_edit(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, FALSE));
PERFORM EXISTS (SELECT purchasing.list_po_manual_edit_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE, null, FALSE, null));
PERFORM EXISTS (SELECT purchasing.list_po_paging(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT purchasing.list_po_termin(null));
--PERFORM EXISTS (SELECT purchasing.list_price_contract(null, FALSE, FALSE, CURRENT_DATE, FALSE, null, 0));
PERFORM EXISTS (SELECT purchasing.list_price_contract(null, FALSE, FALSE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT purchasing.list_price_contract_detail_discount(null));
PERFORM EXISTS (SELECT purchasing.list_price_contract_detail_taxes(null));
PERFORM EXISTS (SELECT purchasing.list_product_ap_invoice_search());
PERFORM EXISTS (SELECT purchasing.list_product_for_grn_search());
PERFORM EXISTS (SELECT purchasing.list_product_for_po_manual_report());
PERFORM EXISTS (SELECT purchasing.list_product_for_pr_lookup());
PERFORM EXISTS (SELECT purchasing.list_product_for_purchase_report_lookup());
PERFORM EXISTS (SELECT purchasing.list_product_po_close_report());
PERFORM EXISTS (SELECT purchasing.list_product_po_outstanding_report());
PERFORM EXISTS (SELECT purchasing.list_product_pr_outstanding_report());
PERFORM EXISTS (SELECT purchasing.list_product_preq_report_manual());
PERFORM EXISTS (SELECT purchasing.list_product_purchase_report());
PERFORM EXISTS (SELECT purchasing.list_product_purchase_return());
PERFORM EXISTS (SELECT purchasing.list_product_purchase_return_report_by_product());
PERFORM EXISTS (SELECT purchasing.list_product_qc_reject_report());
PERFORM EXISTS (SELECT purchasing.list_purchase_lite_detail_edit(null));
PERFORM EXISTS (SELECT purchasing.list_purchase_lite_edit(null, null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT purchasing.list_purchase_lite_settled_edit(null));
PERFORM EXISTS (SELECT purchasing.list_purchase_order_all(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null, FALSE, 0, null));
PERFORM EXISTS (SELECT purchasing.list_purchase_order_close(null, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT purchasing.list_purchase_order_close_detail(FALSE, CURRENT_DATE, CURRENT_DATE, null, null));
PERFORM EXISTS (SELECT purchasing.list_purchase_order_detail(null));
PERFORM EXISTS (SELECT purchasing.list_purchase_order_grn(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT purchasing.list_purchase_order_list(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE));
PERFORM EXISTS (SELECT purchasing.list_purchase_order_list_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE, null, FALSE, null));
PERFORM EXISTS (SELECT purchasing.list_purchase_order_list_item_detail(null));
PERFORM EXISTS (SELECT purchasing.list_purchase_order_list_termin(null));
PERFORM EXISTS (SELECT purchasing.list_purchase_order_manual_list(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE));
PERFORM EXISTS (SELECT purchasing.list_purchase_order_manual_list_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE, null, FALSE, null));
PERFORM EXISTS (SELECT purchasing.list_purchase_order_manual_list_item_detail(null));
PERFORM EXISTS (SELECT purchasing.list_purchase_order_manual_list_termin(null));
PERFORM EXISTS (SELECT purchasing.list_purchase_order_parent(CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT purchasing.list_purchase_order_report_product_lookup());
--PERFORM EXISTS (SELECT purchasing.list_purchase_planning(null, FALSE, CURRENT_DATE, CURRENT_DATE));
--PERFORM EXISTS (SELECT purchasing.list_purchase_planning_detail(null, null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT purchasing.list_purchase_report_product());
PERFORM EXISTS (SELECT purchasing.list_purchase_req_report_product_lookup());
PERFORM EXISTS (SELECT purchasing.list_purchase_request_all_n_sisa(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT purchasing.list_purchase_request_all_n_sisa(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT purchasing.list_purchase_request_close_by_instance(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT purchasing.list_purchase_request_manual(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT purchasing.list_purchase_request_manual_all_n_sisa(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.list_purchase_requisition(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE));
PERFORM EXISTS (SELECT purchasing.list_purchase_requisition_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT purchasing.list_purchase_requisition_detail_close_report(null, FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT purchasing.list_purchase_requisition_detail_close_report(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT purchasing.list_purchase_requisition_detail_edit(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT purchasing.list_purchase_requisition_detail_edit(null));
PERFORM EXISTS (SELECT purchasing.list_purchase_requisition_detail_manual(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT purchasing.list_purchase_requisition_detal_new(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT purchasing.list_purchase_requisition_list(null, null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT purchasing.list_purchase_requisition_list_edit(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT purchasing.list_purchase_requisition_manual(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE));
PERFORM EXISTS (SELECT purchasing.list_purchase_requisition_manual_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT purchasing.list_purchase_requisition_manual_list(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE));
PERFORM EXISTS (SELECT purchasing.list_purchase_requistion_detail_report(null));
PERFORM EXISTS (SELECT purchasing.list_purchase_return(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT purchasing.list_purchase_return_detail(null, null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT purchasing.list_purchase_return_for_debit_notes(null, null));
PERFORM EXISTS (SELECT purchasing.list_purchasing_requisition_close(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE));
PERFORM EXISTS (SELECT purchasing.list_qc_parameter(null, FALSE));
PERFORM EXISTS (SELECT purchasing.list_qc_parameter_archive(null));
PERFORM EXISTS (SELECT purchasing.list_qc_parameter_edit(null));
PERFORM EXISTS (SELECT purchasing.list_qc_report_detai(null, null));
PERFORM EXISTS (SELECT purchasing.list_qc_report_detail(null, null));
PERFORM EXISTS (SELECT purchasing.list_qc_report_detail2(null, null));
PERFORM EXISTS (SELECT purchasing.list_quality_control_check_report_analisis(null));
PERFORM EXISTS (SELECT purchasing.list_quality_control_check_report_detail(null));
PERFORM EXISTS (SELECT purchasing.list_quality_control_check_report_detail(null, null));
PERFORM EXISTS (SELECT purchasing.list_quality_control_check_report_detail2(null));
PERFORM EXISTS (SELECT purchasing.list_quality_control_check_report_detail2(null, null));
PERFORM EXISTS (SELECT purchasing.list_quality_control_check_report_parent(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT purchasing.list_quality_control_check_report_parent_by_instance(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT purchasing.list_quality_control_detail(null));
PERFORM EXISTS (SELECT purchasing.list_quality_control_list(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE));
PERFORM EXISTS (SELECT purchasing.list_quality_control_list_detail(null, null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT purchasing.list_quality_control_list_detail2(null));
PERFORM EXISTS (SELECT purchasing.list_quality_control_parameter_list(null));
PERFORM EXISTS (SELECT purchasing.list_quality_control_parent(FALSE, CURRENT_DATE, CURRENT_DATE, null, null));
PERFORM EXISTS (SELECT purchasing.list_supplier_ap_unbilled_report());
PERFORM EXISTS (SELECT purchasing.list_supplier_for_grn_search());
PERFORM EXISTS (SELECT purchasing.list_supplier_for_invoice_report());
PERFORM EXISTS (SELECT purchasing.list_supplier_for_po_lookup());
PERFORM EXISTS (SELECT purchasing.list_supplier_for_po_manual_report());
PERFORM EXISTS (SELECT purchasing.list_supplier_for_purchase_report_lookup());
PERFORM EXISTS (SELECT purchasing.list_supplier_for_purchase_report_report());
PERFORM EXISTS (SELECT purchasing.list_supplier_new());
PERFORM EXISTS (SELECT purchasing.list_supplier_po_close_report());
PERFORM EXISTS (SELECT purchasing.list_supplier_po_outstanding_report());
PERFORM EXISTS (SELECT purchasing.list_supplier_purchase_return_report());
PERFORM EXISTS (SELECT purchasing.list_supplier_purchase_return_report_by_product());
PERFORM EXISTS (SELECT purchasing.list_transaction_status());
PERFORM EXISTS (SELECT purchasing.list_transaction_type(null, FALSE));
PERFORM EXISTS (SELECT purchasing.list_transaction_type_archive(null));
PERFORM EXISTS (SELECT purchasing.list_unsettle_ap(null, null));
PERFORM EXISTS (SELECT purchasing.list_unsettle_purchase_lite(null, null));
PERFORM EXISTS (SELECT purchasing.list_vendor_suply(null, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT purchasing.list_vendor_suply_all(null, FALSE, null));
PERFORM EXISTS (SELECT purchasing.list_warehouse_for_ap_invoice_beginning(null));
PERFORM EXISTS (SELECT purchasing.open_ap_invoice(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT purchasing.open_ap_invoice_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT purchasing.open_close_ap_invoice(null, FALSE));
PERFORM EXISTS (SELECT purchasing.open_close_good_received_notes(null, FALSE));
PERFORM EXISTS (SELECT purchasing.open_close_purchase_order(null, FALSE));
PERFORM EXISTS (SELECT purchasing.open_close_purchase_order_manual(null, FALSE));
PERFORM EXISTS (SELECT purchasing.open_close_purchase_request(null, FALSE));
PERFORM EXISTS (SELECT purchasing.open_close_purchase_request_manual(null, FALSE));
PERFORM EXISTS (SELECT purchasing.open_close_purchase_return(null, FALSE));
PERFORM EXISTS (SELECT purchasing.open_close_quality_control_notes(null, FALSE));
PERFORM EXISTS (SELECT purchasing.open_list_ap_invoice_beginning(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT purchasing.open_list_po_for_purchase_advance(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT purchasing.open_purchase_grn(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT purchasing.open_purchase_grn_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT purchasing.open_purchase_lite(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT purchasing.open_purchase_lite_detail(null));
PERFORM EXISTS (SELECT purchasing.open_purchase_lite_settled(null));
PERFORM EXISTS (SELECT purchasing.open_purchase_order(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT purchasing.open_purchase_order_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT purchasing.open_purchase_pom(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT purchasing.open_purchase_pom_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT purchasing.open_purchase_prm(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT purchasing.open_purchase_prm_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT purchasing.open_purchase_qcc(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT purchasing.open_purchase_qcc_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT purchasing.open_purchase_request(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT purchasing.open_purchase_requisition_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT purchasing.open_purchase_return(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT purchasing.open_purchase_return_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT purchasing.po_lastbuying(null, null));
PERFORM EXISTS (SELECT purchasing.print_ap_aging_report_detail(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT purchasing.print_ap_aging_report_summary(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.print_ap_invoice_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.print_ap_unbilled_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.print_grn_monitoring_report(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT purchasing.print_grn_monitoring_report_by_instance(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT purchasing.print_grn_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.print_grn_report_by_instance(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT purchasing.print_purchase_order_close(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT purchasing.print_purchase_order_close_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.print_purchase_order_close_report_by_instance(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT purchasing.print_purchase_order_manual_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.print_purchase_order_manual_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT purchasing.print_purchase_order_manual_report_by_instance(null, null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT purchasing.print_purchase_order_outsanding_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT purchasing.print_purchase_order_outstanding_report_by_instance(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT purchasing.print_purchase_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.print_purchase_return_by_product(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.print_purchase_return_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.print_purchase_return_report_by_instance(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT purchasing.print_qc_reject_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.print_qc_reject_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT purchasing.print_qc_reject_report_by_instance(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null, null));
PERFORM EXISTS (SELECT purchasing.purchase_last_buying(null, null));
PERFORM EXISTS (SELECT purchasing.purchase_lite_add_batch(null));
PERFORM EXISTS (SELECT purchasing.purchase_lite_add_batch_by_product(null));
PERFORM EXISTS (SELECT purchasing.purchase_lite_list(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.purchase_lite_update_stock(null, null, null));
PERFORM EXISTS (SELECT purchasing.purchase_order_termin_default(null, null, 0.0));
PERFORM EXISTS (SELECT purchasing.purchase_request_close_list_detail(null, null, FALSE, CURRENT_DATE, CURRENT_DATE, 0, 0));
PERFORM EXISTS (SELECT purchasing.purchase_request_close_list_parent(null, null, null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT purchasing.purchase_return_report_detail(null));
PERFORM EXISTS (SELECT purchasing.purchase_return_update_stock(null, null, null));
PERFORM EXISTS (SELECT purchasing.qc_update_stock(null, null, CURRENT_DATE, null));
PERFORM EXISTS (SELECT purchasing.remove_item_discount_edit(null));
PERFORM EXISTS (SELECT purchasing.remove_price_contract_detail_discount(null, 0, 0));
PERFORM EXISTS (SELECT purchasing.remove_price_contract_detail_taxes(null, 0, 0));
PERFORM EXISTS (SELECT purchasing.report_ap_invoice_report_detail(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null, FALSE, 0));
PERFORM EXISTS (SELECT purchasing.report_ap_invoice_report_detail_by_instance(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null, FALSE, 0, null));
PERFORM EXISTS (SELECT purchasing.report_ap_invoice_report_summary(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, 0));
PERFORM EXISTS (SELECT purchasing.report_ap_invoice_report_summary_by_instance(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, 0, null));
PERFORM EXISTS (SELECT purchasing.report_apinvoice_detail_generate(null));
PERFORM EXISTS (SELECT purchasing.report_apinvoice_generate(null));
PERFORM EXISTS (SELECT purchasing.report_grn_detail_new());
PERFORM EXISTS (SELECT purchasing.report_grn_list_new(null));
PERFORM EXISTS (SELECT purchasing.report_list_ap_invoice_beginning_list(null));
PERFORM EXISTS (SELECT purchasing.report_list_grn(null));
PERFORM EXISTS (SELECT purchasing.report_list_grn_detail(null));
PERFORM EXISTS (SELECT purchasing.report_list_grn_detail_analysis_generate(null));
PERFORM EXISTS (SELECT purchasing.report_list_grn_detail_generate(null));
PERFORM EXISTS (SELECT purchasing.report_list_grn_generate(null));
PERFORM EXISTS (SELECT purchasing.report_po(null));
PERFORM EXISTS (SELECT purchasing.report_po_detail(null));
PERFORM EXISTS (SELECT purchasing.report_po_detail_generate(null));
PERFORM EXISTS (SELECT purchasing.report_po_detail_generate1(null));
PERFORM EXISTS (SELECT purchasing.report_po_generate(null, 0.0));
PERFORM EXISTS (SELECT purchasing.report_po_generate_new(null, null));
PERFORM EXISTS (SELECT purchasing.report_po_termin_generate(null));
PERFORM EXISTS (SELECT purchasing.report_pr(null));
PERFORM EXISTS (SELECT purchasing.report_pr_detail(null));
PERFORM EXISTS (SELECT purchasing.report_pr_detail_report(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT purchasing.report_preturn(null));
PERFORM EXISTS (SELECT purchasing.report_preturn_detail(null));
PERFORM EXISTS (SELECT purchasing.report_purchase_lite_detail_generate(null));
PERFORM EXISTS (SELECT purchasing.report_purchase_lite_generate(null));
PERFORM EXISTS (SELECT purchasing.report_purchase_lite_generate_list(null));
PERFORM EXISTS (SELECT purchasing.report_purchase_order(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.report_purchase_order_by_instance(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT purchasing.report_purchase_order_list_item_detail_new());
PERFORM EXISTS (SELECT purchasing.report_purchase_order_list_new(null));
PERFORM EXISTS (SELECT purchasing.report_purchase_order_list_termin_new());
PERFORM EXISTS (SELECT purchasing.report_purchase_order_manual(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT purchasing.report_purchase_order_manual_list(null));
PERFORM EXISTS (SELECT purchasing.report_purchase_order_manual_list_item_detail(null));
PERFORM EXISTS (SELECT purchasing.report_purchase_order_outsanding(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT purchasing.report_purchase_request_by_product_by_instance_print(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.report_purchase_request_manual_by_instance(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.report_purchase_request_manual_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT purchasing.report_purchase_request_manual_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.report_purchase_request_report_print(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT purchasing.report_purchase_requisition(null));
PERFORM EXISTS (SELECT purchasing.report_purchase_requisition_close_list(null));
PERFORM EXISTS (SELECT purchasing.report_purchase_requisition_close_list_detail(null));
PERFORM EXISTS (SELECT purchasing.report_purchase_requisition_detail(null));
PERFORM EXISTS (SELECT purchasing.report_purchase_requisition_detail1(null));
PERFORM EXISTS (SELECT purchasing.report_purchase_requisition_detail_generate(null));
PERFORM EXISTS (SELECT purchasing.report_purchase_requisition_detail_generate_manual(null));
PERFORM EXISTS (SELECT purchasing.report_purchase_requisition_detail_generate_new(null, null));
PERFORM EXISTS (SELECT purchasing.report_purchase_requisition_detal(null));
PERFORM EXISTS (SELECT purchasing.report_purchase_requisition_generate(null));
PERFORM EXISTS (SELECT purchasing.report_purchase_requisition_generate_manual(null));
PERFORM EXISTS (SELECT purchasing.report_purchase_requisition_list_(null));
PERFORM EXISTS (SELECT purchasing.report_purchase_requisition_manual_detail(null));
PERFORM EXISTS (SELECT purchasing.report_purchase_requisition_manual_generate(null));
PERFORM EXISTS (SELECT purchasing.report_purchase_return_detail(null));
PERFORM EXISTS (SELECT purchasing.report_purchase_return_list(null));
PERFORM EXISTS (SELECT purchasing.report_purchase_return_parent(null));
PERFORM EXISTS (SELECT purchasing.report_purchase_return_total(null));
PERFORM EXISTS (SELECT purchasing.report_quality_control_check_detail(null, null));
PERFORM EXISTS (SELECT purchasing.report_quality_control_check_detail(null));
PERFORM EXISTS (SELECT purchasing.report_quality_control_check_detail_parameter(null));
PERFORM EXISTS (SELECT purchasing.report_quality_control_check_parent(null));
PERFORM EXISTS (SELECT purchasing.report_quality_control_generate(null));
PERFORM EXISTS (SELECT purchasing.report_quality_control_list_detail_generate());
PERFORM EXISTS (SELECT purchasing.report_quality_control_parameter_list_generate());
PERFORM EXISTS (SELECT purchasing.report_request_outstanding_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT purchasing.report_request_outstanding_report_by_instance(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.report_request_report_by_product_print(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT purchasing.set_approved_by(null, null, null));
PERFORM EXISTS (SELECT purchasing.set_approved_purchase_lite(null, null, null));
PERFORM EXISTS (SELECT purchasing.set_ar_invoice_detail(null, null, null, null));
PERFORM EXISTS (SELECT purchasing.set_new_ap_beginning(CURRENT_DATE, null, null, null, 0.0, null, null, null, null, null, CURRENT_DATE, null, null, null));
PERFORM EXISTS (SELECT purchasing.set_new_goods_received_notes(null, null, null, null, null, null, null, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT purchasing.set_new_master_transaction_type(null, null, FALSE, null));
PERFORM EXISTS (SELECT purchasing.set_new_price_contract(null, null, null, null, null, CURRENT_DATE, FALSE, 0, FALSE, CURRENT_DATE, null, 0));
PERFORM EXISTS (SELECT purchasing.set_new_purchase_invoice1(null, CURRENT_DATE, null, null, null, null, null, null, null, null, null, null, null, 0.0, 0.0, 0.0, 0.0, 0.0, null, null, null, 0.0, null));
PERFORM EXISTS (SELECT purchasing.set_new_purchase_invoice1_new(null, CURRENT_DATE, null, null, null, null, null, null, null, null, null, null, null, 0.0, 0.0, 0.0, 0.0, 0.0, null, null, null, null, 0.0));
PERFORM EXISTS (SELECT purchasing.set_new_purchase_lite(null, CURRENT_DATE, null, null, null, null, null, null, null, 0, null, null, null, null, null, null, null, 0.0, 0.0, 0.0, 0.0, 0.0, null, null, null, null, 0.0));
PERFORM EXISTS (SELECT purchasing.set_new_purchase_order1(CURRENT_DATE, null, null, null, null, 0.0, null, null, null, CURRENT_DATE, 0.0, 0.0, 0.0, 0.0, 0.0, null, 0.0, null));
PERFORM EXISTS (SELECT purchasing.set_new_purchase_order1_new(CURRENT_DATE, null, null, null, null, 0.0, null, null, null, null, CURRENT_DATE, 0.0, 0.0, 0.0, 0.0, 0.0, null, null, null));
PERFORM EXISTS (SELECT purchasing.set_new_purchase_order_manual_edit(CURRENT_DATE, null, null, null, null, 0.0, null, null, null, null, CURRENT_DATE, 0.0, 0.0, 0.0, 0.0, 0.0, null, null));
PERFORM EXISTS (SELECT purchasing.set_new_purchase_price_contract_manual_edit(CURRENT_DATE, null, null, null, null, null, null, null, FALSE, null, null, null, null, null, null, null, CURRENT_DATE));
PERFORM EXISTS (SELECT purchasing.set_new_purchase_requisition(CURRENT_DATE, null, null, null, null, null, null, null, null));
PERFORM EXISTS (SELECT purchasing.set_new_purchase_return(null, CURRENT_DATE, null, null, null, null, null));
PERFORM EXISTS (SELECT purchasing.set_new_purchase_return_journal(null));
PERFORM EXISTS (SELECT purchasing.set_new_qc_parameter(null, null, null, null, FALSE));
PERFORM EXISTS (SELECT purchasing.set_new_quality_control(null, CURRENT_DATE, null, null));
PERFORM EXISTS (SELECT purchasing.set_new_quality_control_category(null, null, null, FALSE));
PERFORM EXISTS (SELECT purchasing.set_new_update_qc_parameter(null, null, FALSE, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT purchasing.set_quality_check_control_detail(null, null));
PERFORM EXISTS (SELECT purchasing.update_is_enabled(null, null, null, FALSE));
PERFORM EXISTS (SELECT purchasing.update_list_dst_po1(null, null, null));
PERFORM EXISTS (SELECT purchasing.update_old_qc_parameter(null));
PERFORM EXISTS (SELECT purchasing.update_old_transaction_type(null));
PERFORM EXISTS (SELECT purchasing.update_purchase_order_is_used_false(null));
PERFORM EXISTS (SELECT purchasing.update_purchase_requisition_is_used_false(null));
PERFORM EXISTS (SELECT purchasing.update_qty_ordered_pch_requisition(null));
PERFORM EXISTS (SELECT purchasing.update_transaction_status(null, null, 0));
PERFORM EXISTS (SELECT purchasing.update_transaction_status_grn(null));
PERFORM EXISTS (SELECT purchasing.update_transaction_status_pr(null));
PERFORM EXISTS (SELECT purchasing.validasi_last_buying_price_and_lock_price_pl(null));
PERFORM EXISTS (SELECT purchasing.validasi_last_buying_price_dan_lock_price(null));
PERFORM EXISTS (SELECT purchasing.validate_discount_exists_purchase_price_contract(null));
PERFORM EXISTS (SELECT purchasing.validate_price_contract_detail_net_price(null));
PERFORM EXISTS (SELECT purchasing.validate_price_contract_detail_net_price_1(null));
PERFORM EXISTS (SELECT purchasing.validate_purchase_order_unit_price(null));
PERFORM EXISTS (SELECT purchasing.validate_qc_detail_parameter(null));
PERFORM EXISTS (SELECT purchasing.validate_qc_param_name(null));
PERFORM EXISTS (SELECT purchasing.validate_qc_parameter_edit_name(null, null));
PERFORM EXISTS (SELECT purchasing.validate_qc_parameter_name(null));
PERFORM EXISTS (SELECT purchasing.validate_qc_parameter_name_archive(null));
PERFORM EXISTS (SELECT purchasing.validate_transaction_type_archived(null));
PERFORM EXISTS (SELECT purchasing.validate_transaction_type_edit(null, null));
PERFORM EXISTS (SELECT purchasing.validate_transaction_type_name(null));
END;