BEGIN
PERFORM EXISTS (SELECT finance.auto_generate_period());
PERFORM EXISTS (SELECT finance.cancel_ap_beginning_to_edit(null, null));
PERFORM EXISTS (SELECT finance.cancel_ar_beginning_to_edit(null, null));
PERFORM EXISTS (SELECT finance.cancel_cash_payment_to_edit(null, null));
PERFORM EXISTS (SELECT finance.cancel_cash_receipt_to_edit(null, null));
PERFORM EXISTS (SELECT finance.cancel_cash_transfer_to_edit(null, null));
PERFORM EXISTS (SELECT finance.cancel_notes_payable_to_edit(null, null));
PERFORM EXISTS (SELECT finance.cancel_purchase_advance_to_edit(null, null));
PERFORM EXISTS (SELECT finance.cancel_sales_advance_to_edit(null, null));
PERFORM EXISTS (SELECT finance.cash_payment_detail_for_list(null, null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null, null));
PERFORM EXISTS (SELECT finance.cash_payment_detail_journal_for_list(null, null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null, null));
PERFORM EXISTS (SELECT finance.cash_payment_detail_report(null));
PERFORM EXISTS (SELECT finance.cash_payment_for_list(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null, null, FALSE, 0, null));
PERFORM EXISTS (SELECT finance.cash_payment_for_list_non_ap(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null, null, FALSE, FALSE, FALSE, 0, null));
PERFORM EXISTS (SELECT finance.cash_payment_journal_entry_report());
PERFORM EXISTS (SELECT finance.cash_payment_report(null));
PERFORM EXISTS (SELECT finance.cash_payment_report_edit(null));
PERFORM EXISTS (SELECT finance.cash_payment_set_journal(null, FALSE));
PERFORM EXISTS (SELECT finance.cash_receipt_detail_ar(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT finance.cash_receipt_detail_ar_report(null));
PERFORM EXISTS (SELECT finance.cash_receipt_detail_ar_report_generate(null));
PERFORM EXISTS (SELECT finance.cash_receipt_journal_detail(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT finance.cash_receipt_journal_detail_report(null));
PERFORM EXISTS (SELECT finance.cash_receipt_journal_detail_report_generate(null));
PERFORM EXISTS (SELECT finance.cash_receipt_report(null));
PERFORM EXISTS (SELECT finance.cash_receipt_report_generate(null));
PERFORM EXISTS (SELECT finance.cash_receipt_set_journal(null, FALSE));
PERFORM EXISTS (SELECT finance.cash_transfer_edit_update_parent_old_data(null, null, 0.0));
PERFORM EXISTS (SELECT finance.cek_transaction_name_cash_payment(null));
PERFORM EXISTS (SELECT finance.cencel_notes_recivebel_to_edit(null, null));
PERFORM EXISTS (SELECT finance.check_ap_invoice_can_used_cash_payment(null, null));
PERFORM EXISTS (SELECT finance.check_ap_pl_can_used_purchase_return(null, null));
PERFORM EXISTS (SELECT finance.check_ar_invoice_can_used_cash_receipt(null));
PERFORM EXISTS (SELECT finance.completing_purchase_advance_transaction(null));
PERFORM EXISTS (SELECT finance.copy_ap_beginning_to_edit(null));
PERFORM EXISTS (SELECT finance.copy_ar_beginning_to_edit(null));
PERFORM EXISTS (SELECT finance.copy_cash_payment_to_edit(null));
PERFORM EXISTS (SELECT finance.copy_cash_receipt_to_edit(null));
PERFORM EXISTS (SELECT finance.copy_cash_transfer_to_edit(null));
PERFORM EXISTS (SELECT finance.copy_notes_payable_to_edit(null));
PERFORM EXISTS (SELECT finance.copy_notes_reciveble_to_edit(null));
PERFORM EXISTS (SELECT finance.copy_purchase_advance_to_edit(null));
PERFORM EXISTS (SELECT finance.expenses_realization_set_journal(null));
PERFORM EXISTS (SELECT finance.get_active_period_and_pricelist(null));
PERFORM EXISTS (SELECT finance.get_cash_bank_ledger_detail_report_test(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT finance.get_cash_bank_ledger_parent(CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT finance.get_cash_bank_ledger_report(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT finance.get_cash_bank_ledger_report(null, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT finance.get_cash_bank_movement_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT finance.get_cash_bank_movement_report(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT finance.get_cash_payment_detail_json(null));
PERFORM EXISTS (SELECT finance.get_cash_payment_journal_entries_json(null));
PERFORM EXISTS (SELECT finance.get_cash_payment_json(null));
PERFORM EXISTS (SELECT finance.get_cash_payment_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT finance.get_cash_receipt_detail_ar_json(null));
PERFORM EXISTS (SELECT finance.get_cash_receipt_detail_json(null));
PERFORM EXISTS (SELECT finance.get_cash_receipt_json(null));
PERFORM EXISTS (SELECT finance.get_cash_receipt_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT finance.get_cash_transfer_json(null));
PERFORM EXISTS (SELECT finance.get_cash_transfer_report(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT finance.get_cost_center(null));
PERFORM EXISTS (SELECT finance.get_cost_center_code(null));
PERFORM EXISTS (SELECT finance.get_cost_center_json(null));
PERFORM EXISTS (SELECT finance.get_cost_center_with_instance(null));
PERFORM EXISTS (SELECT finance.get_currency());
PERFORM EXISTS (SELECT finance.get_currency_all(null));
PERFORM EXISTS (SELECT finance.get_currency_default());
PERFORM EXISTS (SELECT finance.get_currency_json(null));
PERFORM EXISTS (SELECT finance.get_current_balance(CURRENT_DATE, null));
PERFORM EXISTS (SELECT finance.get_current_balance_for_edit(CURRENT_DATE, null, null));
PERFORM EXISTS (SELECT finance.get_current_level_cost_center(null));
PERFORM EXISTS (SELECT finance.get_current_period(null));
PERFORM EXISTS (SELECT finance.get_current_period_by_parent_instance(null));
PERFORM EXISTS (SELECT finance.get_default_currency_id(null));
PERFORM EXISTS (SELECT finance.get_expense_realization_detail_json(null));
PERFORM EXISTS (SELECT finance.get_expense_realization_journal_detail_json(null));
PERFORM EXISTS (SELECT finance.get_expense_realization_json(null));
PERFORM EXISTS (SELECT finance.get_expenses_by_cost_center_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT finance.get_new_update_cost_center(null));
PERFORM EXISTS (SELECT finance.get_new_update_periode(null));
PERFORM EXISTS (SELECT finance.get_new_update_taxes(null));
PERFORM EXISTS (SELECT finance.get_new_update_terms_payment(null));
PERFORM EXISTS (SELECT finance.get_notes_payable_report(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT finance.get_notes_receivable_report(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT finance.get_operational_adv_payment_detail_json(null));
PERFORM EXISTS (SELECT finance.get_operational_adv_payment_json(null));
PERFORM EXISTS (SELECT finance.get_operational_expense_payment_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT finance.get_operational_expense_payment_report_new(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT finance.get_operational_expense_realization_list_report_test(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT finance.get_parent_cost_center(null));
PERFORM EXISTS (SELECT finance.get_payment_method());
PERFORM EXISTS (SELECT finance.get_payment_term());
PERFORM EXISTS (SELECT finance.get_payment_term_credit());
PERFORM EXISTS (SELECT finance.get_payment_term_with_gateway(null));
PERFORM EXISTS (SELECT finance.get_period(null));
PERFORM EXISTS (SELECT finance.get_period_by_pareto_outlet(null));
PERFORM EXISTS (SELECT finance.get_periode());
PERFORM EXISTS (SELECT finance.get_periode_json(null));
PERFORM EXISTS (SELECT finance.get_purchase_advance_detail_json(null));
PERFORM EXISTS (SELECT finance.get_purchase_advance_json(null));
PERFORM EXISTS (SELECT finance.get_purchase_advance_payment_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT finance.get_supplier_current_balance(CURRENT_DATE, null));
PERFORM EXISTS (SELECT finance.get_tax_type_json(null));
PERFORM EXISTS (SELECT finance.get_taxes());
PERFORM EXISTS (SELECT finance.get_taxes_all());
PERFORM EXISTS (SELECT finance.get_taxes_json(null));
PERFORM EXISTS (SELECT finance.get_terms_of_payment_details_json(null));
PERFORM EXISTS (SELECT finance.get_terms_of_payment_json(null));
PERFORM EXISTS (SELECT finance.get_top());
PERFORM EXISTS (SELECT finance.get_top_(null));
PERFORM EXISTS (SELECT finance.get_top_max(null));
PERFORM EXISTS (SELECT finance.get_total_pick_cash_receipt_detail_ar(null, null));
PERFORM EXISTS (SELECT finance.get_view_cost_center_json(null));
PERFORM EXISTS (SELECT finance.get_view_currency_json(null));
PERFORM EXISTS (SELECT finance.get_view_periode_json(null));
PERFORM EXISTS (SELECT finance.get_view_tax_type_json(null));
PERFORM EXISTS (SELECT finance.get_view_taxes_json(null));
PERFORM EXISTS (SELECT finance.get_view_terms_of_payment_details_json(null));
PERFORM EXISTS (SELECT finance.get_view_terms_of_payment_json(null));
PERFORM EXISTS (SELECT finance.insert_cash_payment(null, null));
PERFORM EXISTS (SELECT finance.insert_cash_payment_ap_begining_multiple(null, null));
PERFORM EXISTS (SELECT finance.insert_cash_payment_detail(null, null));
PERFORM EXISTS (SELECT finance.insert_cash_payment_detail_ap_multiple(null, null));
PERFORM EXISTS (SELECT finance.insert_cash_payment_detail_multiple(null, null));
PERFORM EXISTS (SELECT finance.insert_cash_payment_edit(null));
PERFORM EXISTS (SELECT finance.insert_cash_payment_multiple(null, null));
PERFORM EXISTS (SELECT finance.insert_cash_payment_purchase_lite_multiple(null, null));
PERFORM EXISTS (SELECT finance.insert_cash_payment_to_journal(null));
PERFORM EXISTS (SELECT finance.insert_cash_receipt_detail_ar(null, null));
PERFORM EXISTS (SELECT finance.insert_edit_cash_receipt(null));
PERFORM EXISTS (SELECT finance.insert_edit_expenses_realization(null));
PERFORM EXISTS (SELECT finance.insert_edit_notes_payable(null));
PERFORM EXISTS (SELECT finance.insert_edit_notes_receivable(null));
PERFORM EXISTS (SELECT finance.insert_edit_operational_advance_payment(null));
PERFORM EXISTS (SELECT finance.insert_edit_sales_advance(null));
PERFORM EXISTS (SELECT finance.insert_operational_adv_payment_generate(null, null));
PERFORM EXISTS (SELECT finance.insert_purchase_advance_detail(null, null));
PERFORM EXISTS (SELECT finance.insert_purchase_advance_generate(null, null));
PERFORM EXISTS (SELECT finance.insert_taxes(null, null, null, 0.0, null, null, null));
PERFORM EXISTS (SELECT finance.list__slu_account_for_cash_receipt());
PERFORM EXISTS (SELECT finance.list_adv_unsettle(null, null));
PERFORM EXISTS (SELECT finance.list_ap_invoice(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT finance.list_ar_for_cr(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT finance.list_bank_cash_account_cash_receipt());
PERFORM EXISTS (SELECT finance.list_cash_account_for_cash_payment());
PERFORM EXISTS (SELECT finance.list_cash_payment(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, FALSE, null, null));
PERFORM EXISTS (SELECT finance.list_cash_payment_giro(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT finance.list_cash_receipt(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, 0));
PERFORM EXISTS (SELECT finance.list_cash_receipt_for_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT finance.list_cash_receipt_list_detail(null));
PERFORM EXISTS (SELECT finance.list_cash_receipt_list_detail_journal_entry(null));
PERFORM EXISTS (SELECT finance.list_cash_receipt_list_parent(FALSE, CURRENT_DATE, CURRENT_DATE, null, null, FALSE, null, null, null, null, FALSE, 0, null));
PERFORM EXISTS (SELECT finance.list_cash_receipt_list_parent_non_ar(FALSE, CURRENT_DATE, CURRENT_DATE, null, null, FALSE, null, null, null, null, FALSE, 0, null));
PERFORM EXISTS (SELECT finance.list_cash_transfer(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT finance.list_cash_transfer_list(FALSE, CURRENT_DATE, CURRENT_DATE, null, FALSE, null, null, null, null));
PERFORM EXISTS (SELECT finance.list_cash_transfer_new(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT finance.list_cash_transfer_parent(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT finance.list_cost_center(null, FALSE, null));
PERFORM EXISTS (SELECT finance.list_cost_center_archive(null, null));
PERFORM EXISTS (SELECT finance.list_costcenter_no_code(null));
PERFORM EXISTS (SELECT finance.list_currency(null));
PERFORM EXISTS (SELECT finance.list_currency_archive(null));
PERFORM EXISTS (SELECT finance.list_expenses_realization_list(FALSE, CURRENT_DATE, CURRENT_DATE, null, null));
PERFORM EXISTS (SELECT finance.list_expenses_realization_list_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT finance.list_expenses_realization_list_journal_entry(null));
PERFORM EXISTS (SELECT finance.list_expenses_realization_list_parent(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT finance.list_expenses_realization_list_parent(FALSE, CURRENT_DATE, CURRENT_DATE, null, null, null));
PERFORM EXISTS (SELECT finance.list_notes_payable_edit(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT finance.list_notes_payable_edit_detail(null));
PERFORM EXISTS (SELECT finance.list_notes_payable_in_open_finance(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT finance.list_notes_payable_list(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT finance.list_notes_payable_list(null, null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null, null));
PERFORM EXISTS (SELECT finance.list_notes_payable_list_detail(null));
PERFORM EXISTS (SELECT finance.list_notes_payable_list_edit(null, null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT finance.list_notes_payable_list_journal(null));
PERFORM EXISTS (SELECT finance.list_notes_receivable_edit(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, 0, null));
PERFORM EXISTS (SELECT finance.list_notes_receivable_list(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT finance.list_notes_receivable_list_detail(null));
PERFORM EXISTS (SELECT finance.list_notes_receivable_list_journal(null));
PERFORM EXISTS (SELECT finance.list_of_all_period(null));
PERFORM EXISTS (SELECT finance.list_of_cash_payment_detail(null));
PERFORM EXISTS (SELECT finance.list_of_cash_payment_edit(null, FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT finance.list_of_cash_payment_edit_detail(null));
PERFORM EXISTS (SELECT finance.list_of_cash_payment_journal_entries(null));
PERFORM EXISTS (SELECT finance.list_of_cash_receipt_edit_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT finance.list_of_cash_receipt_edit_test(null, FALSE, CURRENT_DATE, CURRENT_DATE, null, null, FALSE, null));
PERFORM EXISTS (SELECT finance.list_of_cash_receipt_journal_entries(null));
PERFORM EXISTS (SELECT finance.list_of_cost_center(null));
PERFORM EXISTS (SELECT finance.list_of_currency(null));
PERFORM EXISTS (SELECT finance.list_of_current_future_period(null));
PERFORM EXISTS (SELECT finance.list_of_current_past_period(null));
PERFORM EXISTS (SELECT finance.list_of_purchase_advance(null, FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT finance.list_of_purchase_advance_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT finance.list_of_purchase_advance_list(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT finance.list_of_purchase_advance_payment_edit(FALSE, CURRENT_DATE, CURRENT_DATE, null, null));
PERFORM EXISTS (SELECT finance.list_operational_adv_payment(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT finance.list_operational_adv_payment_for_exp(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT finance.list_operational_adv_payment_list(FALSE, CURRENT_DATE, CURRENT_DATE, null, null, FALSE, null, null));
PERFORM EXISTS (SELECT finance.list_operational_adv_payment_list(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null, null));
PERFORM EXISTS (SELECT finance.list_payment_term(null, FALSE));
PERFORM EXISTS (SELECT finance.list_payment_term_popup(null));
PERFORM EXISTS (SELECT finance.list_payment_term_popup_new());
PERFORM EXISTS (SELECT finance.list_payment_type_for_cash_payment());
PERFORM EXISTS (SELECT finance.list_periode(null, FALSE));
PERFORM EXISTS (SELECT finance.list_periode_archive(null));
PERFORM EXISTS (SELECT finance.list_purchase_adv_edit_deposit(FALSE, CURRENT_DATE, CURRENT_DATE, null, null));
PERFORM EXISTS (SELECT finance.list_purchase_advance_list(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT finance.list_purchase_advance_list_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT finance.list_purchase_advance_list_detail2(null));
PERFORM EXISTS (SELECT finance.list_sales_advance_detail(null));
PERFORM EXISTS (SELECT finance.list_sales_advance_list(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT finance.list_sales_advance_list_detail(null));
PERFORM EXISTS (SELECT finance.list_slu_customer_for_cash_receipt());
PERFORM EXISTS (SELECT finance.list_stock_in(0, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT finance.list_supplier_for_cash_payment());
PERFORM EXISTS (SELECT finance.list_supplier_for_cash_payment_list());
PERFORM EXISTS (SELECT finance.list_taxes(null));
PERFORM EXISTS (SELECT finance.list_taxes_archive(null));
PERFORM EXISTS (SELECT finance.list_terms_payment_archive(null));
PERFORM EXISTS (SELECT finance.lookup_cost_center());
PERFORM EXISTS (SELECT finance.note_payable_set_journal(null, FALSE));
PERFORM EXISTS (SELECT finance.note_received_set_journal(null, FALSE));
PERFORM EXISTS (SELECT finance.notes_payable_edit_update_parent_old_data(null, null));
PERFORM EXISTS (SELECT finance.open_cash_payment_for_list(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT finance.open_cash_receipt_detail_ar(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT finance.open_close_ap_beginning(null, FALSE));
PERFORM EXISTS (SELECT finance.open_close_ar_beginning(null, FALSE));
PERFORM EXISTS (SELECT finance.open_close_cash_transfer(null, FALSE));
PERFORM EXISTS (SELECT finance.open_close_operational_advance(null, FALSE));
PERFORM EXISTS (SELECT finance.open_close_purchase_advance(null, FALSE));
PERFORM EXISTS (SELECT finance.open_close_sales_advance(null, FALSE));
PERFORM EXISTS (SELECT finance.open_expense_realization(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT finance.open_expense_realization_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT finance.open_expense_realization_journal_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT finance.open_list_ap_invoice(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT finance.open_list_ap_invoice(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null, null));
PERFORM EXISTS (SELECT finance.open_list_ap_invoice_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT finance.open_list_ap_invoice_journal_detail(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT finance.open_list_ap_invoice_journal_entry(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT finance.open_list_ar_for_cr(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT finance.open_list_ar_for_cr_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT finance.open_list_ar_for_cr_journal_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT finance.open_list_cash_payment_giro(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT finance.open_list_cash_payment_giro_detail(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT finance.open_list_cash_payment_giro_journal_detail(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT finance.open_list_cash_receipt(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, 0));
PERFORM EXISTS (SELECT finance.open_list_cash_receipt_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, 0));
PERFORM EXISTS (SELECT finance.open_list_cash_receipt_journal_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT finance.open_list_cash_receipt_parent(FALSE, CURRENT_DATE, CURRENT_DATE, null, null, FALSE, null, null, null, null));
PERFORM EXISTS (SELECT finance.open_list_cash_transfer(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT finance.open_list_notes_receivable_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT finance.open_list_notes_receivable_journal_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT finance.open_list_operational_adv_payment(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT finance.open_list_operational_adv_payment_for_exp(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT finance.open_list_po_for_purchase_advance_detail(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT finance.open_list_po_for_purchase_advance_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT finance.operational_advance_payment_set_journal(null));
PERFORM EXISTS (SELECT finance."pop_up_Payment_term"(null));
PERFORM EXISTS (SELECT finance.print_cash_bank_ledger_detail_report(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT finance.print_cash_bank_ledger_report(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT finance.print_cash_bank_movement_report(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT finance.print_cash_payment_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT finance.print_cash_receipt_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT finance.print_cash_transfer_report(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT finance.print_expenses_by_cost_center_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT finance.print_list_cash_transfer_list(null, null));
PERFORM EXISTS (SELECT finance.print_list_sales_advance_detail(null));
PERFORM EXISTS (SELECT finance.print_list_sales_advance_list(null));
PERFORM EXISTS (SELECT finance.print_notes_payable_list(null, null));
PERFORM EXISTS (SELECT finance.print_notes_payable_list_detail());
PERFORM EXISTS (SELECT finance.print_notes_payable_list_journal());
PERFORM EXISTS (SELECT finance.print_notes_payable_report(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT finance.print_notes_receivable_list(null, null));
PERFORM EXISTS (SELECT finance.print_notes_receivable_list_detail());
PERFORM EXISTS (SELECT finance.print_notes_receivable_list_journal());
PERFORM EXISTS (SELECT finance.print_notes_receivable_report(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT finance.print_operational_expense_payment_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT finance.print_operational_expense_realization_list_report_test(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT finance.print_purchase_advance_payment_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT finance.remove_cash_payment(null));
PERFORM EXISTS (SELECT finance.report_cash_payment_detail_for_list(null));
PERFORM EXISTS (SELECT finance.report_cash_payment_for_list(null));
PERFORM EXISTS (SELECT finance.report_cash_payment_generate(null));
PERFORM EXISTS (SELECT finance.report_cash_payment_generate_detail_ap(null));
PERFORM EXISTS (SELECT finance.report_cash_payment_generate_detail_journal(null));
PERFORM EXISTS (SELECT finance.report_cash_payment_journal_entry_for_list(null));
PERFORM EXISTS (SELECT finance.report_cash_receipt_list_detail(null));
PERFORM EXISTS (SELECT finance.report_cash_receipt_list_detail_journal(null));
PERFORM EXISTS (SELECT finance.report_cash_receipt_list_parent(null));
PERFORM EXISTS (SELECT finance.report_expenses_realization_list_parent(null, null));
PERFORM EXISTS (SELECT finance.report_list_expenses_realization_list_detail(null));
PERFORM EXISTS (SELECT finance.report_list_expenses_realization_list_journal_entry(null));
PERFORM EXISTS (SELECT finance.report_operational_adv_payment_list(null));
PERFORM EXISTS (SELECT finance.report_purchase_advance_list(null));
PERFORM EXISTS (SELECT finance.report_purchase_advance_list_detail(null));
PERFORM EXISTS (SELECT finance.sales_report_by_day());
PERFORM EXISTS (SELECT finance.save_ap_beginning_edit_new_to_old(null, null, 0));
PERFORM EXISTS (SELECT finance.save_ar_beginning_edit_new_to_old(null, null, 0));
PERFORM EXISTS (SELECT finance.save_cash_payment_new_to_old(null, null, FALSE));
PERFORM EXISTS (SELECT finance.save_cash_receipt_new_to_old(null, null, FALSE));
PERFORM EXISTS (SELECT finance.save_cash_receipt_parent(null));
PERFORM EXISTS (SELECT finance.save_purchase_advance_new_to_old(null, null));
PERFORM EXISTS (SELECT finance.save_purchase_advance_new_to_old_deposit(null, null));
PERFORM EXISTS (SELECT finance.set_auto_pick_cash_receipt(null, 0.0));
PERFORM EXISTS (SELECT finance.set_is_used_false_from_cash_payment(null, null));
PERFORM EXISTS (SELECT finance.set_new_cash_payment(null, CURRENT_DATE, null, null, null, null, null, null, null, null, null, null, null, null, null));
PERFORM EXISTS (SELECT finance.set_new_cash_payment_ap(CURRENT_DATE, null, null, null, null, null, null));
PERFORM EXISTS (SELECT finance.set_new_cash_payment_edit(null, null, 0.0, 0.0, 0.0, CURRENT_DATE, null, null, null, null, null));
PERFORM EXISTS (SELECT finance.set_new_cash_payment_new(null, null, 0.0, 0.0, 0.0, CURRENT_DATE, null, null, null, null, null));
PERFORM EXISTS (SELECT finance.set_new_cash_receipt(null, CURRENT_DATE, null, null, null, null, null, null, null, null, null, null, null));
PERFORM EXISTS (SELECT finance.set_new_cash_transfer(CURRENT_DATE, null, null, null, null, 0.0, null, null, 0.0, null, null, 0.0, null));
PERFORM EXISTS (SELECT finance.set_new_cash_transfer_1(CURRENT_DATE, null, null, null, null, 0.0, null, null, 0.0, null, null, null, 0.0, null));
PERFORM EXISTS (SELECT finance.set_new_cost_center(null, null, 0, FALSE, null, null, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT finance.set_new_currency(null, null, null, null, null, FALSE));
PERFORM EXISTS (SELECT finance.set_new_expense_realization(CURRENT_DATE, null, null, null, null, null, null, null, 0.0, 0.0, 0.0, 0.0, 0.0, null, null));
PERFORM EXISTS (SELECT finance.set_new_operational_adv_payment(CURRENT_DATE, null, null, null, null, null, null, CURRENT_DATE, 0.0, null, null));
PERFORM EXISTS (SELECT finance.set_new_payment_term(null, null, FALSE, null, null));
PERFORM EXISTS (SELECT finance.set_new_payment_term(null, null, FALSE, null, null, null, null, null, 0.0));
PERFORM EXISTS (SELECT finance.set_new_periode(CURRENT_DATE, CURRENT_DATE, null, null, null, FALSE, null));
PERFORM EXISTS (SELECT finance."set_new_periode_Archive"(CURRENT_DATE, CURRENT_DATE, null, null, null, FALSE, null));
PERFORM EXISTS (SELECT finance.set_new_purchase_adv_deposit(null, CURRENT_DATE, null, null, null, 0.0, null, null, 0.0, null, null));
PERFORM EXISTS (SELECT finance.set_new_purchase_advance(null, CURRENT_DATE, null, null, null, null, null));
PERFORM EXISTS (SELECT finance.set_new_purchase_advance_non_po(CURRENT_DATE, null, null, null, null, null, null, 0.0, null, null, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, null));
PERFORM EXISTS (SELECT finance.set_new_taxes(null, null, 0.0, null, null, null, FALSE, null));
PERFORM EXISTS (SELECT finance.set_new_update_payment_term_detail(null, null));
PERFORM EXISTS (SELECT finance.set_purchase_advance_journal(null));
PERFORM EXISTS (SELECT finance.set_sales_advance_from_cash_receipt(null));
PERFORM EXISTS (SELECT finance.update_data_from_payable_ap(null));
PERFORM EXISTS (SELECT finance.update_data_from_payment_non_giro(null));
PERFORM EXISTS (SELECT finance.update_data_from_receipt_non_giro(null));
PERFORM EXISTS (SELECT finance.update_data_from_receivable_ar(null));
PERFORM EXISTS (SELECT finance.update_invoice_cash_receipt(null));
PERFORM EXISTS (SELECT finance.update_is_used_edit_cash_payment(null));
PERFORM EXISTS (SELECT finance.update_old_cost_center(null));
PERFORM EXISTS (SELECT finance.update_old_periode(null));
PERFORM EXISTS (SELECT finance.update_old_taxes(null));
PERFORM EXISTS (SELECT finance.update_old_terms_payment(null));
PERFORM EXISTS (SELECT finance.update_old_terms_payment_detail(null, null));
PERFORM EXISTS (SELECT finance.update_purchase_order_is_used_false(null));
PERFORM EXISTS (SELECT finance.update_total_pick(null, 0.0));
PERFORM EXISTS (SELECT finance.update_total_pick_pl(null));
PERFORM EXISTS (SELECT finance.update_transaction_status_cash_payment(null));
PERFORM EXISTS (SELECT finance.validate_cost_center(null));
PERFORM EXISTS (SELECT finance.validate_cost_center_code(null));
PERFORM EXISTS (SELECT finance.validate_cost_center_code_archive(null));
PERFORM EXISTS (SELECT finance.validate_cost_center_edit_code(null, null));
PERFORM EXISTS (SELECT finance.validate_cost_center_name(null));
PERFORM EXISTS (SELECT finance.validate_cost_center_name_archive(null));
PERFORM EXISTS (SELECT finance.validate_cost_center_name_archive_new(null));
PERFORM EXISTS (SELECT finance.validate_currency(0, null));
PERFORM EXISTS (SELECT finance.validate_currency_archived(0, null));
PERFORM EXISTS (SELECT finance.validate_currency_code_iso(null, null));
PERFORM EXISTS (SELECT finance.validate_currency_country_edit(null, null));
PERFORM EXISTS (SELECT finance.validate_currency_name_edit(null, null));
PERFORM EXISTS (SELECT finance.validate_edit_cost_center_code(null, null));
PERFORM EXISTS (SELECT finance.validate_edit_cost_center_name(null, null));
PERFORM EXISTS (SELECT finance.validate_paymen_terms_code_edit(null, null));
PERFORM EXISTS (SELECT finance.validate_paymen_terms_name_edit(null, null));
PERFORM EXISTS (SELECT finance.validate_period(null, null));
PERFORM EXISTS (SELECT finance.validate_period_archived(null, null));
PERFORM EXISTS (SELECT finance.validate_periode_date(CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT finance.validate_periode_date_edited(CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT finance.validate_qc_parameter_archive(null));
PERFORM EXISTS (SELECT finance.validate_qc_parameter_name(null));
PERFORM EXISTS (SELECT finance.validate_supplier_category(null, null));
PERFORM EXISTS (SELECT finance.validate_taxes_code(null));
PERFORM EXISTS (SELECT finance.validate_taxes_code_archived(null));
PERFORM EXISTS (SELECT finance.validate_taxes_code_edit(null, null));
PERFORM EXISTS (SELECT finance.validate_taxes_edit_code(null, null));
PERFORM EXISTS (SELECT finance.validate_taxes_name(null));
PERFORM EXISTS (SELECT finance.validate_taxes_name_archived(null));
PERFORM EXISTS (SELECT finance.validate_taxes_name_edit(null, null));
PERFORM EXISTS (SELECT finance.validate_terms_payment_code(null));
PERFORM EXISTS (SELECT finance.validate_terms_payment_code_archive(null));
PERFORM EXISTS (SELECT finance.validate_terms_payment_name(null));
PERFORM EXISTS (SELECT finance.validate_terms_payment_name_archive(null));
END;