BEGIN
PERFORM EXISTS (SELECT sales.ar_invoice_detail_print_out(null));
PERFORM EXISTS (SELECT sales.ar_invoice_outlet_details(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, 0));
PERFORM EXISTS (SELECT sales.ar_invoice_outlet_details_report(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, 0));
PERFORM EXISTS (SELECT sales.ar_invoice_outlet_summary(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, 0));
PERFORM EXISTS (SELECT sales.ar_invoice_outlet_summary_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, 0));
PERFORM EXISTS (SELECT sales.ar_invoice_print_out(null));
PERFORM EXISTS (SELECT sales.archive_data(null, null));
PERFORM EXISTS (SELECT sales.archive_data_coloumn(null, null, null));
PERFORM EXISTS (SELECT sales.check_different_qty_sales_lite(null));
PERFORM EXISTS (SELECT sales.check_exists_pricelist(null, null));
PERFORM EXISTS (SELECT sales.check_outlet_pareto(null, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT sales.create_outlet_transaction_history(null, null, null, CURRENT_DATE, 0.0, 0.0, null, null));
PERFORM EXISTS (SELECT sales.delete_permanent(null, null));
PERFORM EXISTS (SELECT sales.delete_permanent_array_agg(null, null, null));
PERFORM EXISTS (SELECT sales.delete_permanent_coloumn(null, null, null));
PERFORM EXISTS (SELECT sales.delete_permanent_multiple(null, null));
PERFORM EXISTS (SELECT sales.delete_permanent_multiple_coloumn(null, null, null));
PERFORM EXISTS (SELECT sales.delivery_allocation_mobile_detail_for_list(null));
PERFORM EXISTS (SELECT sales.delivery_order_allocation_mobile_for_list(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT sales.delivery_order_allocation_mobile_for_list_new(null));
PERFORM EXISTS (SELECT sales.generate_sales_lite_batchnumber(null, null));
PERFORM EXISTS (SELECT sales.get_accumulation_qty_so(null));
PERFORM EXISTS (SELECT sales.get_ar_aging_outlet_report_det(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT sales.get_ar_aging_outlet_report_sum(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT sales.get_ar_aging_report_detail(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT sales.get_ar_aging_report_summary(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT sales.get_ar_billing(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT sales.get_ar_faktur_detail_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT sales.get_ar_faktur_detail_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT sales.get_ar_invoice_advance_settle_json(null));
PERFORM EXISTS (SELECT sales.get_ar_invoice_details_json(null));
PERFORM EXISTS (SELECT sales.get_ar_invoice_json(null));
PERFORM EXISTS (SELECT sales.get_ar_invoice_report_summary(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT sales.get_ar_ledger(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT sales.get_ar_ledger_bg_ed(CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT sales.get_ar_ledger_x(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT sales.get_ar_status());
PERFORM EXISTS (SELECT sales.get_base_invoice_details_json(null));
PERFORM EXISTS (SELECT sales.get_base_invoice_details_qty_json(null));
PERFORM EXISTS (SELECT sales.get_base_invoice_details_taxes_json(null));
PERFORM EXISTS (SELECT sales.get_base_invoice_json(null));
PERFORM EXISTS (SELECT sales.get_base_payments_json(null));
PERFORM EXISTS (SELECT sales.get_base_receive_details_json(null));
PERFORM EXISTS (SELECT sales.get_base_receive_details_qty_json(null));
PERFORM EXISTS (SELECT sales.get_base_receive_json(null));
PERFORM EXISTS (SELECT sales.get_base_shipment_details_json(null));
PERFORM EXISTS (SELECT sales.get_base_shipment_details_qty_json(null));
PERFORM EXISTS (SELECT sales.get_base_shipment_json(null));
PERFORM EXISTS (SELECT sales.get_canal());
PERFORM EXISTS (SELECT sales.get_canal_by_instance(null));
PERFORM EXISTS (SELECT sales.get_customer_type_code());
PERFORM EXISTS (SELECT sales.get_data_ar_invoice_list(null));
PERFORM EXISTS (SELECT sales.get_data_ar_invoice_outlet_parent(null));
PERFORM EXISTS (SELECT sales.get_do_for_report_sales(CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT sales.get_do_sales_plan(null, null));
PERFORM EXISTS (SELECT sales.get_edc_json(null));
PERFORM EXISTS (SELECT sales.get_expedition());
PERFORM EXISTS (SELECT sales.get_expedition_by_instance(null));
PERFORM EXISTS (SELECT sales.get_expedition_json(null));
PERFORM EXISTS (SELECT sales.get_favorite_products_json(null));
--PERFORM EXISTS (SELECT sales.get_id(null, ''));
--PERFORM EXISTS (SELECT sales.get_id_code(null, null, null));
--PERFORM EXISTS (SELECT sales.get_id_no_instance(null));
--PERFORM EXISTS (SELECT sales.get_id_transaction(null, null, null));
PERFORM EXISTS (SELECT sales.get_invoce_outlet_json(null));
PERFORM EXISTS (SELECT sales.get_invoice_outlet_details_json(null));
PERFORM EXISTS (SELECT sales.get_invoice_outlet_details_qty_json(null));
PERFORM EXISTS (SELECT sales.get_invoice_outlet_details_taxes_json(null));
PERFORM EXISTS (SELECT sales.get_invoice_outlet_json(null));
PERFORM EXISTS (SELECT sales.get_invoices_detail_json(null));
PERFORM EXISTS (SELECT sales.get_invoices_json(null));
PERFORM EXISTS (SELECT sales.get_list_qty_available());
PERFORM EXISTS (SELECT sales.get_location(null, CURRENT_DATE));
PERFORM EXISTS (SELECT sales.get_location_json(null));
PERFORM EXISTS (SELECT sales.get_location_last_updated_json(null));
PERFORM EXISTS (SELECT sales.get_location_sales(FALSE, null, CURRENT_DATE, FALSE));
PERFORM EXISTS (SELECT sales.get_location_sales(FALSE, null, CURRENT_DATE));
PERFORM EXISTS (SELECT sales.get_month_for_sales_period(FALSE, CURRENT_DATE, CURRENT_DATE, null, FALSE, 0));
PERFORM EXISTS (SELECT sales.get_month_for_sales_period_by_customer(FALSE, CURRENT_DATE, CURRENT_DATE, null, FALSE, 0));
PERFORM EXISTS (SELECT sales.get_month_for_sales_period_customer_category(FALSE, CURRENT_DATE, CURRENT_DATE, null, FALSE, 0, null));
PERFORM EXISTS (SELECT sales.get_month_for_sales_period_customer_category_by_instance(FALSE, CURRENT_DATE, CURRENT_DATE, null, null, FALSE, 0, null));
PERFORM EXISTS (SELECT sales.get_month_for_sales_period_customer_product_idr(FALSE, CURRENT_DATE, CURRENT_DATE, null, FALSE, 0, null));
PERFORM EXISTS (SELECT sales.get_month_for_sales_period_customer_product_qty(FALSE, CURRENT_DATE, CURRENT_DATE, null, FALSE, 0, null, null));
PERFORM EXISTS (SELECT sales.get_month_for_sales_period_product_idr(FALSE, CURRENT_DATE, CURRENT_DATE, null, FALSE, 0));
PERFORM EXISTS (SELECT sales.get_month_for_sales_period_product_qty(FALSE, CURRENT_DATE, CURRENT_DATE, null, FALSE, 0));
PERFORM EXISTS (SELECT sales.get_new_update_expedition(null));
PERFORM EXISTS (SELECT sales.get_new_update_master_canal(null));
PERFORM EXISTS (SELECT sales.get_outlet_invoice_details_json(null));
PERFORM EXISTS (SELECT sales.get_outlet_invoice_details_qty_json(null));
PERFORM EXISTS (SELECT sales.get_outlet_invoice_details_taxes_json(null));
PERFORM EXISTS (SELECT sales.get_outlet_invoice_instances(null));
PERFORM EXISTS (SELECT sales.get_outlet_invoice_json(null));
PERFORM EXISTS (SELECT sales.get_outlet_invoice_payments_json(null));
PERFORM EXISTS (SELECT sales.get_outlet_invoices(null, null));
PERFORM EXISTS (SELECT sales.get_outlet_receive_details_json(null));
PERFORM EXISTS (SELECT sales.get_outlet_receive_details_qty_json(null));
PERFORM EXISTS (SELECT sales.get_outlet_receive_from_selling_in_json(null));
PERFORM EXISTS (SELECT sales.get_outlet_receive_json(null));
PERFORM EXISTS (SELECT sales.get_outlet_retur_details_json(null));
PERFORM EXISTS (SELECT sales.get_outlet_retur_details_qty_json(null));
PERFORM EXISTS (SELECT sales.get_outlet_retur_details_taxes_json(null));
PERFORM EXISTS (SELECT sales.get_outlet_retur_json(null));
PERFORM EXISTS (SELECT sales.get_outlet_retur_taxes_json(null));
PERFORM EXISTS (SELECT sales.get_outlet_seliing_in_details_taxes_json(null));
PERFORM EXISTS (SELECT sales.get_outlet_seliing_in_taxes_json(null));
PERFORM EXISTS (SELECT sales.get_outlet_selilng_in_details_qty_json(null));
PERFORM EXISTS (SELECT sales.get_outlet_selling_in_details_discount_json(null));
PERFORM EXISTS (SELECT sales.get_outlet_selling_in_details_json(null));
PERFORM EXISTS (SELECT sales.get_outlet_selling_in_discount_json(null));
PERFORM EXISTS (SELECT sales.get_outlet_selling_in_json(null));
PERFORM EXISTS (SELECT sales.get_outlet_selling_in_taxes_json(null));
PERFORM EXISTS (SELECT sales.get_outlet_shipment_to_sales_details_json(null));
PERFORM EXISTS (SELECT sales.get_outlet_shipment_to_sales_details_qty_json(null));
PERFORM EXISTS (SELECT sales.get_outlet_shipment_to_sales_json(null));
PERFORM EXISTS (SELECT sales.get_outlet_transaction_history_json(null));
PERFORM EXISTS (SELECT sales.get_period_sales_comparison(CURRENT_DATE, 0, 0));
PERFORM EXISTS (SELECT sales.get_product_for_do_report(null));
PERFORM EXISTS (SELECT sales.get_product_for_online_sales_report(null));
PERFORM EXISTS (SELECT sales.get_product_for_pareto_product_report(null));
PERFORM EXISTS (SELECT sales.get_product_for_sales_plan_report(null));
PERFORM EXISTS (SELECT sales.get_product_for_sales_return_report(null));
PERFORM EXISTS (SELECT sales.get_product_for_so_outstanding_report(null));
PERFORM EXISTS (SELECT sales.get_product_sales_comparison(CURRENT_DATE, 0, 0, FALSE, null, 0));
PERFORM EXISTS (SELECT sales.get_product_sales_comparison_by_year(CURRENT_DATE, 0, FALSE, null, 0));
PERFORM EXISTS (SELECT sales.get_products());
PERFORM EXISTS (SELECT sales.get_receipt_of_payment_detail_json(null));
PERFORM EXISTS (SELECT sales.get_receipt_of_payment_json(null));
PERFORM EXISTS (SELECT sales.get_reminder_json(null));
PERFORM EXISTS (SELECT sales.get_report_sales_comparison_by_product(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT sales.get_report_sales_forecast_vs_actual_production_detail(null, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT sales.get_report_sales_forecast_vs_actual_production_group(null, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT sales.get_retur_draft_json(null));
PERFORM EXISTS (SELECT sales.get_retur_items_draft_json(null));
PERFORM EXISTS (SELECT sales.get_retur_items_json(null));
PERFORM EXISTS (SELECT sales.get_retur_json(null));
PERFORM EXISTS (SELECT sales."get_sales _order_buying_price_info"(null));
PERFORM EXISTS (SELECT sales.get_sales_by_customer_detail(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT sales.get_sales_by_customer_detail(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT sales.get_sales_by_customer_product_summary(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT sales.get_sales_by_customer_summary(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT sales.get_sales_by_segment(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT sales.get_sales_comparison_by_product(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT sales.get_sales_deposit_deficiency_detail_json(null));
PERFORM EXISTS (SELECT sales.get_sales_deposit_deficiency_json(null));
PERFORM EXISTS (SELECT sales.get_sales_deposit_json(null));
PERFORM EXISTS (SELECT sales.get_sales_deposit_summary_json(null));
PERFORM EXISTS (SELECT sales.get_sales_forecast_for_report_sales());
PERFORM EXISTS (SELECT sales.get_sales_group_detail_json(null));
PERFORM EXISTS (SELECT sales.get_sales_groups_json(null));
PERFORM EXISTS (SELECT sales.get_sales_incentives_details_json(null));
PERFORM EXISTS (SELECT sales.get_sales_incentives_json(null));
PERFORM EXISTS (SELECT sales.get_sales_lite_buying_price_info(null));
PERFORM EXISTS (SELECT sales.get_sales_lite_parent(null));
PERFORM EXISTS (SELECT sales.get_sales_order(null));
PERFORM EXISTS (SELECT sales.get_sales_order_buying_price_info(null));
PERFORM EXISTS (SELECT sales.get_sales_order_detail_json(null));
PERFORM EXISTS (SELECT sales.get_sales_order_json(null));
PERFORM EXISTS (SELECT sales.get_sales_period_by_category(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT sales.get_sales_period_by_customer(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT sales.get_sales_period_by_customer_category(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT sales.get_sales_period_by_customer_product_idr(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT sales.get_sales_period_by_customer_product_qty(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT sales.get_sales_period_by_product_idr(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT sales.get_sales_period_by_product_qty(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT sales.get_sales_receive_from_retur_details_json(null));
PERFORM EXISTS (SELECT sales.get_sales_receive_from_retur_details_qty_json(null));
PERFORM EXISTS (SELECT sales.get_sales_receive_from_retur_json(null));
PERFORM EXISTS (SELECT sales.get_sales_return_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT sales.get_sales_selling_in_stock_track_details_json(null));
PERFORM EXISTS (SELECT sales.get_sales_selling_in_stock_track_json(null));
PERFORM EXISTS (SELECT sales.get_sales_stock_opname_draft_json(null));
PERFORM EXISTS (SELECT sales.get_sales_stock_opname_items_draft_json(null));
PERFORM EXISTS (SELECT sales.get_sales_stock_opname_items_json(null));
PERFORM EXISTS (SELECT sales.get_sales_stock_opname_json(null));
PERFORM EXISTS (SELECT sales.get_shipment_to_instance_json(null));
PERFORM EXISTS (SELECT sales.get_shipment_to_outlet_details_json(null));
PERFORM EXISTS (SELECT sales.get_shipment_to_outlet_details_qty_json(null));
PERFORM EXISTS (SELECT sales.get_shipment_to_outlet_json(null));
PERFORM EXISTS (SELECT sales.get_so_sales_plan(null, null));
PERFORM EXISTS (SELECT sales.get_store_admin_json(null));
PERFORM EXISTS (SELECT sales.get_store_json(null));
PERFORM EXISTS (SELECT sales.get_view_ar_invoice_advance_settle_json(null));
PERFORM EXISTS (SELECT sales.get_view_ar_invoice_details_json(null));
PERFORM EXISTS (SELECT sales.get_view_ar_invoice_json(null));
PERFORM EXISTS (SELECT sales.get_view_base_invoice_details_json(null));
PERFORM EXISTS (SELECT sales.get_view_base_invoice_details_qty_json(null));
PERFORM EXISTS (SELECT sales.get_view_base_invoice_details_taxes_json(null));
PERFORM EXISTS (SELECT sales.get_view_base_invoice_json(null));
PERFORM EXISTS (SELECT sales.get_view_base_payments_json(null));
PERFORM EXISTS (SELECT sales.get_view_base_receive_details_json(null));
PERFORM EXISTS (SELECT sales.get_view_base_receive_details_qty_json(null));
PERFORM EXISTS (SELECT sales.get_view_base_receive_json(null));
PERFORM EXISTS (SELECT sales.get_view_base_shipment_details_json(null));
PERFORM EXISTS (SELECT sales.get_view_base_shipment_details_qty_json(null));
PERFORM EXISTS (SELECT sales.get_view_base_shipment_json(null));
PERFORM EXISTS (SELECT sales.get_view_edc_json(null));
PERFORM EXISTS (SELECT sales.get_view_expedition_json(null));
PERFORM EXISTS (SELECT sales.get_view_favorite_products_json(null));
PERFORM EXISTS (SELECT sales.get_view_invoce_outlet_json(null));
PERFORM EXISTS (SELECT sales.get_view_invoice_outlet_details_json(null));
PERFORM EXISTS (SELECT sales.get_view_invoice_outlet_details_qty_json(null));
PERFORM EXISTS (SELECT sales.get_view_invoice_outlet_details_taxes_json(null));
PERFORM EXISTS (SELECT sales.get_view_invoice_outlet_json(null));
PERFORM EXISTS (SELECT sales.get_view_invoices_detail_json(null));
PERFORM EXISTS (SELECT sales.get_view_invoices_json(null));
PERFORM EXISTS (SELECT sales.get_view_last_location_json(null));
PERFORM EXISTS (SELECT sales.get_view_location_json(null));
PERFORM EXISTS (SELECT sales.get_view_location_last_updated_json(null));
PERFORM EXISTS (SELECT sales.get_view_outlet_invoice_details_json(null));
PERFORM EXISTS (SELECT sales.get_view_outlet_invoice_details_qty_json(null));
PERFORM EXISTS (SELECT sales.get_view_outlet_invoice_details_taxes_json(null));
PERFORM EXISTS (SELECT sales.get_view_outlet_invoice_json(null));
PERFORM EXISTS (SELECT sales.get_view_outlet_invoice_payments_json(null));
PERFORM EXISTS (SELECT sales.get_view_outlet_receive_details_json(null));
PERFORM EXISTS (SELECT sales.get_view_outlet_receive_details_qty_json(null));
PERFORM EXISTS (SELECT sales.get_view_outlet_receive_from_selling_in_json(null));
PERFORM EXISTS (SELECT sales.get_view_outlet_receive_json(null));
PERFORM EXISTS (SELECT sales.get_view_outlet_retur_details_json(null));
PERFORM EXISTS (SELECT sales.get_view_outlet_retur_details_qty_json(null));
PERFORM EXISTS (SELECT sales.get_view_outlet_retur_details_taxes_json(null));
PERFORM EXISTS (SELECT sales.get_view_outlet_retur_json(null));
PERFORM EXISTS (SELECT sales.get_view_outlet_retur_taxes_json(null));
PERFORM EXISTS (SELECT sales.get_view_outlet_seliing_in_details_taxes_json(null));
PERFORM EXISTS (SELECT sales.get_view_outlet_seliing_in_taxes_json(null));
PERFORM EXISTS (SELECT sales.get_view_outlet_selilng_in_details_qty_json(null));
PERFORM EXISTS (SELECT sales.get_view_outlet_selling_in_details_discount_json(null));
PERFORM EXISTS (SELECT sales.get_view_outlet_selling_in_details_json(null));
PERFORM EXISTS (SELECT sales.get_view_outlet_selling_in_discount_json(null));
PERFORM EXISTS (SELECT sales.get_view_outlet_selling_in_json(null));
PERFORM EXISTS (SELECT sales.get_view_outlet_selling_in_taxes_json(null));
PERFORM EXISTS (SELECT sales.get_view_outlet_shipment_to_sales_details_json(null));
PERFORM EXISTS (SELECT sales.get_view_outlet_shipment_to_sales_details_qty_json(null));
PERFORM EXISTS (SELECT sales.get_view_outlet_shipment_to_sales_json(null));
PERFORM EXISTS (SELECT sales.get_view_outlet_transaction_history_json(null));
PERFORM EXISTS (SELECT sales.get_view_receipt_of_payment_detail_json(null));
PERFORM EXISTS (SELECT sales.get_view_receipt_of_payment_json(null));
PERFORM EXISTS (SELECT sales.get_view_reminder_json(null));
PERFORM EXISTS (SELECT sales.get_view_retur_items_json(null));
PERFORM EXISTS (SELECT sales.get_view_retur_json(null));
PERFORM EXISTS (SELECT sales.get_view_sales_deposit_deficiency_detail_json(null));
PERFORM EXISTS (SELECT sales.get_view_sales_deposit_deficiency_json(null));
PERFORM EXISTS (SELECT sales.get_view_sales_deposit_json(null));
PERFORM EXISTS (SELECT sales.get_view_sales_deposit_summary_json(null));
PERFORM EXISTS (SELECT sales.get_view_sales_group_detail_json(null));
PERFORM EXISTS (SELECT sales.get_view_sales_groups_json(null));
PERFORM EXISTS (SELECT sales.get_view_sales_incentives_details_json(null));
PERFORM EXISTS (SELECT sales.get_view_sales_incentives_json(null));
PERFORM EXISTS (SELECT sales.get_view_sales_order_detail_json(null));
PERFORM EXISTS (SELECT sales.get_view_sales_order_json(null));
PERFORM EXISTS (SELECT sales.get_view_sales_receive_from_retur_details_json(null));
PERFORM EXISTS (SELECT sales.get_view_sales_receive_from_retur_details_qty_json(null));
PERFORM EXISTS (SELECT sales.get_view_sales_receive_from_retur_json(null));
PERFORM EXISTS (SELECT sales.get_view_sales_stock_opname_items_json(null));
PERFORM EXISTS (SELECT sales.get_view_sales_stock_opname_json(null));
PERFORM EXISTS (SELECT sales.get_view_shipment_to_instance_json(null));
PERFORM EXISTS (SELECT sales.get_view_shipment_to_outlet_details_json(null));
PERFORM EXISTS (SELECT sales.get_view_shipment_to_outlet_details_qty_json(null));
PERFORM EXISTS (SELECT sales.get_view_shipment_to_outlet_json(null));
PERFORM EXISTS (SELECT sales.get_view_store_admin_json(null));
PERFORM EXISTS (SELECT sales.get_view_store_json(null));
PERFORM EXISTS (SELECT sales.get_view_visiting_json(null));
PERFORM EXISTS (SELECT sales.get_view_visiting_reminder_json(null));
PERFORM EXISTS (SELECT sales.get_view_work_order_additional_costs_json(null));
PERFORM EXISTS (SELECT sales.get_view_work_order_attachment_json(null));
PERFORM EXISTS (SELECT sales.get_view_work_order_detail_bill_of_quantity_json(null));
PERFORM EXISTS (SELECT sales.get_view_work_order_detail_json(null));
PERFORM EXISTS (SELECT sales.get_view_work_order_detail_spec_json(null));
PERFORM EXISTS (SELECT sales.get_view_work_order_inventory_of_goods_json(null));
PERFORM EXISTS (SELECT sales.get_view_work_order_json(null));
PERFORM EXISTS (SELECT sales.get_view_work_order_payment_system_json(null));
PERFORM EXISTS (SELECT sales.get_view_work_order_terms_of_delivery_json(null));
PERFORM EXISTS (SELECT sales.get_visiting_json(null));
PERFORM EXISTS (SELECT sales.get_visiting_reminder_json(null));
PERFORM EXISTS (SELECT sales.get_warehouse_for_delivery_order(null));
PERFORM EXISTS (SELECT sales.get_work_order_additional_costs_json(null));
PERFORM EXISTS (SELECT sales.get_work_order_attachment_json(null));
PERFORM EXISTS (SELECT sales.get_work_order_detail_bill_of_quantity_json(null));
PERFORM EXISTS (SELECT sales.get_work_order_detail_json(null));
PERFORM EXISTS (SELECT sales.get_work_order_detail_spec_json(null));
PERFORM EXISTS (SELECT sales.get_work_order_inventory_of_goods_json(null));
PERFORM EXISTS (SELECT sales.get_work_order_json(null));
PERFORM EXISTS (SELECT sales.get_work_order_payment_system_json(null));
PERFORM EXISTS (SELECT sales.get_work_order_terms_of_delivery_json(null));
PERFORM EXISTS (SELECT sales.get_year());
PERFORM EXISTS (SELECT sales.good_replacement_edit(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT sales.good_replacement_edit_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT sales.good_replacement_insert_to_journal(null, null));
PERFORM EXISTS (SELECT sales.good_replacement_insert_to_journal_unit_price(null, null));
PERFORM EXISTS (SELECT sales.good_replacement_received_set_stock(null, null, null));
PERFORM EXISTS (SELECT sales.insert_detail_so_new(null, null, null, null, FALSE, FALSE, FALSE));
PERFORM EXISTS (SELECT sales.insert_edit_ar_invoice(null));
PERFORM EXISTS (SELECT sales.insert_edit_good_replacement(null));
PERFORM EXISTS (SELECT sales.insert_edit_sales_lite(null));
PERFORM EXISTS (SELECT sales.insert_edit_sales_order(null));
PERFORM EXISTS (SELECT sales.insert_new_ar_invoice_detail(null, null));
PERFORM EXISTS (SELECT sales.insert_sales_lite_from_sales_advance(null, null));
PERFORM EXISTS (SELECT sales.insert_store(null, null, null, null, null, null, null, null));
PERFORM EXISTS (SELECT sales.insert_store(null, null, null, null, null, null));
PERFORM EXISTS (SELECT sales.invoice_outlet_detail_list(null));
PERFORM EXISTS (SELECT sales.list_account_for_ar_invoice_beginning());
PERFORM EXISTS (SELECT sales.list_ar_invoice(null, FALSE, null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, 0));
PERFORM EXISTS (SELECT sales.list_ar_invoice_advance_settle(null));
PERFORM EXISTS (SELECT sales.list_ar_invoice_beginning(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT sales.list_ar_invoice_beginning_edit(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT sales.list_ar_invoice_beginning_list(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null, null));
PERFORM EXISTS (SELECT sales.list_ar_invoice_beginning_list_parent(FALSE, CURRENT_DATE, CURRENT_DATE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT sales.list_ar_invoice_detail(null));
PERFORM EXISTS (SELECT sales.list_ar_invoice_detail_edit(null));
PERFORM EXISTS (SELECT sales.list_ar_invoice_edit(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT sales.list_ar_invoice_report_detail(null, FALSE, null, FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT sales.list_ar_invoice_report_detail(null, FALSE, null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT sales.list_ar_invoice_report_detail1(null));
PERFORM EXISTS (SELECT sales.list_ar_invoice_report_detail2(null));
PERFORM EXISTS (SELECT sales.list_ar_invoice_report_parent(null, FALSE, null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT sales.list_ar_ledger_outlet(CURRENT_DATE, CURRENT_DATE, null, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT sales.list_ar_ledger_outlet_summary(CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT sales.list_customer_for_ar_invoice_beginning());
PERFORM EXISTS (SELECT sales.list_distribution_fg_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT sales.list_edc(null));
PERFORM EXISTS (SELECT sales.list_expedition(null, FALSE));
PERFORM EXISTS (SELECT sales.list_expedition_archive_city(null));
PERFORM EXISTS (SELECT sales.list_expedition_new(null, FALSE));
PERFORM EXISTS (SELECT sales.list_good_replacement(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT sales.list_good_replacement_detail(null));
PERFORM EXISTS (SELECT sales.list_good_replacement_list(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT sales.list_good_replacement_list_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT sales.list_good_replacement_list_detail_new(null));
PERFORM EXISTS (SELECT sales.list_good_replacement_receive(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT sales.list_good_replacement_receive_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT sales.list_good_replacement_receive_detail_edit(null, FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT sales.list_good_replacement_receive_edit(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT sales.list_good_replacement_receive_list(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT sales.list_good_replacement_receive_list_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT sales.list_good_replacement_receive_list_detail_new(null));
PERFORM EXISTS (SELECT sales.list_master_canal(FALSE, null));
PERFORM EXISTS (SELECT sales.list_master_canal_archive(null));
PERFORM EXISTS (SELECT sales.list_of_deposit_history(null));
PERFORM EXISTS (SELECT sales.list_of_product_replacement(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT sales.list_of_product_replacement_detail(null));
PERFORM EXISTS (SELECT sales.list_of_recap_collectible(null));
PERFORM EXISTS (SELECT sales.list_of_sales_deposits(null));
PERFORM EXISTS (SELECT sales.list_of_sales_lite(null, FALSE, CURRENT_DATE, CURRENT_DATE, null, FALSE, null));
PERFORM EXISTS (SELECT sales.list_of_sales_lite_batchnumber(null));
PERFORM EXISTS (SELECT sales.list_of_sales_lite_detail(null));
PERFORM EXISTS (SELECT sales.list_of_sales_lite_settle(null));
PERFORM EXISTS (SELECT sales.list_of_sales_replacement_to_received(null, FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT sales.list_of_sales_replacement_to_received_detail(null));
PERFORM EXISTS (SELECT sales.list_pareto_customer_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT sales.list_pareto_product_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT sales.list_sales_group_employee());
PERFORM EXISTS (SELECT sales.list_sales_lite_for_edit(null, FALSE, CURRENT_DATE, CURRENT_DATE, null, FALSE, null));
PERFORM EXISTS (SELECT sales.list_sales_order(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT sales.list_sales_order_close(null, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT sales.list_sales_order_close_detail(FALSE, CURRENT_DATE, CURRENT_DATE, null, null));
PERFORM EXISTS (SELECT sales.list_sales_order_close_report_detail(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT sales.list_sales_order_close_report_parent(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT sales.list_sales_order_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT sales.list_sales_order_detail_for_edit(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT sales.list_sales_order_detail_list(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT sales.list_sales_order_detail_so(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT sales.list_sales_order_do(CURRENT_DATE, CURRENT_DATE, null, FALSE, FALSE, FALSE, null));
PERFORM EXISTS (SELECT sales.list_sales_order_for_edit(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT sales.list_sales_order_list(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, FALSE, null, FALSE, 0));
PERFORM EXISTS (SELECT sales.list_sales_order_list_parent(null, FALSE, null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE));
PERFORM EXISTS (SELECT sales.list_sales_order_midtrans_detail_report(null));
PERFORM EXISTS (SELECT sales.list_sales_order_midtrans_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT sales.list_sales_order_new(CURRENT_DATE, CURRENT_DATE, null, null, FALSE, FALSE));
PERFORM EXISTS (SELECT sales.list_sales_order_report_detail(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT sales.list_sales_order_report_detail(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, null, FALSE, 0));
PERFORM EXISTS (SELECT sales.list_sales_order_report_summary(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null, FALSE, 0, null));
--PERFORM EXISTS (SELECT sales.list_sales_order_report_summary(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT sales.list_sales_order_report_summary(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT sales.list_sales_plan(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT sales.list_sales_price_list_archive(null));
PERFORM EXISTS (SELECT sales.list_sales_return_receive(CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT sales.list_selling_price(null, null, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT sales.list_selling_price_archive(null));
PERFORM EXISTS (SELECT sales.list_shipping_order_detail_edit(null));
PERFORM EXISTS (SELECT sales.list_store(null));
PERFORM EXISTS (SELECT sales.list_visiting_report(null));
PERFORM EXISTS (SELECT sales.master_canal_list());
PERFORM EXISTS (SELECT sales.master_get_canal_by_instance(null));
PERFORM EXISTS (SELECT sales.open_ar_invoice(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT sales.open_ar_invoice_advance_settle(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT sales.open_ar_invoice_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT sales.open_close_ar_invoice(null, FALSE));
PERFORM EXISTS (SELECT sales.open_close_delivery_order(null, FALSE));
PERFORM EXISTS (SELECT sales.open_close_good_replacement(null, FALSE));
PERFORM EXISTS (SELECT sales.open_close_good_replacement_receive(null, FALSE));
PERFORM EXISTS (SELECT sales.open_close_sales_order(null, FALSE));
PERFORM EXISTS (SELECT sales.open_close_sales_return_receive(null, FALSE));
PERFORM EXISTS (SELECT sales.open_close_sales_return_request(null, FALSE));
PERFORM EXISTS (SELECT sales.open_close_shipping_order(null, FALSE));
PERFORM EXISTS (SELECT sales.open_delivery_order(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT sales.open_delivery_order_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT sales.open_good_replacement(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT sales.open_good_replacement_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT sales.open_good_replacement_receive(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT sales.open_good_replacement_receive_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT sales.open_list_ar_invoice_beginning(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT sales.open_sales_lite(FALSE, CURRENT_DATE, CURRENT_DATE, null, null));
PERFORM EXISTS (SELECT sales.open_sales_lite_batchnumber(null));
PERFORM EXISTS (SELECT sales.open_sales_lite_detail(null));
PERFORM EXISTS (SELECT sales.open_sales_lite_settle(null));
PERFORM EXISTS (SELECT sales.open_sales_order(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT sales.open_sales_order_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT sales.open_sales_return_receive(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT sales.open_sales_return_receive_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT sales.open_sales_return_request(FALSE, CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT sales.open_sales_return_request_detail(null));
PERFORM EXISTS (SELECT sales.open_shipping_order(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT sales.open_shipping_order_detail(null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT sales.outstanding_sales_order_report_list(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT sales.outstanding_sales_order_report_list_print_new(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, null, null));
--PERFORM EXISTS (SELECT sales.outstanding_sales_order_report_print(null));
PERFORM EXISTS (SELECT sales.print_ar_invoice_beginning_list(null));
PERFORM EXISTS (SELECT sales.print_ar_ledger_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT sales.print_good_replacement_list(null));
PERFORM EXISTS (SELECT sales.print_good_replacement_receive_detail());
PERFORM EXISTS (SELECT sales.print_good_replacement_receive_list(null));
PERFORM EXISTS (SELECT sales.print_settlement_sales_list(null));
PERFORM EXISTS (SELECT sales.printout_sales_planning(null, null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT sales.printout_sales_planning_detail(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT sales.printt_good_replacement_list_detail());
PERFORM EXISTS (SELECT sales.report_ar_aging_report_detail(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT sales.report_ar_aging_report_summary(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT sales.report_ar_billing(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT sales.report_ar_faktur_detail_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT sales.report_ar_faktur_detail_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT sales.report_ar_invoice(null));
PERFORM EXISTS (SELECT sales.report_ar_invoice_detail());
PERFORM EXISTS (SELECT sales.report_ar_invoice_report_summary(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT sales.report_delivery_allocation_mobile_detail_for_list());
PERFORM EXISTS (SELECT sales.report_delivery_order_allocation_mobile_for_list(null));
PERFORM EXISTS (SELECT sales.report_distribution_fg_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT sales.report_get_ar_ledger(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT sales.report_pareto_customer_list(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT sales.report_pareto_product_list(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, null));
PERFORM EXISTS (SELECT sales.report_print_sales_order_close_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT sales.report_sales_advance_receipt_parent(null));
PERFORM EXISTS (SELECT sales.report_sales_by_customer_detail(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT sales.report_sales_by_customer_detail(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT sales.report_sales_by_customer_product_summary(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT sales.report_sales_by_customer_summary(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT sales.report_sales_by_segment(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT sales.report_sales_lite(null));
PERFORM EXISTS (SELECT sales.report_sales_lite_detail(null));
PERFORM EXISTS (SELECT sales.report_sales_order_close_detail(null));
PERFORM EXISTS (SELECT sales.report_sales_order_close_parent(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT sales.report_sales_order_close_parent(null, FALSE, FALSE, CURRENT_DATE, CURRENT_DATE, null, null, FALSE, FALSE, null));
PERFORM EXISTS (SELECT sales.report_sales_order_detail(FALSE, CURRENT_DATE, CURRENT_DATE, null, FALSE, null, FALSE, null, FALSE, null, FALSE, 0));
PERFORM EXISTS (SELECT sales.report_sales_order_detail(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT sales.report_sales_order_list_detail());
PERFORM EXISTS (SELECT sales.report_sales_order_list_parent(null));
PERFORM EXISTS (SELECT sales.report_sales_order_summary(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, null, FALSE, 0));
PERFORM EXISTS (SELECT sales.report_sales_order_summary(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT sales.report_sales_period_by_category(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT sales.report_sales_period_by_customer_category(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT sales.report_sales_period_by_customer_idr_print(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT sales.report_sales_period_by_customer_product_idr_print(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT sales.report_sales_period_by_customer_product_qty_print(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT sales.report_sales_period_by_customer_product_qty_print_old(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT sales.report_sales_period_by_product_idr(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT sales.report_sales_period_by_product_qty(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null));
PERFORM EXISTS (SELECT sales.report_sales_return_report(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT sales.return_received_outlet_set_stock(null, null, null));
PERFORM EXISTS (SELECT sales.sales_order_report_detail(null));
PERFORM EXISTS (SELECT sales.sales_order_report_list(FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT sales.sales_order_report_list_detail(null, null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT sales.sales_order_report_parent(null));
PERFORM EXISTS (SELECT sales.sales_order_validate_qty(null));
PERFORM EXISTS (SELECT sales.sales_order_validate_qty_new(null, FALSE));
--PERFORM EXISTS (SELECT sales.sales_remaining_receivables(null));
PERFORM EXISTS (SELECT sales.select_data_same_price_list(null, null, null, FALSE, null));
PERFORM EXISTS (SELECT sales.select_data_same_price_list(null, null, null, FALSE));
PERFORM EXISTS (SELECT sales.set_approved_sales_lite(null, null, null));
PERFORM EXISTS (SELECT sales.set_ar_beginning_cust_outl(CURRENT_DATE, null, null, null, 0.0, null, null, null, null, null, null, CURRENT_DATE, null, null, null, 0));
PERFORM EXISTS (SELECT sales.set_is_enabled(null, null, FALSE));
PERFORM EXISTS (SELECT sales.set_new_ar_beginning(CURRENT_DATE, null, null, null, 0.0, null, null, null, null, null, null, CURRENT_DATE, null, null, null));
PERFORM EXISTS (SELECT sales.set_new_ar_invoice(null, CURRENT_DATE, null, null, null, null, null, null, null, CURRENT_DATE, null, null, null, null, null, null, CURRENT_DATE, null, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, null, 0.0, null));
PERFORM EXISTS (SELECT sales.set_new_edc(null, null, null, 0.0, null, FALSE));
PERFORM EXISTS (SELECT sales.set_new_expedition(null, null, null, null, null, null, null, null, null, FALSE, null));
PERFORM EXISTS (SELECT sales.set_new_good_replacement(CURRENT_DATE, null, null, null, null, null, null, 0.0, null, null, null));
PERFORM EXISTS (SELECT sales.set_new_good_replacement_receive(CURRENT_DATE, null, null, null, null, null, null, 0.0, null, null));
PERFORM EXISTS (SELECT sales.set_new_good_replacement_unit_price(CURRENT_DATE, null, null, null, null, null, null, 0.0, null, null, null));
PERFORM EXISTS (SELECT sales.set_new_master_canal(null, null, null, null, null, null));
PERFORM EXISTS (SELECT sales.set_new_sales_plan(null, FALSE, null, 0));
PERFORM EXISTS (SELECT sales.set_new_sales_plan(null, FALSE, null));
PERFORM EXISTS (SELECT sales.set_new_sales_plan_detail(null));
PERFORM EXISTS (SELECT sales.set_new_sales_return_received_outlet(null, null, null, CURRENT_DATE, null, null, null));
PERFORM EXISTS (SELECT sales.set_new_update_sales_order(null, CURRENT_DATE, null, null, null, null, null, null, null, null, null, null, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, null, null, null, null, null, null));
PERFORM EXISTS (SELECT sales.set_new_update_sales_order(null, CURRENT_DATE, null, null, null, null, null, null, null, null, null, null, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, null, null, null, null, FALSE, null));
PERFORM EXISTS (SELECT sales.set_outlet_invoice_to_journal(null, 0));
PERFORM EXISTS (SELECT sales.set_outlet_payment_to_journal(null, null));
PERFORM EXISTS (SELECT sales.set_products_to_products_received_detail(null, null));
PERFORM EXISTS (SELECT sales.set_revision_number(null, null, null, null));
PERFORM EXISTS (SELECT sales.set_sales_lite(null, CURRENT_DATE, null, null, 0, null, null, null, null, null, null, null, null, null, null, null, null, null, null, CURRENT_DATE, null, null, null, null, null, null, null, null, 0.0, FALSE, null, null, null, CURRENT_DATE, null, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, null, null));
PERFORM EXISTS (SELECT sales.set_sales_lite_defaults(null, 0, null));
PERFORM EXISTS (SELECT sales.set_sales_lite_detail(null, null, null, null, null, FALSE, FALSE, FALSE));
PERFORM EXISTS (SELECT sales.set_sales_lite_insert_advance_by_customer(null, null));
PERFORM EXISTS (SELECT sales.set_sales_lite_invoice(null));
PERFORM EXISTS (SELECT sales.set_sales_lite_journal_stock(null));
PERFORM EXISTS (SELECT sales.set_sales_lite_outgoing_product(null));
PERFORM EXISTS (SELECT sales.set_sales_lite_update_stock(null));
PERFORM EXISTS (SELECT sales.set_sales_order_detail(null, null, null, null, null, FALSE, FALSE, FALSE));
PERFORM EXISTS (SELECT sales.set_settlement_to_journal(null));
PERFORM EXISTS (SELECT sales.update_old_expedition(null));
PERFORM EXISTS (SELECT sales.update_old_master_canal(null));
PERFORM EXISTS (SELECT sales.update_sales_lite_detail(null, null, null, null, FALSE, FALSE, FALSE));
PERFORM EXISTS (SELECT sales.update_trx_status_so_from_do(null));
PERFORM EXISTS (SELECT sales.val_credit_exceed(null));
PERFORM EXISTS (SELECT sales.validasi_edc_code(null));
PERFORM EXISTS (SELECT sales.validasi_master_canal_name(null));
PERFORM EXISTS (SELECT sales.validasi_master_canal_name_archived(null));
PERFORM EXISTS (SELECT sales.validasi_name_mastercanaledit(null, null));
PERFORM EXISTS (SELECT sales.validate_backdate_sales_lite_arrival_date(CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT sales.validate_edit_and_remove_sales_lite(null));
PERFORM EXISTS (SELECT sales.validate_edit_and_remove_sales_order(null));
PERFORM EXISTS (SELECT sales.validate_edit_sales_order(null));
PERFORM EXISTS (SELECT sales.validate_expedition_name(null));
PERFORM EXISTS (SELECT sales.validate_expedition_name_edit(null, null));
PERFORM EXISTS (SELECT sales.validate_expendition_name_archive(null));
PERFORM EXISTS (SELECT sales.validate_master_canal_name(null));
PERFORM EXISTS (SELECT sales.validate_sales_methode_sales_order_edit(null));
END;