BEGIN
PERFORM EXISTS (SELECT warehouse.check_archived_items(null));
PERFORM EXISTS (SELECT warehouse.check_is_error_mat_used_edit(null, null, null));
PERFORM EXISTS (SELECT warehouse.check_warehouse_is_empty(null));
PERFORM EXISTS (SELECT warehouse.delete_stock_opname(null, 0));
PERFORM EXISTS (SELECT warehouse.delete_stock_opname_detail(null));
PERFORM EXISTS (SELECT warehouse.fc_get_product_with_cogs(null));
PERFORM EXISTS (SELECT warehouse.get_all_product_uoms());
PERFORM EXISTS (SELECT warehouse.get_average_stock_unit_price(null, null, FALSE, null));
PERFORM EXISTS (SELECT warehouse.get_batch_number(null));
PERFORM EXISTS (SELECT warehouse.get_batch_numbers(null));
PERFORM EXISTS (SELECT warehouse.get_batch_numbers_for_good_replacement_receive(null));
PERFORM EXISTS (SELECT warehouse.get_batchnumbers());
PERFORM EXISTS (SELECT warehouse.get_beginning_stock_ledger(null));
PERFORM EXISTS (SELECT warehouse.get_category());
PERFORM EXISTS (SELECT warehouse.get_category_json(null));
PERFORM EXISTS (SELECT warehouse.get_category_product());
PERFORM EXISTS (SELECT warehouse.get_category_store());
PERFORM EXISTS (SELECT warehouse.get_cogs_transaction_specific_batch_number(null, null, FALSE, null));
PERFORM EXISTS (SELECT warehouse.get_cogs_transaction_specific_batch_number_for_return(null, null, null));
PERFORM EXISTS (SELECT warehouse.get_convertion_detail(null, 0.0));
PERFORM EXISTS (SELECT warehouse.get_convertion_name(null, 0.0));
PERFORM EXISTS (SELECT warehouse.get_current_level_warehouse(null));
PERFORM EXISTS (SELECT warehouse.get_current_stock_by_batch(null, null, null, null));
PERFORM EXISTS (SELECT warehouse.get_default_unit_id_by_product(null));
PERFORM EXISTS (SELECT warehouse.get_expedition_rooms_json(null));
PERFORM EXISTS (SELECT warehouse.get_instance_rooms_admin_json(null));
PERFORM EXISTS (SELECT warehouse.get_instance_rooms_json(null));
PERFORM EXISTS (SELECT warehouse.get_inventory_category(null));
PERFORM EXISTS (SELECT warehouse.get_inventory_ledger_detail_json(null));
PERFORM EXISTS (SELECT warehouse.get_inventory_ledger_json(null));
PERFORM EXISTS (SELECT warehouse.get_inventory_ratio());
PERFORM EXISTS (SELECT warehouse.get_inventory_ratio_and_unit_price_by_product());
PERFORM EXISTS (SELECT warehouse.get_inventory_ratio_for_good_replacement());
PERFORM EXISTS (SELECT warehouse.get_item_converter(null, null, null, 0.0));
PERFORM EXISTS (SELECT warehouse.get_item_default_unit(null));
PERFORM EXISTS (SELECT warehouse.get_item_unit_id_by_kind_unit(null, null));
PERFORM EXISTS (SELECT warehouse.get_list_product_by_instance(null, null));
PERFORM EXISTS (SELECT warehouse.get_new_update_master_group(null));
PERFORM EXISTS (SELECT warehouse.get_new_update_master_segmen(null));
PERFORM EXISTS (SELECT warehouse.get_new_update_products(null));
PERFORM EXISTS (SELECT warehouse.get_new_update_warehouse(null));
PERFORM EXISTS (SELECT warehouse.get_new_update_warehouse_category(null));
PERFORM EXISTS (SELECT warehouse.get_new_update_warehouse_top(null));
PERFORM EXISTS (SELECT warehouse.get_outlet_rooms_json(null));
PERFORM EXISTS (SELECT warehouse.get_outstanding_grn(null, null, null));
PERFORM EXISTS (SELECT warehouse.get_parent_warehouse(null));
PERFORM EXISTS (SELECT warehouse.get_product_allocation(null));
PERFORM EXISTS (SELECT warehouse.get_product_allocation_detail_json(null));
PERFORM EXISTS (SELECT warehouse.get_product_allocation_detail_qty_json(null));
PERFORM EXISTS (SELECT warehouse.get_product_allocation_json(null));
PERFORM EXISTS (SELECT warehouse.get_product_and_prices());
PERFORM EXISTS (SELECT warehouse.get_product_category_by_instance(null));
PERFORM EXISTS (SELECT warehouse.get_product_qrcodes_json(null));
PERFORM EXISTS (SELECT warehouse.get_product_received_detail_json(null));
PERFORM EXISTS (SELECT warehouse.get_product_received_detail_qty_json(null));
PERFORM EXISTS (SELECT warehouse.get_product_received_json(null));
PERFORM EXISTS (SELECT warehouse.get_product_repack_cost_json(null));
PERFORM EXISTS (SELECT warehouse.get_product_repack_detail_json(null));
PERFORM EXISTS (SELECT warehouse.get_product_repack_json(null));
PERFORM EXISTS (SELECT warehouse.get_product_repack_price(null, null, 0, 0.0));
PERFORM EXISTS (SELECT warehouse.get_product_request_detail_json(null));
PERFORM EXISTS (SELECT warehouse.get_product_request_json(null));
PERFORM EXISTS (SELECT warehouse.get_product_sales_profit(null, null, null, null, null));
PERFORM EXISTS (SELECT warehouse.get_product_sales_profit(null, null, null, null, null, null));
PERFORM EXISTS (SELECT warehouse.get_product_segment());
PERFORM EXISTS (SELECT warehouse.get_product_segment_json(null));
PERFORM EXISTS (SELECT warehouse.get_product_segments(null));
PERFORM EXISTS (SELECT warehouse.get_product_stocks_json(null));
PERFORM EXISTS (SELECT warehouse.get_product_taxes_json(null));
PERFORM EXISTS (SELECT warehouse.get_product_type());
PERFORM EXISTS (SELECT warehouse.get_product_type(null));
PERFORM EXISTS (SELECT warehouse.get_product_type_json(null));
PERFORM EXISTS (SELECT warehouse.get_product_uom_qrcodes_json(null));
PERFORM EXISTS (SELECT warehouse.get_product_uoms_json(null));
PERFORM EXISTS (SELECT warehouse.get_products_category(null, null, 0, FALSE));
PERFORM EXISTS (SELECT warehouse.get_products_convertion(null, null));
PERFORM EXISTS (SELECT warehouse.get_products_json(null));
PERFORM EXISTS (SELECT warehouse.get_products_pbuy_pstock());
PERFORM EXISTS (SELECT warehouse.get_room_types());
PERFORM EXISTS (SELECT warehouse.get_rooms_admin(0));
PERFORM EXISTS (SELECT warehouse.get_rooms_instance(null));
PERFORM EXISTS (SELECT warehouse.get_rooms_json(null));
PERFORM EXISTS (SELECT warehouse.get_rooms_stocks_expedition_json(null));
PERFORM EXISTS (SELECT warehouse.get_rooms_stocks_instances(null, null));
PERFORM EXISTS (SELECT warehouse.get_rooms_stocks_instances_all());
PERFORM EXISTS (SELECT warehouse.get_rooms_stocks_instances_json(null));
PERFORM EXISTS (SELECT warehouse.get_rooms_stocks_instances_qty_avaliable(null, 0.0));
PERFORM EXISTS (SELECT warehouse.get_rooms_stocks_json(null));
PERFORM EXISTS (SELECT warehouse.get_rooms_stocks_outlets_json(null));
PERFORM EXISTS (SELECT warehouse.get_rooms_stocks_sales_json(null));
PERFORM EXISTS (SELECT warehouse.get_rooms_stocks_store_json(null));
PERFORM EXISTS (SELECT warehouse.get_rooms_stocks_transportation_json(null));
PERFORM EXISTS (SELECT warehouse.get_sales_rooms_json(null));
PERFORM EXISTS (SELECT warehouse.get_stock_cogs_avg(null, null, FALSE, null));
PERFORM EXISTS (SELECT warehouse.get_stock_ledger_bg_ed(CURRENT_DATE, CURRENT_DATE, null, FALSE, null, null, null, FALSE));
PERFORM EXISTS (SELECT warehouse.get_stock_ledger_bg_ed_by_wh(CURRENT_DATE, CURRENT_DATE, null, FALSE, null, null, null, FALSE));
PERFORM EXISTS (SELECT warehouse.get_stock_opname_batch_json(null));
PERFORM EXISTS (SELECT warehouse.get_stock_opname_detail_json(null));
PERFORM EXISTS (SELECT warehouse.get_stock_opname_json(null));
PERFORM EXISTS (SELECT warehouse.get_stock_opname_system_qty(null, FALSE));
PERFORM EXISTS (SELECT warehouse.get_stock_opname_uom_json(null));
PERFORM EXISTS (SELECT warehouse.get_store_rooms_json(null));
PERFORM EXISTS (SELECT warehouse.get_sub_categories(null, null));
PERFORM EXISTS (SELECT warehouse.get_transportation_rooms_json(null));
PERFORM EXISTS (SELECT warehouse.get_unit_for_sales_forecast(null, null));
PERFORM EXISTS (SELECT warehouse.get_unit_price_by_default_unit(null, null, 0.0));
PERFORM EXISTS (SELECT warehouse.get_unit_price_by_selected_unit(null, null, null, 0.0));
PERFORM EXISTS (SELECT warehouse.get_unit_price_from_inv_ledger(null, null, null, null, null));
PERFORM EXISTS (SELECT warehouse.get_uom(null));
PERFORM EXISTS (SELECT warehouse.get_uom_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_all_rooms_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_category_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_expedition_rooms_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_instance_rooms_admin_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_instance_rooms_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_outlet_rooms_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_product_allocation_detail_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_product_allocation_detail_qty_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_product_allocation_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_product_qrcodes_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_product_received_detail_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_product_received_detail_qty_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_product_received_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_product_repack_cost_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_product_repack_detail_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_product_repack_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_product_request_detail_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_product_request_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_product_segment_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_product_stocks_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_product_taxes_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_product_type_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_product_uom_qrcodes_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_product_uoms_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_products_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_rooms_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_rooms_stocks_expedition_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_rooms_stocks_instances_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_rooms_stocks_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_rooms_stocks_outlets_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_rooms_stocks_sales_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_rooms_stocks_store_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_rooms_stocks_transportation_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_sales_rooms_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_stock_opname_batch_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_stock_opname_detail_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_stock_opname_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_stock_opname_uom_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_store_rooms_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_transportation_rooms_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_uom_json(null));
PERFORM EXISTS (SELECT warehouse.get_view_warehouse_category_json(null));
PERFORM EXISTS (SELECT warehouse.get_warehouse_by_warehouse_config(null));
PERFORM EXISTS (SELECT warehouse.get_warehouse_category());
PERFORM EXISTS (SELECT warehouse.get_warehouse_category_json(null));
PERFORM EXISTS (SELECT warehouse.get_warehouse_code(null));
PERFORM EXISTS (SELECT warehouse.get_warehouse_for_inventory_transfer(null));
PERFORM EXISTS (SELECT warehouse.get_warehouse_lookup(null));
PERFORM EXISTS (SELECT warehouse.get_warehouse_parent_code(null));
PERFORM EXISTS (SELECT warehouse.get_warehouse_sales_to(FALSE, FALSE, null, null));
PERFORM EXISTS (SELECT warehouse.get_warehouse_sales_to_list(null, null));
PERFORM EXISTS (SELECT warehouse.get_warehouse_to_edit(null, null));
PERFORM EXISTS (SELECT warehouse.get_warehouses_by_instances(null));
PERFORM EXISTS (SELECT warehouse.insert_inventory_ledger(null));
PERFORM EXISTS (SELECT warehouse.insert_product_data(null, 0, null, null, null));
PERFORM EXISTS (SELECT warehouse.insert_product_received_detail(null, null));
PERFORM EXISTS (SELECT warehouse.insert_product_received_qty(null, 0.0));
PERFORM EXISTS (SELECT warehouse.insert_request_products_detail(null, null));
PERFORM EXISTS (SELECT warehouse.insert_rooms_stock_in(0, null, null, null, 0, 0.0, 0.0));
PERFORM EXISTS (SELECT warehouse.insert_rooms_stock_in_execute(null, 0, null, null, 0.0, null, 0, 0.0));
PERFORM EXISTS (SELECT warehouse.insert_stock_opname(null, null, null, null, null, FALSE, null, 0, CURRENT_DATE));
PERFORM EXISTS (SELECT warehouse.insert_stock_opname(null, null, null, null, null, FALSE, null));
PERFORM EXISTS (SELECT warehouse.insert_stock_opname_batch(null, null, FALSE));
PERFORM EXISTS (SELECT warehouse.insert_stock_opname_batch(null));
PERFORM EXISTS (SELECT warehouse.insert_stock_opname_detail(null, null, null));
PERFORM EXISTS (SELECT warehouse.insert_stock_opname_detail(null, null, null, 0, FALSE));
PERFORM EXISTS (SELECT warehouse.insert_stock_opname_detail(null, null));
PERFORM EXISTS (SELECT warehouse.item_stock_filter(FALSE, null, null, null));
PERFORM EXISTS (SELECT warehouse.items_list(null));
PERFORM EXISTS (SELECT warehouse.items_list_without_stocks(null, null));
PERFORM EXISTS (SELECT warehouse.list_finish_goods_analyze_product_lookup());
PERFORM EXISTS (SELECT warehouse.list_finished_goods_analyze_item(null));
PERFORM EXISTS (SELECT warehouse.list_finished_goods_analyze_report(null, null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT warehouse.list_finished_goods_analyze_warehouse());
PERFORM EXISTS (SELECT warehouse.list_kind_unit());
PERFORM EXISTS (SELECT warehouse.list_master_group(null, FALSE));
PERFORM EXISTS (SELECT warehouse.list_master_group_archive(null));
PERFORM EXISTS (SELECT warehouse.list_master_product(null, null));
PERFORM EXISTS (SELECT warehouse.list_master_segmen(null, FALSE));
PERFORM EXISTS (SELECT warehouse.list_master_segmen_archive(null));
PERFORM EXISTS (SELECT warehouse.list_product(null, null, FALSE, FALSE, FALSE, FALSE, null));
PERFORM EXISTS (SELECT warehouse.list_product_archive(null));
PERFORM EXISTS (SELECT warehouse.list_product_for_pr(null, null, null, FALSE, FALSE, FALSE, FALSE, null));
PERFORM EXISTS (SELECT warehouse.list_product_for_pr_revision(null, null, FALSE, FALSE, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT warehouse.list_product_for_purchase_lite(null, null, null, FALSE, FALSE, FALSE, FALSE, null));
PERFORM EXISTS (SELECT warehouse.list_product_received(null, null));
PERFORM EXISTS (SELECT warehouse.list_product_received_detail(null));
PERFORM EXISTS (SELECT warehouse.list_product_repack(null, null, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT warehouse.list_product_uom_price_contract(null, FALSE, null, null));
PERFORM EXISTS (SELECT warehouse.list_products(null, null, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT warehouse.list_products_request(null, null));
PERFORM EXISTS (SELECT warehouse.list_products_request_detail(null));
PERFORM EXISTS (SELECT warehouse.list_products_request_detail_report(null));
PERFORM EXISTS (SELECT warehouse.list_products_request_detail_report());
PERFORM EXISTS (SELECT warehouse.list_products_request_report(null, null, FALSE, FALSE, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT warehouse.list_rooms_stock(null, null));
PERFORM EXISTS (SELECT warehouse.list_stock_ending(null, null, FALSE, null));
PERFORM EXISTS (SELECT warehouse.list_stock_ending_by_batchnumber(null, null, FALSE, null));
PERFORM EXISTS (SELECT warehouse.list_stock_ending_by_batchnumber_new(null, null, FALSE, null));
PERFORM EXISTS (SELECT warehouse.list_stock_ending_by_batchnumber_report(null, null, FALSE, null));
PERFORM EXISTS (SELECT warehouse.list_stock_ending_by_qty(null, null, null, FALSE, FALSE, null, null));
PERFORM EXISTS (SELECT warehouse.list_stock_ending_by_summary(null, null, null, FALSE, FALSE, null));
PERFORM EXISTS (SELECT warehouse.list_stock_ending_by_value(null, null, null, FALSE, FALSE, null));
PERFORM EXISTS (SELECT warehouse.list_stock_ending_report(null, null, FALSE, null));
PERFORM EXISTS (SELECT warehouse.list_stock_ledger(CURRENT_DATE, CURRENT_DATE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT warehouse.list_stock_ledger_by_warehouse(null, CURRENT_DATE, CURRENT_DATE, null, FALSE, null, null));
PERFORM EXISTS (SELECT warehouse.list_stock_ledger_by_warehouse_report(CURRENT_DATE, CURRENT_DATE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT warehouse.list_stock_opname_detail(null, null));
PERFORM EXISTS (SELECT warehouse.list_stock_opname_products(null, null, null, FALSE, null, 0));
PERFORM EXISTS (SELECT warehouse.list_stock_opname_products(null, null, null, FALSE, null));
PERFORM EXISTS (SELECT warehouse.list_stock_opname_products(null, null, FALSE, null, FALSE, null));
PERFORM EXISTS (SELECT warehouse.list_stock_opname_uom(null));
PERFORM EXISTS (SELECT warehouse.list_stock_warehouse());
PERFORM EXISTS (SELECT warehouse.list_warehouse(null, FALSE));
PERFORM EXISTS (SELECT warehouse.list_warehouse_archive(null));
PERFORM EXISTS (SELECT warehouse.list_warehouse_category(null, FALSE));
PERFORM EXISTS (SELECT warehouse.list_warehouse_category_archive(null));
PERFORM EXISTS (SELECT warehouse.list_warehouse_for_finish_goods_analyze_lookup(null));
PERFORM EXISTS (SELECT warehouse.list_warehouse_for_stock_taking_byvalue_lookup());
PERFORM EXISTS (SELECT warehouse.list_warehouse_stock_ending());
PERFORM EXISTS (SELECT warehouse.print_stock_ledger_report(CURRENT_DATE, CURRENT_DATE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT warehouse.product_by_centralized_price(null, null, FALSE, null, FALSE, null, FALSE, null, FALSE, null, null, null, FALSE, null));
PERFORM EXISTS (SELECT warehouse.product_by_centralized_price_sales_lite(null, null, FALSE, null, FALSE, null, FALSE, null, FALSE, null, null, null, FALSE, null, null));
PERFORM EXISTS (SELECT warehouse.product_filter_by_category_etc(FALSE, null, FALSE, null, FALSE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT warehouse.product_filter_by_category_for_so(FALSE, null, FALSE, null, FALSE, null, FALSE, null, null, null, null, FALSE));
PERFORM EXISTS (SELECT warehouse.set_inventory_insert_ratio_default(null, null));
PERFORM EXISTS (SELECT warehouse.set_new_master_group(null, null, FALSE, null, null, null, null));
PERFORM EXISTS (SELECT warehouse.set_new_master_segmen(null, null, FALSE, null, FALSE));
PERFORM EXISTS (SELECT warehouse.set_new_product_received(null, CURRENT_DATE, null, null, null));
PERFORM EXISTS (SELECT warehouse.set_new_products(null, null, null, null, null, null, null, null, null, null, null, null, 0.0, null, null, 0.0, null, null, 0.0, null, null, null, null, null, 0.0, 0.0, null, FALSE, FALSE, FALSE, FALSE, null, null, null, null));
PERFORM EXISTS (SELECT warehouse.set_new_products_allocation(null, CURRENT_DATE, null, null, null, null, 0, null, null, null, 0, 0, null, null));
PERFORM EXISTS (SELECT warehouse.set_new_products_request(null, CURRENT_DATE, null, CURRENT_DATE, null, null, null, null, null, null, null));
PERFORM EXISTS (SELECT warehouse.set_new_products_request(null, CURRENT_DATE, null, CURRENT_DATE, null, null, null, null, null, null, null, 0, 0, null, null));
PERFORM EXISTS (SELECT warehouse.set_new_products_unit(null, null));
PERFORM EXISTS (SELECT warehouse.set_new_warehouse(null, null, null, null, null, FALSE, null, null));
PERFORM EXISTS (SELECT warehouse.set_new_warehouse_category(null, null, FALSE, null));
PERFORM EXISTS (SELECT warehouse.set_new_warehouse_top(null, null, null, null, FALSE, null, null));
PERFORM EXISTS (SELECT warehouse.set_product_default_uom_ratio());
PERFORM EXISTS (SELECT warehouse.set_stock_opname_child_is_new(null, FALSE, null));
PERFORM EXISTS (SELECT warehouse.stock_filter(FALSE, null, null, null));
PERFORM EXISTS (SELECT warehouse.stock_filter(FALSE, null, null, null, null));
PERFORM EXISTS (SELECT warehouse.update_old_master_category(null));
PERFORM EXISTS (SELECT warehouse.update_old_master_segmen(null));
PERFORM EXISTS (SELECT warehouse.update_old_products(null));
PERFORM EXISTS (SELECT warehouse.update_old_products_detail(null));
PERFORM EXISTS (SELECT warehouse.update_old_products_detail(null, null));
PERFORM EXISTS (SELECT warehouse.update_old_products_detail_new(null, null));
PERFORM EXISTS (SELECT warehouse.update_old_warehouse(null));
PERFORM EXISTS (SELECT warehouse.update_old_warehouse_admin(null, null));
PERFORM EXISTS (SELECT warehouse.update_old_warehouse_category(null));
PERFORM EXISTS (SELECT warehouse.update_product_allocation_detail(null));
PERFORM EXISTS (SELECT warehouse.update_product_received_detail(null));
PERFORM EXISTS (SELECT warehouse.update_product_received_detail_qty(null, null, 0.0, null));
PERFORM EXISTS (SELECT warehouse.update_product_received_detail_qty(null, null, null, 0.0, null, 0));
PERFORM EXISTS (SELECT warehouse.update_product_received_detail_qty(null, null, 0.0, null, null, null, 0, 0));
PERFORM EXISTS (SELECT warehouse.update_product_received_detail_qty_different(null, 0.0, null));
PERFORM EXISTS (SELECT warehouse.update_products_buying_price(null));
PERFORM EXISTS (SELECT warehouse.update_qty_available_item_stock_list(null, 0));
PERFORM EXISTS (SELECT warehouse.update_rooms_stocks_out(null, null, null, 0.0, null, 0));
PERFORM EXISTS (SELECT warehouse.update_rooms_stocks_out(null, null, null, 0, 0.0, null, 0));
PERFORM EXISTS (SELECT warehouse.update_stock_opaname_real_stock(null));
PERFORM EXISTS (SELECT warehouse.update_stock_opname_detail(null));
PERFORM EXISTS (SELECT warehouse.update_stock_opname_uom(null));
PERFORM EXISTS (SELECT warehouse.validate_group(null, null));
PERFORM EXISTS (SELECT warehouse.validate_group_name(null));
PERFORM EXISTS (SELECT warehouse.validate_group_name_archive(null));
PERFORM EXISTS (SELECT warehouse.validate_master_segmen_name(null));
PERFORM EXISTS (SELECT warehouse.validate_product_allocation_detail(null));
PERFORM EXISTS (SELECT warehouse.validate_product_code_edit(null, null));
PERFORM EXISTS (SELECT warehouse.validate_product_code_edit_archived(null, null));
PERFORM EXISTS (SELECT warehouse.validate_product_name_edit(null, null));
PERFORM EXISTS (SELECT warehouse.validate_product_qrcode_edit(null, null));
PERFORM EXISTS (SELECT warehouse.validate_products_barcode(null));
PERFORM EXISTS (SELECT warehouse.validate_products_barcode_archived(null));
PERFORM EXISTS (SELECT warehouse.validate_products_code(null));
PERFORM EXISTS (SELECT warehouse.validate_products_code_archived(null));
PERFORM EXISTS (SELECT warehouse.validate_products_code_edit(null, null));
PERFORM EXISTS (SELECT warehouse.validate_products_name(null));
PERFORM EXISTS (SELECT warehouse.validate_products_name_archived(null));
PERFORM EXISTS (SELECT warehouse.validate_stock_opname_batch(null));
PERFORM EXISTS (SELECT warehouse.validate_stock_opname_batch_price(null));
PERFORM EXISTS (SELECT warehouse.validate_stock_opname_detail(null));
PERFORM EXISTS (SELECT warehouse.validate_warehouse_category_edit_name(null, null));
PERFORM EXISTS (SELECT warehouse.validate_warehouse_category_name(null));
PERFORM EXISTS (SELECT warehouse.validate_warehouse_category_name_archived(null));
PERFORM EXISTS (SELECT warehouse.validate_warehouse_code(null));
PERFORM EXISTS (SELECT warehouse.validate_warehouse_code_archived(null));
PERFORM EXISTS (SELECT warehouse.validate_warehouse_code_edit(null, null));
PERFORM EXISTS (SELECT warehouse.validate_warehouse_code_new(null));
PERFORM EXISTS (SELECT warehouse.validate_warehouse_edit_code(null, null));
PERFORM EXISTS (SELECT warehouse.validate_warehouse_edit_code_new(null, null));
PERFORM EXISTS (SELECT warehouse.validate_warehouse_edit_name(null));
PERFORM EXISTS (SELECT warehouse.validate_warehouse_name(null));
PERFORM EXISTS (SELECT warehouse.validate_warehouse_name_edit(null, null));
PERFORM EXISTS (SELECT warehouse.validate_warehouse_name_new(null));
PERFORM EXISTS (SELECT warehouse.validate_warehouse_name_warehouse(null));
PERFORM EXISTS (SELECT warehouse.validate_warehouse_name_warehouse_archived(null));
PERFORM EXISTS (SELECT warehouse."warehouse.validate_warehouse_edit_name"(null, null));
PERFORM EXISTS (SELECT warehouse.warehouse_stock(null, null, null));
PERFORM EXISTS (SELECT warehouse.warehouse_stock_all(null));
PERFORM EXISTS (SELECT warehouse.warehouse_stock_batchno_filter(null, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT warehouse.warehouse_stock_batchno_for_inv_transfer(null, null, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT warehouse.warehouse_stock_filter(null, FALSE, null, null, null));
PERFORM EXISTS (SELECT warehouse.warehouse_stock_filter_category_delivery(FALSE, null, FALSE, null, FALSE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT warehouse.warehouse_stock_filter_category_etc(FALSE, null, FALSE, null, FALSE, null, FALSE, null, null, null));
PERFORM EXISTS (SELECT warehouse.warehouse_stock_filter_category_new(FALSE, null, FALSE, null, FALSE, null, FALSE, null, null, null, null, FALSE));
PERFORM EXISTS (SELECT warehouse.warehouse_stock_filter_category_sales(FALSE, null, FALSE, null, FALSE, null, null));
PERFORM EXISTS (SELECT warehouse.warehouse_stock_filter_category_sales_new(FALSE, null, FALSE, null, FALSE, null, null, FALSE, null));
END;