BEGIN
PERFORM EXISTS (SELECT wsm.add_item_to_cart(null));
PERFORM EXISTS (SELECT wsm.add_outlet_feedback(null));
PERFORM EXISTS (SELECT wsm.agenda_schedule(null));
PERFORM EXISTS (SELECT wsm.all_schedule(null));
PERFORM EXISTS (SELECT wsm.check_in(null));
PERFORM EXISTS (SELECT wsm.commit_transaction(null));
PERFORM EXISTS (SELECT wsm.commit_transaction_process(null, null));
PERFORM EXISTS (SELECT wsm.delete_reminder(null));
PERFORM EXISTS (SELECT wsm.error(null));
PERFORM EXISTS (SELECT wsm.error_multilanguage(null, null));
PERFORM EXISTS (SELECT wsm.get_all_history_payments_by_date(null, now(), now()));
PERFORM EXISTS (SELECT wsm.get_body_by_key(null, null));
PERFORM EXISTS (SELECT wsm.get_curr_ar_collection(null));
PERFORM EXISTS (SELECT wsm.get_curr_certain_product(null));
PERFORM EXISTS (SELECT wsm.get_curr_incentive_sales_person(null));
PERFORM EXISTS (SELECT wsm.get_curr_main_salary(null));
PERFORM EXISTS (SELECT wsm.get_curr_noo_cash(null));
PERFORM EXISTS (SELECT wsm.get_curr_sales_turnover(null));
PERFORM EXISTS (SELECT wsm.get_curr_selling_price(null));
PERFORM EXISTS (SELECT wsm.get_curr_selling_price_by_qty(null));
PERFORM EXISTS (SELECT wsm.get_history_payments(null));
PERFORM EXISTS (SELECT wsm.get_image(null));
PERFORM EXISTS (SELECT wsm.get_invoice_by_id(null));
PERFORM EXISTS (SELECT wsm.get_invoice_by_id_json(null, null));
PERFORM EXISTS (SELECT wsm.get_invoices(null, now(), now(), 0));
PERFORM EXISTS (SELECT wsm.get_last_sales_tracking(null));
PERFORM EXISTS (SELECT wsm.get_me(null));
PERFORM EXISTS (SELECT wsm.get_new_pricelist(null));
PERFORM EXISTS (SELECT wsm.get_outlet_categories(null));
PERFORM EXISTS (SELECT wsm.get_outlet_feedback(null));
PERFORM EXISTS (SELECT wsm.get_outlet_invoices(null));
PERFORM EXISTS (SELECT wsm.get_outlet_location(null));
PERFORM EXISTS (SELECT wsm.get_outlets(null));
PERFORM EXISTS (SELECT wsm.get_outlets_by_id(null));
PERFORM EXISTS (SELECT wsm.get_payment_by_id(null, null));
PERFORM EXISTS (SELECT wsm.get_payment_by_invoice(null));
PERFORM EXISTS (SELECT wsm.get_presence_in_day(null));
PERFORM EXISTS (SELECT wsm.get_pricelist(null));
PERFORM EXISTS (SELECT wsm.get_pricelist_sales_to(null));
PERFORM EXISTS (SELECT wsm.get_product_tracking_stocks(null));
PERFORM EXISTS (SELECT wsm.get_product_uoms(null));
PERFORM EXISTS (SELECT wsm.get_remaining_invoice(null));
PERFORM EXISTS (SELECT wsm.get_reminder(null));
PERFORM EXISTS (SELECT wsm.get_replacement_history(null));
PERFORM EXISTS (SELECT wsm.get_sales_ar_history(null));
PERFORM EXISTS (SELECT wsm.get_sales_max_checkin_range(null));
PERFORM EXISTS (SELECT wsm.get_schedules(null));
PERFORM EXISTS (SELECT wsm.get_selling_in_history(null));
PERFORM EXISTS (SELECT wsm.get_take_home_pay(null));
PERFORM EXISTS (SELECT wsm.get_term_payment_jsonb(null));
PERFORM EXISTS (SELECT wsm.get_termin(null));
PERFORM EXISTS (SELECT wsm.get_token_id(null));
PERFORM EXISTS (SELECT wsm.get_transaction_log(null));
PERFORM EXISTS (SELECT wsm.get_visiting_history(null));
PERFORM EXISTS (SELECT wsm.insert_cart(null));
PERFORM EXISTS (SELECT wsm.insert_outlet(null));
PERFORM EXISTS (SELECT wsm.insert_outlet_reminder(null));
PERFORM EXISTS (SELECT wsm.invoices_by_outlet(null, null));
PERFORM EXISTS (SELECT wsm.is_already_check_in(null));
PERFORM EXISTS (SELECT wsm.is_check_in(null, null));
PERFORM EXISTS (SELECT wsm.is_outlet_open(null, null));
PERFORM EXISTS (SELECT wsm.is_product_replaceable(null));
PERFORM EXISTS (SELECT wsm.is_product_replaced(null, null, null));
PERFORM EXISTS (SELECT wsm.is_qr_code_available(null));
PERFORM EXISTS (SELECT wsm.is_visited(null, null));
PERFORM EXISTS (SELECT wsm.login(null));
PERFORM EXISTS (SELECT wsm.outlet_by_code(null, null));
PERFORM EXISTS (SELECT wsm.outlet_informations(null, null));
PERFORM EXISTS (SELECT wsm.outlet_selling_in_info(null));
PERFORM EXISTS (SELECT wsm.payment_by_invoice(null, null, now(), now(), 0));
PERFORM EXISTS (SELECT wsm.process_user_quota_info(null, FALSE, null));
PERFORM EXISTS (SELECT wsm.product_informations(null));
PERFORM EXISTS (SELECT wsm.refresh_outlet_cart(null));
PERFORM EXISTS (SELECT wsm.refresh_outlet_cart_detail(null));
PERFORM EXISTS (SELECT wsm.remove_item_from_cart(null));
PERFORM EXISTS (SELECT wsm.replacement_history_by_outlet(null, null, now(), now(), 0));
PERFORM EXISTS (SELECT wsm.sales_payment(null, null));
PERFORM EXISTS (SELECT wsm.send_replacement(null));
PERFORM EXISTS (SELECT wsm.set_payment(null));
PERFORM EXISTS (SELECT wsm.set_termin(null));
PERFORM EXISTS (SELECT wsm.set_tracking_sales(null));
PERFORM EXISTS (SELECT wsm.success(null));
PERFORM EXISTS (SELECT wsm.success_with_message(null));
PERFORM EXISTS (SELECT wsm.transaction_log(null, now(), now(), 0));
PERFORM EXISTS (SELECT wsm.unauthorized());
PERFORM EXISTS (SELECT wsm.upload_image(null, null));
PERFORM EXISTS (SELECT wsm.visiting_qr_code(null));
END;