BEGIN
PERFORM EXISTS (SELECT human_resources.create_room_sales(null));
PERFORM EXISTS (SELECT human_resources.get_brands_ambassador_json(null));
PERFORM EXISTS (SELECT human_resources.get_brands_ambassador_sales_json(null));
PERFORM EXISTS (SELECT human_resources.get_business_partner_address_json(null));
PERFORM EXISTS (SELECT human_resources.get_business_partner_bank_json(null));
PERFORM EXISTS (SELECT human_resources.get_business_partner_contact_json(null));
PERFORM EXISTS (SELECT human_resources.get_employee_by_instance(null, null));
PERFORM EXISTS (SELECT human_resources.get_employee_id1(null));
PERFORM EXISTS (SELECT human_resources.get_employee_not_registered());
PERFORM EXISTS (SELECT human_resources.get_employee_positions_json(null));
PERFORM EXISTS (SELECT human_resources.get_employee_registered());
PERFORM EXISTS (SELECT human_resources.get_employee_sales_json(null));
PERFORM EXISTS (SELECT human_resources.get_employees(null));
PERFORM EXISTS (SELECT human_resources.get_employees_all());
PERFORM EXISTS (SELECT human_resources.get_employees_id_user_system(null));
PERFORM EXISTS (SELECT human_resources.get_employees_json(null));
PERFORM EXISTS (SELECT human_resources.get_employees_position_instance(null));
PERFORM EXISTS (SELECT human_resources.get_employees_sales_instance(null, null, null));
PERFORM EXISTS (SELECT human_resources.get_mentions(null, null));
PERFORM EXISTS (SELECT human_resources.get_mentions(null, 0));
PERFORM EXISTS (SELECT human_resources.get_mentions_by_positions(null, null));
PERFORM EXISTS (SELECT human_resources.get_mentions_multi_role(null, null));
PERFORM EXISTS (SELECT human_resources.get_new_update_employee(null));
PERFORM EXISTS (SELECT human_resources.get_sales_person(null));
PERFORM EXISTS (SELECT human_resources.get_sales_type(null));
PERFORM EXISTS (SELECT human_resources.get_user_id_session(0));
PERFORM EXISTS (SELECT human_resources.get_view_brands_ambassador_json(null));
PERFORM EXISTS (SELECT human_resources.get_view_brands_ambassador_sales_json(null));
PERFORM EXISTS (SELECT human_resources.get_view_business_partner_address_json(null));
PERFORM EXISTS (SELECT human_resources.get_view_business_partner_bank_json(null));
PERFORM EXISTS (SELECT human_resources.get_view_business_partner_contact_json(null));
PERFORM EXISTS (SELECT human_resources.get_view_employee_positions_json(null));
PERFORM EXISTS (SELECT human_resources.get_view_employee_sales_json(null));
PERFORM EXISTS (SELECT human_resources.get_view_employees_json(null));
PERFORM EXISTS (SELECT human_resources.get_view_sales_groups_json(null));
PERFORM EXISTS (SELECT human_resources.insert_brands_employees(null, null, null, FALSE));
PERFORM EXISTS (SELECT human_resources.list_archive_employees(null));
PERFORM EXISTS (SELECT human_resources.list_brands_ambassador_and_sales(null, null));
PERFORM EXISTS (SELECT human_resources.list_brands_ambassador_employed(null, null, FALSE));
PERFORM EXISTS (SELECT human_resources.list_brands_ambassador_sales(null, FALSE));
PERFORM EXISTS (SELECT human_resources.list_brands_ambassador_unemployed(null, null, FALSE, null));
PERFORM EXISTS (SELECT human_resources.list_employees_archive(null));
PERFORM EXISTS (SELECT human_resources.list_of_employees_by_instance(null));
PERFORM EXISTS (SELECT human_resources.list_of_sales_expenses(null, null, null));
PERFORM EXISTS (SELECT human_resources.list_of_sales_incentive(null, null));
PERFORM EXISTS (SELECT human_resources.list_of_sales_performance(FALSE, null, null));
PERFORM EXISTS (SELECT human_resources.open_get_employees());
PERFORM EXISTS (SELECT human_resources.remove_new_ambassador(null, null));
PERFORM EXISTS (SELECT human_resources.set_attendance_salesman(null));
PERFORM EXISTS (SELECT human_resources.set_image_id_for_employee(null, null));
PERFORM EXISTS (SELECT human_resources.set_new_brands_ambassador(null, null));
PERFORM EXISTS (SELECT human_resources.set_target_ar_collection(null, null, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT human_resources.set_target_certain_product(null, null, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT human_resources.set_target_noo_cash(null));
PERFORM EXISTS (SELECT human_resources.set_target_noo_cash(null, null, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT human_resources.set_target_outlet_pareto(null, null, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT human_resources.set_target_turnover(null, null, null, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT human_resources.update_old_brands_ambassador(null, null));
PERFORM EXISTS (SELECT human_resources.validate_brand_ambassador_in_use(null, null));
PERFORM EXISTS (SELECT human_resources.validate_emp_nik_edit(null, null));
PERFORM EXISTS (SELECT human_resources.validate_employe_code_edit(null, null));
PERFORM EXISTS (SELECT human_resources.validate_employee_code(null));
PERFORM EXISTS (SELECT human_resources.validate_employee_code_archived(null));
PERFORM EXISTS (SELECT human_resources.validate_employee_code_archived_data(null));
PERFORM EXISTS (SELECT human_resources.validate_employee_name(null));
PERFORM EXISTS (SELECT human_resources.validate_employee_name_archived(null));
END;