BEGIN
PERFORM EXISTS (SELECT android.authentication(null, null));
PERFORM EXISTS (SELECT android.auto_recap_user_quote(null));
PERFORM EXISTS (SELECT android.check_in(null));
PERFORM EXISTS (SELECT android.check_outlet_code(null));
PERFORM EXISTS (SELECT android.check_update(0));
PERFORM EXISTS (SELECT android.create_log_transaction(null));
PERFORM EXISTS (SELECT android.create_product_replacement(null));
PERFORM EXISTS (SELECT android.delete_all_transaction_sales_today(null, 0));
PERFORM EXISTS (SELECT android.delete_incentive_from_invoice_today(null, 0));
PERFORM EXISTS (SELECT android.delete_invoice_today(null, 0));
PERFORM EXISTS (SELECT android.delete_payment_today(null, 0));
PERFORM EXISTS (SELECT android.delete_sales_deposit(null));
PERFORM EXISTS (SELECT android.delete_selling_in_today(null, 0));
PERFORM EXISTS (SELECT android.delete_shipment_today(null));
PERFORM EXISTS (SELECT android.delete_transaction_history_today(null, 0));
PERFORM EXISTS (SELECT android.fc_generate_branch_code(null));
PERFORM EXISTS (SELECT android.geodistance(0.0, 0.0, 0.0, 0.0));
PERFORM EXISTS (SELECT android.get_all_invoice_by_outlet(null));
PERFORM EXISTS (SELECT android.get_all_outlets());
PERFORM EXISTS (SELECT android.get_all_sales_invoice());
PERFORM EXISTS (SELECT android.get_all_shown_levels());
PERFORM EXISTS (SELECT android.get_bandwidth_monitoring_data(CURRENT_DATE, CURRENT_DATE, null));
PERFORM EXISTS (SELECT android.get_count_invoice(null));
PERFORM EXISTS (SELECT android.get_count_payment(null, now()));
PERFORM EXISTS (SELECT android.get_current_ar_collection(null));
PERFORM EXISTS (SELECT android.get_current_certain_product(null));
PERFORM EXISTS (SELECT android.get_current_incentive_sales_person(null));
PERFORM EXISTS (SELECT android.get_current_main_salary(null));
PERFORM EXISTS (SELECT android.get_current_noo_cash(null));
PERFORM EXISTS (SELECT android.get_current_sales_turnover(null));
PERFORM EXISTS (SELECT android.get_current_selling_price(null, 0, 0.0, null, null));
PERFORM EXISTS (SELECT android.get_current_selling_price_by_qty(null, 0, 0.0, null));
PERFORM EXISTS (SELECT android.get_debt_remaining(null));
PERFORM EXISTS (SELECT android.get_debt_remaining_today(null, null));
PERFORM EXISTS (SELECT android.get_deposit_by_date(null));
PERFORM EXISTS (SELECT android.get_deposit_item_by_id_payment(null));
PERFORM EXISTS (SELECT android.get_deposit_summary_total(null));
PERFORM EXISTS (SELECT android.get_domain());
PERFORM EXISTS (SELECT android.get_employee_position_by_id(null));
PERFORM EXISTS (SELECT android.get_fixed_selling_price(null));
PERFORM EXISTS (SELECT android.get_incentive_active_from_invoice());
PERFORM EXISTS (SELECT android.get_instance_by_id(null));
PERFORM EXISTS (SELECT android.get_instance_id(null));
PERFORM EXISTS (SELECT android.get_instance_id_by_user_id(null));
PERFORM EXISTS (SELECT android.get_invoice_by_id_json(null));
PERFORM EXISTS (SELECT android.get_invoice_by_id_outlet_date(null));
PERFORM EXISTS (SELECT android.get_nearby_outlets(null, 0.0, 0.0));
PERFORM EXISTS (SELECT android.get_new_level_price_id(null));
PERFORM EXISTS (SELECT android.get_outlet_by_barcode(null));
PERFORM EXISTS (SELECT android.get_outlet_by_id_json(null));
PERFORM EXISTS (SELECT android.get_outlet_categories(null));
PERFORM EXISTS (SELECT android.get_outlet_invoices_json(null));
PERFORM EXISTS (SELECT android.get_outlet_invoices_summary_by_id_outlet(null));
PERFORM EXISTS (SELECT android.get_outlet_last_invoice_today(null, null));
PERFORM EXISTS (SELECT android.get_outlet_last_invoices(null));
PERFORM EXISTS (SELECT android.get_outlet_last_payment(null));
PERFORM EXISTS (SELECT android.get_outlet_last_payment_date(null, now()));
PERFORM EXISTS (SELECT android.get_outlet_last_visited_information(null));
PERFORM EXISTS (SELECT android.get_outlet_last_visiting(null));
PERFORM EXISTS (SELECT android.get_outlet_payment_by_id_json(null));
PERFORM EXISTS (SELECT android.get_outlet_payment_by_invoice_date(null, now()));
PERFORM EXISTS (SELECT android.get_outlet_payment_by_invoice_json(null));
PERFORM EXISTS (SELECT android.get_outlet_rooms_by_id_outlet(null));
PERFORM EXISTS (SELECT android.get_outlet_rooms_by_json(null));
PERFORM EXISTS (SELECT android.get_outlet_transaction_average(null, null, 0));
PERFORM EXISTS (SELECT android.get_outlet_visiting_history(null, 0));
PERFORM EXISTS (SELECT android.get_outlets(null));
PERFORM EXISTS (SELECT android.get_outlets_feedback(null));
PERFORM EXISTS (SELECT android.get_presence_in_day(null));
PERFORM EXISTS (SELECT android.get_pricelist(null));
PERFORM EXISTS (SELECT android.get_pricelist_sales_to(null));
PERFORM EXISTS (SELECT android.get_prices_by_id_product(null));
PERFORM EXISTS (SELECT android.get_prices_by_id_product_id_outlet(null, null));
PERFORM EXISTS (SELECT android.get_prices_for_pricelist(null));
PERFORM EXISTS (SELECT android.get_product_category_json(null));
PERFORM EXISTS (SELECT android.get_product_details(null));
PERFORM EXISTS (SELECT android.get_product_favorites());
PERFORM EXISTS (SELECT android.get_product_for_pricelist(null));
PERFORM EXISTS (SELECT android.get_product_for_pricelist_sales_to(null));
PERFORM EXISTS (SELECT android.get_product_images_json(null));
PERFORM EXISTS (SELECT android.get_product_qrcodes_json(null));
PERFORM EXISTS (SELECT android.get_product_replacement_by_jsonb(null));
PERFORM EXISTS (SELECT android.get_product_uoms_json(null));
PERFORM EXISTS (SELECT android.get_product_uoms_table(null));
PERFORM EXISTS (SELECT android.get_retur_by_id(null));
PERFORM EXISTS (SELECT android.get_retur_by_id_invoice(null));
PERFORM EXISTS (SELECT android.get_retur_details_by_id_invoice_detail(null, null));
PERFORM EXISTS (SELECT android.get_retur_details_by_id_retur(null, null));
PERFORM EXISTS (SELECT android.get_retur_summary());
PERFORM EXISTS (SELECT android.get_retur_summary_by_invoice_id(null));
PERFORM EXISTS (SELECT android.get_retur_summary_by_outlet(null));
PERFORM EXISTS (SELECT android.get_retur_summary_today());
PERFORM EXISTS (SELECT android.get_sales_current_stocks(null));
PERFORM EXISTS (SELECT android.get_sales_group_id_by_user_id(null));
PERFORM EXISTS (SELECT android.get_sales_incentive_today_json());
PERFORM EXISTS (SELECT android.get_sales_incentive_today_x());
PERFORM EXISTS (SELECT android.get_sales_incentive_total_json());
PERFORM EXISTS (SELECT android.get_sales_incentive_total_x());
PERFORM EXISTS (SELECT android.get_sales_invoices_today(now()));
PERFORM EXISTS (SELECT android.get_sales_last_visiting_date(now()));
PERFORM EXISTS (SELECT android.get_sales_last_visiting_today());
PERFORM EXISTS (SELECT android.get_sales_minimum_req());
PERFORM EXISTS (SELECT android.get_sales_outlet_visiting_reminder(null));
PERFORM EXISTS (SELECT android.get_sales_outlets(null));
PERFORM EXISTS (SELECT android.get_sales_payment_by_id_outlet_date(null));
PERFORM EXISTS (SELECT android.get_sales_payment_date(now()));
PERFORM EXISTS (SELECT android.get_sales_payment_grouped_by_outlet());
PERFORM EXISTS (SELECT android.get_sales_payment_item_by_id_outlet(null));
PERFORM EXISTS (SELECT android.get_sales_product_customize(null, null));
PERFORM EXISTS (SELECT android.get_sales_products());
PERFORM EXISTS (SELECT android.get_sales_products_by_id(null));
PERFORM EXISTS (SELECT android.get_sales_products_by_id_outlet(null));
PERFORM EXISTS (SELECT android.get_sales_stock_details(null));
PERFORM EXISTS (SELECT android.get_sales_stocks(null));
PERFORM EXISTS (SELECT android.get_sales_summary_json());
PERFORM EXISTS (SELECT android.get_sales_transaction_count_today());
PERFORM EXISTS (SELECT android.get_sales_visiting_count_today());
PERFORM EXISTS (SELECT android.get_sales_visiting_reminder(null));
PERFORM EXISTS (SELECT android.get_schedules(null));
PERFORM EXISTS (SELECT android.get_session_instance_id());
PERFORM EXISTS (SELECT android.get_session_user_id());
PERFORM EXISTS (SELECT android.get_sisa_total_hutang_by_id_outlet(null, null));
PERFORM EXISTS (SELECT android.get_summary_retur_invoice_today(null));
PERFORM EXISTS (SELECT android.get_take_home_pay(null));
PERFORM EXISTS (SELECT android.get_taxes_by_id_product(null));
PERFORM EXISTS (SELECT android.get_taxes_by_id_product_x(null));
PERFORM EXISTS (SELECT android.get_termin_by_id_json(null));
PERFORM EXISTS (SELECT android.get_termin_by_outlet_id(null));
PERFORM EXISTS (SELECT android.get_tracking_sales());
PERFORM EXISTS (SELECT android.get_tracking_sales_by_id(null));
PERFORM EXISTS (SELECT android.get_user(null));
PERFORM EXISTS (SELECT android.get_user_by_id(null));
PERFORM EXISTS (SELECT android.get_user_group_json());
PERFORM EXISTS (SELECT android.get_user_join_date_long(null));
PERFORM EXISTS (SELECT android.get_user_sales_group_json());
PERFORM EXISTS (SELECT android.get_user_sales_group_progress_json());
PERFORM EXISTS (SELECT android.get_warehouse_current_stocks(null));
PERFORM EXISTS (SELECT android.insert_images(null, null));
PERFORM EXISTS (SELECT android.is_already_checkin(null));
PERFORM EXISTS (SELECT android.list_of_invoice_outlet(FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null, FALSE, 0));
PERFORM EXISTS (SELECT android.list_of_invoice_outlet_detail_report());
PERFORM EXISTS (SELECT android.list_of_invoice_outlet_report(null, FALSE, CURRENT_DATE, CURRENT_DATE, FALSE, null, FALSE, null, null, FALSE, 0));
PERFORM EXISTS (SELECT android.list_sales_person_presence_and_invoice(null, CURRENT_DATE, CURRENT_DATE));
PERFORM EXISTS (SELECT android.login(null));
PERFORM EXISTS (SELECT android.outlet_add_feedback(null));
PERFORM EXISTS (SELECT android.outlet_insert(null));
PERFORM EXISTS (SELECT android.outlet_insert_from_local(null));
PERFORM EXISTS (SELECT android.outlet_retur_shipment(null));
PERFORM EXISTS (SELECT android.post_sales_outlet_visiting_reminder(null));
PERFORM EXISTS (SELECT android.price_in_uoms(null));
PERFORM EXISTS (SELECT android.refresh_outlet_cart_detail_qty(null));
PERFORM EXISTS (SELECT android.sales_create_stock_history(null));
PERFORM EXISTS (SELECT android.sales_create_stock_history_detail(null));
PERFORM EXISTS (SELECT android.sales_depositing(null));
PERFORM EXISTS (SELECT android.sales_do_retur(null));
PERFORM EXISTS (SELECT android.sales_incentive());
PERFORM EXISTS (SELECT android.sales_incentive1());
PERFORM EXISTS (SELECT android.sales_incentive_from_invoice(null));
PERFORM EXISTS (SELECT android.sales_incentive_from_invoice_update_by_checkin());
PERFORM EXISTS (SELECT android.sales_invoice_from_order(null, now(), 0, null));
PERFORM EXISTS (SELECT android.sales_order_save(null));
PERFORM EXISTS (SELECT android.sales_order_save_x(null));
PERFORM EXISTS (SELECT android.sales_payment(null));
PERFORM EXISTS (SELECT android.sales_payment_history());
PERFORM EXISTS (SELECT android.sales_payment_summary(null));
PERFORM EXISTS (SELECT android.sales_receive_from_order(null));
PERFORM EXISTS (SELECT android.sales_receive_retur(null));
PERFORM EXISTS (SELECT android.sales_shipment_from_order(null, null));
PERFORM EXISTS (SELECT android.sales_stock_updater(null));
PERFORM EXISTS (SELECT android.send_replacement(null, null));
PERFORM EXISTS (SELECT android.set_delivery_order_android_to_journal(null, null));
PERFORM EXISTS (SELECT android.set_payment_to_journal(null));
PERFORM EXISTS (SELECT android.set_product_favorite(null, FALSE));
PERFORM EXISTS (SELECT android.set_return_settlement_to_journal(null, null));
PERFORM EXISTS (SELECT android.set_termin(null, null));
PERFORM EXISTS (SELECT android.stock_updater_replacement(null));
PERFORM EXISTS (SELECT android.update_outlet(null));
PERFORM EXISTS (SELECT android.update_outlet_code(null));
PERFORM EXISTS (SELECT android.update_outlet_image(null));
PERFORM EXISTS (SELECT android.update_outlet_phone(null));
PERFORM EXISTS (SELECT android.update_outlet_status_x(null));
PERFORM EXISTS (SELECT android.validate_credit_limit_outlet(null, null));
PERFORM EXISTS (SELECT android.wsm_login(null));
END;